const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {fixture}=require('./member-fixture');
(async()=>{const f=await fixture();try{
 const p=await f.project('Cloud assignments','Autonomous project');
 const store=require('../server/connections').createConnections(f.root),key=store.issue('user_owner','Cloud agent verification','worker');store.close();
 const w=async(route,body)=>{const r=await fetch(f.base+route,{method:'POST',headers:{authorization:'Bearer '+key.token,'content-type':'application/json'},body:JSON.stringify(body||{})});assert.ok(r.ok,await r.clone().text());return r.json();};
 const t=await f.api(`/api/boards/${p.project.id}/chat/threads`,{method:'POST',body:{}}),j=await f.api(`/api/chat/threads/${t.id}/messages`,{method:'POST',body:{mode:'work',content:'Complete a three-stage assignment; stop at the missing dependency.'}});
 const fake=path.join(f.root,'cloud-codex.cjs');fs.writeFileSync(fake,`#!/usr/bin/env node\nconst fs=require('fs');let prompt='';process.stdin.on('data',d=>prompt+=d);process.stdin.on('end',()=>{const n=fs.existsSync('checkpoint.txt')?Number(fs.readFileSync('checkpoint.txt'))+1:1;fs.writeFileSync('checkpoint.txt',String(n));if(n===3&&!prompt.includes('Dependency restored'))process.exit(2);console.log(JSON.stringify({type:'thread.started',thread_id:'session-cloud-assignment'}));const state=n===1?'continue':n===2?'blocked':'completed';fs.writeFileSync(process.argv[process.argv.indexOf('-o')+1],JSON.stringify({state,summary:n===3?'Verified all three stages.':'Verified stage '+n,next_step:n===1?'Continue to the dependency check.':'',blocker:n===2?'The test server is not connected.':'',next_action:n===2?'Connect the test server, then resume work.':''}));});`,{mode:0o700});
 const config=path.join(f.root,'worker.json');fs.writeFileSync(config,JSON.stringify({origin:f.base,token:key.token,workspaceRoot:path.join(f.root,'projects'),codexCommand:fake,continuous:true,cloud:true,mcpTokenFile:await f.mcpTokenFile(),once:true}));
 const run=()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.resolve('scripts/codex-worker.cjs'),config],{stdio:'ignore'});child.once('error',reject);child.once('close',code=>code===0?resolve():reject(Error('Worker exit '+code)));});
 const form=new FormData();form.set('file',new Blob(['Complete source input']),'source.txt');const input=await f.api(`/api/boards/${p.project.id}/files`,{method:'POST',body:form});const inputDir=path.join(f.root,'projects',p.project.uuid,'.boardly','inputs',j.id);fs.mkdirSync(inputDir,{recursive:true});fs.writeFileSync(path.join(inputDir,`${input.id}-source.txt`),'Interrupted download');
 await run();let history=await f.api(`/api/chat/threads/${t.id}`);assert.equal(history.job.status,'blocked');assert.equal(history.job.continuation_count,2);assert.equal(history.job.worker_host,'cloud');assert.ok(history.job.blocker_card_id);assert.equal(history.job.next_action,'Connect the test server, then resume work.');
 const board=await f.api(`/api/boards/${p.project.id}`);assert.ok(board.lists.find(l=>l.name==='Blocked').cards.some(c=>c.id===history.job.blocker_card_id));
 await f.api(`/api/chat/jobs/${j.id}/resume`,{method:'POST',body:{content:'Dependency restored. Finish the assignment.'}});await run();history=await f.api(`/api/chat/threads/${t.id}`);assert.equal(history.job.id,j.id);assert.equal(history.job.status,'completed');assert.equal(history.job.draft,'Verified all three stages.');const after=await f.api(`/api/boards/${p.project.id}`);assert.ok(after.lists.find(l=>l.name==='Done Awaiting Revisions').cards.some(c=>c.id===history.job.blocker_card_id));
 const recovery=await f.api(`/api/chat/threads/${t.id}/messages`,{method:'POST',body:{mode:'work',content:'Recover this saved assignment after a worker restart.'}});assert.equal((await w('/api/worker/claim',{cloud:true})).job.id,recovery.id);await w('/api/worker/reconnect',{recover:true});const resumed=(await w('/api/worker/claim',{cloud:true})).job;assert.equal(resumed.id,recovery.id);assert.equal(resumed.recovery_required,1);const upload=async()=>{const body=new FormData();body.set('file',new Blob(['Recovered output contents']),'recovered.txt');const r=await fetch(f.base+`/api/worker/jobs/${recovery.id}/outputs`,{method:'POST',headers:{authorization:'Bearer '+key.token},body});assert.ok(r.ok);return r.json();};assert.equal((await upload()).id,(await upload()).id,'Recovery must not duplicate an already uploaded output');await f.api(`/api/chat/jobs/${recovery.id}/cancel`,{method:'POST',body:{}});await w('/api/worker/reconnect',{recover:true});assert.equal((await w('/api/worker/claim',{cloud:true})).job,null,'User cancellation must not resume');
 console.log('PASS: cloud worker continues multiple sessions, persists a real blocker/task/next action, resumes the same assignment with user clarification, completes the blocker task, recovers interrupted ownership and respects user cancellation');
}finally{await f.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
