const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process'),{fixture}=require('./member-fixture');
(async()=>{
 const desktop_id=crypto.randomUUID(),token='cu_fixture_private_key_123456',seen=[];let worker;
 const f=await fixture({computeruseOrigin:'https://api.computeruse.example',computeruseRequest:async()=>({id:'account-one',rentals:[],desktops:[{id:desktop_id,kind:'pilot',state:'active',available:true,memory_mib:6144,label:'8 GB'}]}),computeruseDesktopRequest:async(o,k,c,d)=>{assert.equal(k,token);seen.push(c);if(c==='lease')return{lease:'private-lease',expires:Math.floor(Date.now()/1000)+60};if(c==='screenshot')return{image_url:'data:image/jpeg;base64,/9j/2Q=='};return{state:'completed',mode:'agent'};}});
 try{
  const p=await f.project('Worker desktop','Native');await f.api('/api/account/computeruse',{method:'PUT',body:{token}});await f.api(`/api/projects/${p.project.id}/computeruse`,{method:'PUT',body:{rental_ids:['desktop:'+desktop_id],allow_agent:true,allow_control:true}});
  const t=await f.api(`/api/boards/${p.project.id}/chat/threads`,{method:'POST',body:{}});await f.api(`/api/chat/threads/${t.id}/messages`,{method:'POST',body:{mode:'work',content:'Verify assigned computer.'}});
  const key=await f.api('/api/connections',{method:'POST',body:{name:'Native computer fixture',scope:'worker'}}),fake=path.join(f.root,'fake-codex.cjs');
  fs.writeFileSync(fake,`#!${process.execPath}\nconst fs=require('node:fs'),assert=require('node:assert/strict');let prompt='';process.stdin.on('data',b=>prompt+=b);process.stdin.on('end',async()=>{try{assert.ok(process.env.BOARDLY_COMPUTER_SOCKET);assert.ok(prompt.includes('Assigned ComputerUse desktops'));const c=require(${JSON.stringify(path.resolve('scripts/project-computeruse-client.cjs'))}),desktop_id=${JSON.stringify(desktop_id)};assert.equal((await c.list()).rentals[0].desktop_id,desktop_id);assert.equal((await c.status({desktop_id})).mode,'agent');const shot=await c.screenshot({desktop_id});assert.equal(fs.readFileSync(shot.path)[0],255);assert.equal(fs.statSync(shot.path).mode&511,384);await c.action({desktop_id,action:{type:'move',x:10,y:10}});await c.release({desktop_id});assert.ok(!prompt.includes(${JSON.stringify(token)}));assert.ok(!prompt.includes('private-lease'));fs.writeFileSync(process.argv[process.argv.indexOf('-o')+1],'Verified computer use.');}catch(e){console.error(e.message);process.exitCode=1;}});`,{mode:0o700});
  const settings=path.join(f.root,'worker.json');fs.writeFileSync(settings,JSON.stringify({origin:f.base,token:key.token,workspaceRoot:path.join(f.root,'workspaces'),codexCommand:fake,once:true,cloud:true,mcpTokenFile:await f.mcpTokenFile(),maxAgents:1}),{mode:0o600});
  worker=spawn(process.execPath,[path.resolve('scripts/codex-worker.cjs'),settings],{stdio:['ignore','pipe','pipe']});let log='';worker.stdout.on('data',b=>log+=b);worker.stderr.on('data',b=>log+=b);
  const code=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{worker.kill('SIGTERM');reject(Error('Computer worker timed out'));},20000);worker.once('exit',c=>{clearTimeout(timer);resolve(c);});});assert.equal(code,0,log);
  const h=await f.api(`/api/chat/threads/${t.id}`);assert.equal(h.job.status,'completed',h.job.error);assert.ok(seen.includes('action'));assert.ok(seen.includes('release'));assert.ok(!log.includes(token));assert.ok(!JSON.stringify(h).includes('/9j/2Q=='));
  const r=await fetch(f.base+`/api/worker/jobs/${h.job.id}/computeruse/status`,{method:'POST',headers:{authorization:'Bearer '+key.token,'content-type':'application/json'},body:JSON.stringify({desktop_id})});assert.equal(r.status,404);
  console.log('PASS: actual Codex worker process, private desktop broker, image file delivery, input/release, no credential leakage and completed-job access denied');
 }finally{if(worker&&worker.exitCode===null)worker.kill('SIGTERM');await f.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
