const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{spawn}=require('node:child_process');
const {fixture}=require('./member-fixture'),{githubFixture}=require('./github-connections');
async function native(){
 const remote=githubFixture(),secret='github_pat_fixture_'+crypto.randomBytes(24).toString('hex'),f=await fixture({githubRequest:remote.request});let worker;
 try{
  const p=await f.project('Native repository','Source work'),connection=await f.api('/api/projects/'+p.project.id+'/github',{method:'PUT',body:{repository:'northstar/website',branch:'main',token:secret,allow_agent:true}});
  const t=await f.api('/api/boards/'+p.project.id+'/chat/threads',{method:'POST',body:{}});await f.api('/api/chat/threads/'+t.id+'/messages',{method:'POST',body:{mode:'work',content:'Verify the connected source workflow.'}});
  const key=await f.api('/api/connections',{method:'POST',body:{name:'Native GitHub QA',scope:'worker'}});
  const fake=path.join(f.root,'fake-codex.cjs');fs.writeFileSync(fake,`#!${process.execPath}\nconst fs=require('node:fs'),assert=require('node:assert/strict');let prompt='';process.stdin.on('data',b=>prompt+=b);process.stdin.on('end',async()=>{try{assert.ok(prompt.includes('Current remote state:'));assert.ok(process.env.BOARDLY_GITHUB_SOCKET);const github=require(${JSON.stringify(path.resolve('scripts/project-github-client.cjs'))});const connection_id=${JSON.stringify(connection.id)},status=await github.status({connection_id});const file=await github.readFile({connection_id,sha:status.sha,path:'src/app.js'});assert.equal(Buffer.from(file.content,'base64').toString(),'original source\\n');const pushed=await github.commitFiles({connection_id,base_sha:status.sha,message:'Native worker verified source',files:[{path:'src/app.js',content:'Native workflow verified\\n',mode:'100644'}]});assert.ok((await github.verifyDeployment({connection_id,sha:pushed.sha})).ready);const answer='Verified GitHub source read, committed changes and checked the release SHA.';const output=process.argv[process.argv.indexOf('-o')+1];fs.writeFileSync(output,answer);console.log(JSON.stringify({type:'thread.started',thread_id:'fixture-github-session'}));console.log(JSON.stringify({type:'item.completed',item:{type:'agent_message',text:answer}}));}catch(e){console.error(e.message);process.exitCode=1;}});`,{mode:0o700});
  const settings=path.join(f.root,'worker.json');fs.writeFileSync(settings,JSON.stringify({origin:f.base,token:key.token,workspaceRoot:path.join(f.root,'workspaces'),codexCommand:fake,once:true,cloud:true,maxAgents:1}),{mode:0o600});
  worker=spawn(process.execPath,[path.resolve('scripts/codex-worker.cjs'),settings],{stdio:['ignore','pipe','pipe']});let log='';worker.stdout.on('data',b=>log+=b);worker.stderr.on('data',b=>log+=b);
  const code=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{worker.kill('SIGTERM');reject(Error('Native GitHub fixture timed out'));},20000);worker.once('exit',code=>{clearTimeout(timer);resolve(code);});});assert.equal(code,0,log);
  const history=await f.api('/api/chat/threads/'+t.id);assert.equal(history.job.status,'completed',history.job.error);assert.ok(!JSON.stringify(history).includes(secret));assert.ok(!log.includes(secret));assert.ok(remote.calls.some(c=>c.method==='PATCH'));assert.ok(history.job.activity.some(a=>a.title==='GitHub repository ready'));
  console.log('PASS: actual cloud worker process prepares GitHub, provides a secret-free broker, pushes source and verifies the release commit');
 }finally{if(worker&&worker.exitCode===null)worker.kill('SIGTERM');await f.close();}
}
async function preparationFailure({status,message,source='scoped',inherited=false}){
 const remote=githubFixture(),secret='github_pat_fixture_'+crypto.randomBytes(24).toString('hex');let unavailable=true,worker;
 const f=await fixture({githubRequest:async(...args)=>{if(unavailable)throw Object.assign(Error(message),{status});return remote.request(...args);}});
 try{
  const p=await f.project('Preparation company','Saved assignment');
  if(source==='account')await f.api('/api/account/github',{method:'PUT',body:{token:secret}});
  await f.api(`/api/${inherited?'companies':'projects'}/${inherited?p.company.id:p.project.id}/github`,{method:'PUT',body:{repository:'northstar/website',branch:'main',credential_source:source,...(source==='scoped'?{token:secret}:{}),allow_agent:true}});
  const t=await f.api(`/api/boards/${p.project.id}/chat/threads`,{method:'POST',body:{}}),job=await f.api(`/api/chat/threads/${t.id}/messages`,{method:'POST',body:{mode:'work',content:'Continue my saved assignment after checking the repository.'}});
  const key=await f.api('/api/connections',{method:'POST',body:{name:'Preparation recovery fixture',scope:'worker'}}),marker=path.join(f.root,'codex-started'),fake=path.join(f.root,'fake-codex.cjs');
  fs.writeFileSync(fake,`#!${process.execPath}\nconst fs=require('node:fs');let prompt='';process.stdin.on('data',b=>prompt+=b);process.stdin.on('end',()=>{fs.writeFileSync(${JSON.stringify(marker)},'started');if(!prompt.includes('Latest user clarification: Repository access repaired'))process.exit(3);fs.writeFileSync(process.argv[process.argv.indexOf('-o')+1],'Saved assignment resumed successfully.');});`,{mode:0o700});
  const settings=path.join(f.root,'worker.json');fs.writeFileSync(settings,JSON.stringify({origin:f.base,token:key.token,workspaceRoot:path.join(f.root,'workspaces'),codexCommand:fake,once:true,cloud:true,maxAgents:1}),{mode:0o600});
  async function run(){worker=spawn(process.execPath,[path.resolve('scripts/codex-worker.cjs'),settings],{stdio:['ignore','pipe','pipe']});let log='';worker.stdout.on('data',b=>log+=b);worker.stderr.on('data',b=>log+=b);const code=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{worker.kill('SIGTERM');reject(Error('Preparation fixture timed out'));},20000);worker.once('exit',c=>{clearTimeout(timer);resolve(c);});});assert.equal(code,0,log);assert.ok(!log.includes(secret));}
  await run();let history=await f.api(`/api/chat/threads/${t.id}`);
  assert.equal(history.job.id,job.id);assert.equal(history.job.status,'blocked');assert.equal(history.job.blocker,message);assert.match(history.job.draft,/northstar\/website \(main\).*No AI work started/);assert.match(history.job.next_action,new RegExp(inherited?'Company → GitHub':'Project → GitHub'));if(source==='account'&&status===403)assert.match(history.job.next_action,/Account & AI → GitHub/);assert.doesNotMatch(history.job.next_action,/AI sign-in|agent runtime/);assert.ok(history.job.activity.some(a=>a.title==='GitHub connection needs attention'&&a.status==='failed'&&a.detail===message));assert.equal(fs.existsSync(marker),false);assert.ok(!JSON.stringify(history).includes(secret));
  unavailable=false;await f.api(`/api/chat/jobs/${job.id}/resume`,{method:'POST',body:{content:'Repository access repaired'}});await run();history=await f.api(`/api/chat/threads/${t.id}`);assert.equal(history.job.id,job.id);assert.equal(history.job.status,'completed',history.job.error);assert.equal(fs.readFileSync(marker,'utf8'),'started');assert.equal(history.messages.filter(m=>m.role==='assistant'&&m.content==='Saved assignment resumed successfully.').length,1);
  console.log(`PASS: GitHub ${status} ${source} ${inherited?'company':'project'} failure records the cause and settings location, starts no AI work and resumes the same assignment after repair`);
 }finally{if(worker&&worker.exitCode===null)worker.kill('SIGTERM');await f.close();}
}
async function hosted(){
 const remote=githubFixture(),secret='github_pat_fixture_'+crypto.randomBytes(24).toString('hex');let calls=0;
 const f=await fixture({githubRequest:remote.request,providerRequest:async(url,opts)=>{if(url.includes('/models/'))return Response.json({id:'gpt-6-astra'});const body=JSON.parse(opts.body);assert.ok(!JSON.stringify(body).includes(secret));assert.ok(body.tools.some(t=>t.name==='github_deploy'));const actions=[['github_status',{}],['github_read_file',{sha:remote.head,path:'src/app.js',start_line:1,max_lines:20}],['github_commit_files',{base_sha:remote.head,message:'Hosted agent source update',files:[{path:'src/app.js',content:'Hosted workflow verified\n',encoding:'utf-8',mode:'100644'}]}],['github_verify_deployment',{sha:remote.head}]];const next=actions[calls++];return Response.json({id:'resp_'+crypto.randomUUID(),model:'gpt-6-astra',status:'completed',service_tier:'default',usage:{input_tokens:100,input_tokens_details:{cached_tokens:0},output_tokens:50},output:next?[{type:'function_call',id:'fc_'+calls,call_id:'call_'+calls,name:next[0],arguments:JSON.stringify(next[1])}]:[{type:'message',role:'assistant',content:[{type:'output_text',text:'Source pushed and release commit verified.'}]}]});}});
 try{
  const p=await f.project('Hosted repository','Source work');await f.api('/api/projects/'+p.project.id+'/github',{method:'PUT',body:{repository:'northstar/website',branch:'main',token:secret,allow_agent:true}});
  await f.api('/api/ai/settings',{method:'PUT',body:{mode:'key',model:'gpt-6-astra',monthly_cap:100,api_key:'sk-fixture_'+crypto.randomBytes(24).toString('hex')}});
  const t=await f.api('/api/boards/'+p.project.id+'/chat/threads',{method:'POST',body:{}});await f.api('/api/chat/threads/'+t.id+'/messages',{method:'POST',body:{mode:'work',content:'Verify the hosted repository workflow.'}});
  let history;for(let i=0;i<100;i++){history=await f.api('/api/chat/threads/'+t.id);if(['completed','failed','blocked'].includes(history.job.status))break;await new Promise(r=>setTimeout(r,20));}
  assert.equal(history.job.status,'completed',history.job.error||history.job.blocker);assert.equal(calls,5);assert.ok(remote.calls.some(c=>c.method==='PATCH'));assert.ok(!JSON.stringify(history).includes(secret));
  console.log('PASS: hosted API agent prepares repository, reads source, commits/pushes and verifies deployment through scoped tools without exposing the token');
 }finally{await f.close();}
}
(async()=>{await native();await hosted();await preparationFailure({status:403,message:'GitHub rejected this token. Replace it with a valid token.'});await preparationFailure({status:403,message:'GitHub denied access. Check token permissions, organization approval and rate limits.',source:'account',inherited:true});await preparationFailure({status:404,message:'GitHub repository, branch or file was not found, or the token cannot access it.'});await preparationFailure({status:502,message:'GitHub could not be reached. Check the repository state before retrying a write.'});})().catch(e=>{console.error(e);process.exitCode=1;});
