const crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const assert=require('node:assert/strict');
const {createCloudApp}=require('../server/cloud');
async function fixture({publicAccess=false,providerRequest,billing,openaiApiKey,tailnet,githubRequest,audio,chatgpt,computeruseOrigin,computeruseRequest,computeruseDesktopRequest,onepasswordClient}={}){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'boardly-members-')),keys=crypto.generateKeyPairSync('rsa',{modulusLength:2048});
 const config={dataDir:root,origin:'https://boardly.example.com',ownerId:'user_owner',ownerOnly:!publicAccess,freeEnabled:true,planSlugs:[],publishableKey:'pk_test_'+Buffer.from('boardly-test.clerk.accounts.dev$').toString('base64'),secretKey:'sk_test_fake',jwtKey:keys.publicKey.export({type:'spki',format:'pem'}),billing,openaiApiKey,tailnet,audio,chatgpt,computeruseOrigin};
 const users=[{id:'user_owner',emailAddresses:[{emailAddress:'owner@example.com',verification:{status:'verified'}}]}];
 const identity={users:{async getUserList({emailAddress}){return{data:users.filter(u=>u.emailAddresses.some(e=>emailAddress.includes(e.emailAddress)))};},async createUser(data){assert.deepEqual(data.emailAddressIdentificationStatus,['reserved']);const u={id:'user_member'+users.length,emailAddresses:[{emailAddress:data.emailAddress[0],verification:{status:'unverified'}}]};users.push(u);return u;}},billing:{async getUserBillingSubscription(){throw Object.assign(Error('No subscription'),{status:404});}}};
 const app=createCloudApp(config,{identityClient:identity,providerRequest,githubRequest,computeruseRequest,computeruseDesktopRequest,onepasswordClient}),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 function token(user){const now=Math.floor(Date.now()/1000),h=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT',kid:'test'})).toString('base64url'),c=Buffer.from(JSON.stringify({iss:'https://boardly-test.clerk.accounts.dev',sub:user,sid:'sess_test',iat:now,nbf:now-10,exp:now+7200,azp:config.origin,v:2,fva:[0,-1]})).toString('base64url');return h+'.'+c+'.'+crypto.sign('RSA-SHA256',Buffer.from(h+'.'+c),keys.privateKey).toString('base64url');}
 const request=(route,{user='user_owner',workspace,method='GET',body}={})=>fetch(base+route,{method,headers:{authorization:'Bearer '+token(user),...(workspace?{'x-boardly-workspace':workspace}:{}),...(body instanceof FormData?{}:{'content-type':'application/json'})},body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body)});
 async function api(route,options){const r=await request(route,options),d=await r.json();assert.ok(r.ok,`${route}: ${r.status} ${JSON.stringify(d)}`);return d;}
 async function project(companyName='Company',projectName='Project',user='user_owner'){const company=await api('/api/companies',{user,method:'POST',body:{name:companyName}}),board=await api('/api/company-boards',{user,method:'POST',body:{name:'Board',company_id:company.id}}),project=await api('/api/projects',{user,method:'POST',body:{name:projectName,parent_board_id:board.id}}),full=await api('/api/boards/'+project.id,{user});return{company,board,project,list:full.lists[0]};}
 return{root,config,app,server,base,users,identity,token,request,api,project,async close(){await new Promise(r=>server.close(r));app.closeWorkspaces();fs.rmSync(root,{recursive:true,force:true});}};
}
module.exports={fixture};
