const assert=require('node:assert/strict'),path=require('node:path'),crypto=require('node:crypto');
const {fixture}=require('./member-fixture');
const {chromium}=require('/home/ben/.npm/_npx/e41f203b7505f1fb/node_modules/playwright');
const key='sk-browser_fixture_'+crypto.randomBytes(24).toString('hex');
let f,vite,browser;
(async()=>{
 f=await fixture({providerRequest:async(url,opts)=>{assert.ok(url.includes('/models/'));assert.equal(opts.headers.Authorization,'Bearer '+key);return Response.json({id:'gpt-6-astra'});}});
 const a=await f.project('QA Shared Company','QA Project'),b=await f.project('QA Private Company','QA Private');
 await f.api(`/api/lists/${a.list.id}/cards`,{method:'POST',body:{title:'A shared task',description:'Only shared project members can read this.'}});
 const repo=path.resolve(__dirname,'..'),{createServer}=await import('vite'),react=(await import('@vitejs/plugin-react')).default,tailwind=(await import('@tailwindcss/vite')).default;
 vite=await createServer({configFile:false,root:repo+'/client',plugins:[react(),tailwind(),{
  name:'membership-qa',resolveId(id){if(id==='/qa-entry.jsx')return '\0member-qa';},load(id){if(id==='\0member-qa')return `import React from 'react';import {createRoot} from 'react-dom/client';import {Workspace} from '/src/App.jsx';import {api,setTokenProvider,setWorkspaceId} from '/src/api.js';import '/src/index.css';const user=new URLSearchParams(location.search).get('user')||'user_owner';const tokens=${JSON.stringify(Object.fromEntries(['user_owner','user_member1'].map(u=>[u,f.token(u)])))};setTokenProvider(async()=>tokens[user]);api.get('/api/me').then(access=>{setWorkspaceId(access.workspaceId);createRoot(document.getElementById('root')).render(React.createElement(Workspace,{cloud:true,access,onLogout:()=>{}}));});`;},configureServer(s){s.middlewares.use('/qa',async(q,r)=>{r.setHeader('content-type','text/html');r.end(await s.transformIndexHtml('/qa','<html class="dark"><head></head><body class="bg-zinc-950 text-zinc-100"><div id="root"></div><script type="module" src="/qa-entry.jsx"></script></body></html>'));});}
 }],server:{host:'127.0.0.1',port:0,proxy:{'/api':{target:f.base,configure:p=>p.on('proxyReq',q=>q.setHeader('origin',f.config.origin))},'/uploads':f.base}}});await vite.listen();const url=vite.resolvedUrls.local[0]+'qa';
 browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});const errors=[];
 const owner=await browser.newPage({viewport:{width:1440,height:1000}});owner.on('pageerror',e=>errors.push(e.message));await owner.goto(url+`#/board/${a.project.id}`);
 await owner.getByRole('button',{name:'Members',exact:true}).click();await owner.getByLabel('Member email',{exact:true}).fill('browser@example.com');await owner.getByRole('button',{name:'Add user',exact:true}).click();await owner.getByText('browser@example.com',{exact:true}).waitFor();
 await owner.screenshot({path:'/home/ben/.local/share/boardly-ops/qa-project-members.png'});
 await owner.getByLabel('Close members').click();await owner.getByRole('button',{name:'Account & AI',exact:true}).click();await owner.getByRole('heading',{name:'Your account · Owner'}).waitFor();assert.ok((await owner.getByRole('dialog',{name:'Account and AI settings'}).innerText()).includes('Unlimited'));
 await owner.getByLabel('AI payment method').selectOption('key');await owner.getByLabel('OpenAI API key',{exact:true}).fill(key);await owner.getByRole('button',{name:'Save AI settings',exact:true}).click();await owner.getByText('Your AI settings were saved.',{exact:true}).waitFor();assert.equal(await owner.getByLabel('OpenAI API key',{exact:true}).inputValue(),'');await owner.screenshot({path:'/home/ben/.local/share/boardly-ops/qa-account-ai.png'});await owner.getByLabel('Close account settings').click();
 const member=await browser.newPage({viewport:{width:1280,height:1000}});member.on('pageerror',e=>errors.push(e.message));await member.goto(url+'?user=user_member1');await member.getByRole('button',{name:/QA Shared Company/}).waitFor();assert.equal(await member.getByRole('button',{name:/QA Private Company/}).count(),0);assert.equal(await member.getByRole('button',{name:'New company',exact:true}).isVisible(),false);assert.equal(await member.getByRole('button',{name:'Import board',exact:true}).isVisible(),false);
 await member.goto(url+`?user=user_member1#/board/${a.project.id}`);await member.getByText('A shared task',{exact:true}).waitFor();assert.equal(await member.getByRole('button',{name:'Environment',exact:true}).count(),0);assert.equal(await member.getByRole('button',{name:'Payments',exact:true}).count(),0);assert.equal(await member.getByRole('button',{name:'Members',exact:true}).count(),0);assert.equal(await member.getByLabel('Project name',{exact:true}).getAttribute('readonly'),'');
 await member.getByRole('button',{name:'Chat with AI',exact:true}).click();await member.getByText('Company owner funds AI usage',{exact:false}).waitFor();assert.equal(await member.getByRole('button',{name:'AI settings',exact:true}).count(),0);assert.ok(!(await member.locator('body').innerText()).includes(key));await member.getByLabel('Close project chat').click();
 const grants=await f.api(`/api/projects/${a.project.id}/members`);await f.api(`/api/memberships/${grants.members[0].grant_id}`,{method:'PATCH',body:{role:'viewer'}});await member.reload();await member.getByText('View-only access',{exact:true}).waitFor();await member.getByText('A shared task',{exact:true}).click();assert.equal(await member.locator('fieldset').getAttribute('disabled'),'');assert.equal(await member.getByRole('button',{name:'Labels',exact:true}).isDisabled(),true);await member.screenshot({path:'/home/ben/.local/share/boardly-ops/qa-viewer-task.png'});
 assert.deepEqual(errors,[]);console.log('PASS: browser member creation, unlimited owner account, shared navigation, hidden private controls, owner-key save/redaction, owner-funded member AI readiness and viewer task controls');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(vite)await vite.close();if(f)await f.close();});
