const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const {fixture}=require('./member-fixture'),{inspectOutput,createOutputUploader}=require('../scripts/output-upload.cjs');
(async()=>{const f=await fixture();try{
 const a=await f.project('Output worker','Saved videos'),card=await f.api(`/api/lists/${a.list.id}/cards`,{method:'POST',body:{title:'Deliver files'}}),thread=await f.api(`/api/boards/${a.project.id}/chat/threads`,{method:'POST',body:{card_id:card.id}}),job=await f.api(`/api/chat/threads/${thread.id}/messages`,{method:'POST',body:{mode:'work',content:'Save the generated archive and verify its file ID before finishing.'}}),worker=await f.api('/api/connections',{method:'POST',body:{name:'Cloud agent upload fixture',scope:'worker'}});
 const raw=async(route,body)=>{const binary=Buffer.isBuffer(body),r=await fetch(f.base+route,{method:'POST',headers:{authorization:'Bearer '+worker.token,'content-type':binary?'application/octet-stream':'application/json'},body:binary?body:JSON.stringify(body||{})});if(!r.ok)throw Object.assign(Error((await r.json()).error),{status:r.status});return r;};
 const api=async(route,body)=>(await raw(route,body)).json();await api('/api/worker/claim',{cloud:true});
 const outputDir=path.join(f.root,'output-fixture');fs.mkdirSync(outputDir);const binary=Buffer.concat([Buffer.from('PK\x03\x04\x00archive with digits 4111111111111111 '),Buffer.alloc(6*1024*1024,19)]);fs.writeFileSync(path.join(outputDir,'archive.zip'),binary);
 let droppedChunk=false,droppedFinal=false;
 const uploader=createOutputUploader({outputDir,jobId:job.id,request:async(route,body)=>{const r=await raw(route,body);if(route.includes('/chunks')&&!droppedChunk){droppedChunk=true;throw Error('Lost chunk acknowledgement');}return r;},api:async(route,body)=>{const r=await api(route,body);if(route.endsWith('/complete')&&!droppedFinal){droppedFinal=true;throw Error('Lost completion acknowledgement');}return r;}});
 const file=await uploader.upload('archive.zip');assert.ok(droppedChunk&&droppedFinal);assert.equal(file.sha256,crypto.createHash('sha256').update(binary).digest('hex'));assert.equal((await uploader.upload('archive.zip')).id,file.id);assert.equal((await f.api(`/api/cards/${card.id}/files`)).files.length,1);
 fs.symlinkSync(path.join(outputDir,'archive.zip'),path.join(outputDir,'linked.zip'));await assert.rejects(()=>uploader.upload('linked.zip'));
 const secret='project-value-'+crypto.randomUUID(),secretFile=path.join(outputDir,'private.bin'),payload=Buffer.concat([Buffer.alloc(1024*1024-5),Buffer.from(secret),Buffer.alloc(20)]);fs.writeFileSync(secretFile,payload);const h=await fs.promises.open(secretFile,'r');try{await assert.rejects(()=>inspectOutput(h,{privateValue:secret}),/private project value/);}finally{await h.close();}
 await api(`/api/worker/jobs/${job.id}`,{status:'completed',text:'File upload verified'});
 // Drive an actual worker turn. The fake model uses the same file helper that
 // real Work runs receive and waits for the saved ID before returning success.
 const next=await f.api(`/api/chat/threads/${thread.id}/messages`,{method:'POST',body:{mode:'work',content:'Deliver another binary output'}}),fake=path.join(f.root,'upload-codex.cjs'),client=path.resolve('scripts/project-file-client.cjs');
 fs.writeFileSync(fake,`#!/usr/bin/env node\nconst fs=require('fs'),path=require('path');let prompt='';process.stdin.on('data',b=>prompt+=b);process.stdin.on('end',async()=>{try{if(!prompt.includes('without a per-file size cap'))throw Error('Missing upload instruction');const dir=path.join('.boardly','outputs',${JSON.stringify(next.id)});fs.writeFileSync(path.join(dir,'during-run.zip'),Buffer.concat([Buffer.from('PK\\x03\\x04\\x00 4111111111111111'),Buffer.alloc(3*1024*1024)]));const file=await require(${JSON.stringify(client)}).upload({name:'during-run.zip'});if(!file.id||file.size<3*1024*1024)throw Error('File not saved');fs.writeFileSync('verified-file-id.txt',String(file.id));console.log(JSON.stringify({type:'thread.started',thread_id:'session-file-delivery'}));fs.writeFileSync(process.argv[process.argv.indexOf('-o')+1],JSON.stringify({state:'completed',summary:'Output uploaded and verified during the run.',next_step:'',blocker:'',next_action:''}));}catch(e){fs.writeFileSync('upload-fixture-error.txt',e.stack);console.error(e.message);process.exitCode=1;}});`,{mode:0o700});
 const syntax=require('child_process').spawnSync(process.execPath,['--check',fake],{encoding:'utf8'});assert.equal(syntax.status,0,syntax.stderr);
 const config=path.join(f.root,'worker.json');fs.writeFileSync(config,JSON.stringify({origin:f.base,token:worker.token,workspaceRoot:path.join(f.root,'projects'),codexCommand:fake,continuous:true,cloud:true,mcpTokenFile:await f.mcpTokenFile(),once:true}));
 await new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.resolve('scripts/codex-worker.cjs'),config],{stdio:['ignore','ignore','pipe']});let error='';child.stderr.on('data',b=>error+=b);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(Error(error||'Worker failed')));});
 const history=await f.api(`/api/chat/threads/${thread.id}`);assert.equal(history.job.status,'completed',(fs.existsSync(path.join(f.root,'projects',a.project.uuid,'upload-fixture-error.txt'))?fs.readFileSync(path.join(f.root,'projects',a.project.uuid,'upload-fixture-error.txt'),'utf8'):'')+JSON.stringify(history.job));assert.equal(history.job.draft,'Output uploaded and verified during the run.');const files=(await f.api(`/api/boards/${a.project.id}/files`)).files;assert.equal(files.filter(x=>x.name==='during-run.zip').length,1,'Automatic post-run save reuses the in-run upload');assert.equal(Number(fs.readFileSync(path.join(f.root,'projects',a.project.uuid,'verified-file-id.txt'),'utf8')),files.find(x=>x.name==='during-run.zip').id);
 console.log('PASS: binary archive card-number false positive fixed, known secrets across chunk boundaries rejected, symlinks denied, lost chunk/final acknowledgements recover without duplicates, actual worker uploads and verifies during its run, automatic post-run upload deduplicates');
}finally{await f.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
