const assert=require('node:assert/strict'),crypto=require('node:crypto'),net=require('node:net'),path=require('node:path');
const {Server,utils}=require('ssh2'),{fixture}=require('./member-fixture'),{createSshConnections}=require('../server/ssh-connections'),{workspacePath}=require('../server/cloud'),{loadKey}=require('../server/project-environment');
(async()=>{const f=await fixture({publicAccess:true});let server,db;try{
 const key=crypto.generateKeyPairSync('rsa',{modulusLength:2048}).privateKey.export({type:'pkcs1',format:'pem'}),fingerprint='SHA256:'+crypto.createHash('sha256').update(utils.parseKey(key).getPublicSSH()).digest('base64').replace(/=+$/,''),password='owner-ssh-fixture-'+crypto.randomUUID();let commands=0,forwards=0;
 server=new Server({hostKeys:[key]},client=>{client.on('error',()=>{});client.on('authentication',c=>c.method==='password'&&c.password===password?c.accept():c.reject());client.on('ready',()=>{client.on('tcpip',(accept,reject,info)=>{forwards++;const remote=net.connect(info.destPort,info.destIP,()=>{const stream=accept();stream.on('error',()=>remote.destroy());remote.on('error',()=>stream.destroy());remote.pipe(stream).pipe(remote);});remote.on('error',()=>reject());});client.on('session',accept=>accept().on('exec',accept=>{commands++;const s=accept();s.write('ssh-ok');s.exit(0);s.end();}));});});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const config={host:'127.0.0.1',port:server.address().port,username:'qa',auth_type:'password',password,fingerprint,allow_agent:true};
 const a=await f.project('Company A'),b=await f.project('Company B'),c=await f.project('Private company');
 const jump=await f.api('/api/account/ssh',{method:'POST',body:{...config,label:'Owner jump'}}),target=await f.api('/api/account/ssh',{method:'POST',body:{...config,label:'Owner target',jump_id:jump.id}});
 assert.ok(!JSON.stringify(target).includes(password));assert.equal((await f.api(`/api/companies/${a.company.id}/ssh`)).inherited.length,2);assert.equal((await f.api(`/api/projects/${b.project.id}/ssh`)).inherited.length,2);
 assert.equal((await f.api(`/api/account/ssh/${target.id}/test`,{method:'POST',body:{}})).connected,true);assert.equal(forwards,1);assert.equal(commands,0);
 assert.equal((await f.request(`/api/account/ssh/${jump.id}`,{method:'PATCH',body:{jump_id:target.id}})).status,400,'cycles rejected');
 const member=(await f.api(`/api/companies/${a.company.id}/members`,{method:'POST',body:{email:'ssh@example.com',role:'editor'}})).member.user_id;
 const m={user:member,workspace:'user_owner'},ga=(await f.api(`/api/companies/${a.company.id}/members`)).members[0].grant_id;
 assert.equal((await f.request(`/api/projects/${a.project.id}/ssh`,m)).status,403);
 await f.api(`/api/memberships/${ga}`,{method:'PATCH',body:{owner_ssh:true}});
 assert.equal((await f.api(`/api/projects/${a.project.id}/ssh`,m)).inherited.length,2);
 assert.equal((await f.request(`/api/projects/${c.project.id}/ssh`,m)).status,403);
 await f.api(`/api/projects/${b.project.id}/members`,{method:'POST',body:{email:'ssh@example.com',role:'editor'}});
 assert.equal((await f.api(`/api/projects/${b.project.id}/ssh`,m)).inherited.length,2,'future project grant inherits owner SSH');assert.equal((await f.request(`/api/companies/${b.company.id}/ssh`,m)).status,403,'project guest stays project-only');
 for(const method of ['GET','POST','PATCH','DELETE'])assert.equal((await f.request('/api/account/ssh'+(['PATCH','DELETE'].includes(method)?'/'+target.id:''),{...m,method,...(method==='GET'?{}:{body:{...config,label:'Forbidden'}})})).status,403);
 assert.equal((await f.request(`/api/companies/${a.company.id}/ssh/${target.id}`,{...m,method:'PATCH',body:{allow_agent:false}})).status,404,'scoped delegate cannot mutate owner library');
 assert.equal((await f.request(`/api/memberships/${ga}`,{...m,method:'PATCH',body:{owner_ssh:false}})).status,403);
 assert.equal((await f.request('/api/owner/0/ssh')).status,404);
 const own=await f.api('/api/account/ssh',{user:member});assert.equal(own.connections.length,0,'other owner cannot see library');
 db=new(require('better-sqlite3'))(path.join(workspacePath(f.root,'user_owner'),'app.db'));const ssh=createSshConnections({db,key:loadKey(f.root),namespace:'user_owner'});
 assert.equal(ssh.agentList(c.project.id).length,2);const connection=ssh.forJob(a.project.id,a.company.id,target.id);assert.equal((await ssh.execute(connection,{requireEnabled:true,command:'fixture'})).stdout,'ssh-ok');
 await f.api(`/api/account/ssh/${jump.id}`,{method:'PATCH',body:{allow_agent:false}});assert.throws(()=>ssh.forJob(a.project.id,a.company.id,target.id),/disabled/);
 await f.api(`/api/account/ssh/${jump.id}`,{method:'PATCH',body:{allow_agent:true,password:''}});assert.equal((await f.api(`/api/account/ssh/${jump.id}/test`,{method:'POST',body:{}})).connected,true,'blank credential preserves saved password');
 await f.api(`/api/memberships/${ga}`,{method:'PATCH',body:{owner_ssh:false}});assert.equal((await f.request(`/api/projects/${b.project.id}/ssh`,m)).status,403);
 const pending=await f.api('/api/account/ssh',{method:'POST',body:{...config,label:'Pending trust',fingerprint:'',allow_agent:false}});assert.equal((await f.request(`/api/account/ssh/${pending.id}`,{method:'PATCH',body:{allow_agent:true}})).status,400);assert.equal((await f.request(`/api/account/ssh/${pending.id}/test`,{method:'POST',body:{}})).status,400);
 const networkSsh=createSshConnections({db,key:loadKey(f.root),namespace:'user_owner',tailnet:{dial:async()=>net.connect(config.port,'127.0.0.1')}});
 const networkJump=networkSsh.save('owner',0,{...config,label:'Network jump'},undefined,{account:'user_owner',device:'fixture'}),networkTarget=networkSsh.save('owner',0,{...config,label:'Network target',jump_id:networkJump.id});
 assert.equal((await networkSsh.execute(networkSsh.forJob(a.project.id,a.company.id,networkTarget.id),{requireEnabled:true,command:'fixture'})).stdout,'ssh-ok','Tailscale jump transport remains open through destination authentication');
 const encrypted=db.prepare('SELECT encrypted FROM owner_ssh_connections WHERE id=?').get(target.id).encrypted;assert.ok(!encrypted.includes(password));db.close();db=new(require('better-sqlite3'))(path.join(workspacePath(f.root,'user_owner'),'app.db'));assert.equal(createSshConnections({db,key:loadKey(f.root),namespace:'user_owner'}).forJob(a.project.id,a.company.id,target.id).password,password);
 console.log('PASS: encrypted owner library, real pinned jump forwarding, blank credential updates, inheritance, future grants, member/tenant boundaries, cycle rejection, revocation, pending trust and database reopen');
}finally{db?.close();if(server)await new Promise(r=>server.close(r));await f.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
