const assert=require('node:assert/strict'),http=require('node:http'),net=require('node:net'),crypto=require('node:crypto');
const {fixture}=require('./member-fixture'),{createTailnet}=require('../server/tailnet');
(async()=>{const active=new Set(),seen=[],token='fixture-tailnet-token-that-is-long-enough';let f;const echo=net.createServer(socket=>socket.pipe(socket));await new Promise(r=>echo.listen(0,'127.0.0.1',r));
 const id=user=>crypto.createHash('sha256').update(user).digest('hex');
 const server=http.createServer(async(req,res)=>{assert.equal(req.headers.authorization,'Bearer '+token);const [,kind,account,action]=req.url.split('/');seen.push(account);assert.equal(kind,'accounts');if(action==='connect')active.add(account);if(action==='disconnect')active.delete(account);res.setHeader('content-type','application/json');res.end(JSON.stringify({state:active.has(account)?'Running':'disconnected',devices:active.has(account)?[{id:'device-'+account,name:'Private server',dns_name:'server.test.ts.net',addresses:['100.100.0.2'],online:true}]:[]}));});
 server.on('connect',(req,socket,head)=>{assert.equal(req.headers.authorization,'Bearer '+token);const account=req.url.split('/')[2];if(!active.has(account)||req.headers['x-boardly-device']!=='device-'+account){socket.end('HTTP/1.1 403 Forbidden\r\n\r\n');return;}const upstream=net.connect(echo.address().port,'127.0.0.1',()=>{socket.write('HTTP/1.1 200 Connection Established\r\n\r\n');if(head.length)upstream.write(head);socket.pipe(upstream);upstream.pipe(socket);});socket.on('close',()=>upstream.destroy());});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
 try{f=await fixture({publicAccess:true,tailnet:{url,token}});const alice='user_owner',bob='user_bob';await f.api('/api/account/tailscale/connect',{method:'POST',body:{}});await f.api('/api/account/tailscale/connect',{user:bob,method:'POST',body:{}});const a=await f.api('/api/account/tailscale'),b=await f.api('/api/account/tailscale',{user:bob});assert.notEqual(a.devices[0].id,b.devices[0].id);assert.ok(!JSON.stringify(a).includes(id(bob)));assert.ok(!JSON.stringify(a).includes(token));
 const gateway=createTailnet({url,token});await assert.rejects(()=>gateway.device(bob,a.devices[0].id),/not in your Tailscale network/);const socket=await gateway.dial(alice,a.devices[0].id,22);const returned=new Promise(r=>socket.once('data',r));socket.write('tailnet-transport-verification');assert.equal(String(await returned),'tailnet-transport-verification');socket.destroy();
 const p=await f.project('Tailscale company','Server task');const connection=await f.api(`/api/projects/${p.project.id}/ssh`,{method:'POST',body:{label:'Private server',host:'ignored.invalid',port:22,username:'fixture',auth_type:'password',password:'fixture-password',fingerprint:'SHA256:'+'a'.repeat(43),allow_agent:true,tailnet_device_id:a.devices[0].id}});assert.equal(connection.host,'server.test.ts.net');assert.equal(connection.tailnet_device_id,a.devices[0].id);assert.equal(connection.password,undefined);assert.equal(connection.tailnet_account,undefined);
 assert.equal((await f.request(`/api/projects/${p.project.id}/ssh`,{method:'POST',body:{label:'Other network',host:'ignored.invalid',username:'fixture',auth_type:'password',password:'fixture-password',fingerprint:'SHA256:'+'a'.repeat(43),tailnet_device_id:b.devices[0].id}})).status,403);
 await f.api('/api/account/tailscale/disconnect',{method:'POST',body:{}});assert.equal((await f.api('/api/account/tailscale')).state,'disconnected');assert.equal((await f.api('/api/account/tailscale',{user:bob})).state,'Running');await assert.rejects(()=>gateway.dial(alice,a.devices[0].id,22),/Connect your Tailscale account/);
 console.log('PASS: personal account network isolation, private token omission, stable device-scoped transport, inherited SSH metadata, foreign-device denial and independent disconnect');
 }finally{if(f)await f.close();await new Promise(r=>server.close(r));await new Promise(r=>echo.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
