FROM boardly-cloud:access-download-57b18d9
ARG SOURCE_REVISION
LABEL org.opencontainers.image.revision=$SOURCE_REVISION
COPY --chown=node:node server/project-chat.js server/project-employees.js /app/server/
