FROM boardly-cloud:onepassword-45945a8
COPY --chown=node:node server /app/server
COPY --chown=node:node scripts /app/scripts
COPY --chown=node:node docs /app/docs
COPY --chown=node:node dist /app/dist
