const express=require('express'),crypto=require('node:crypto');
const fail=(status,message)=>Object.assign(Error(message),{status});
async function request(provider,token,method,body){
 const url=provider==='telegram'?`https://api.telegram.org/bot${token}/${method}`:'https://discord.com/api/v10/'+method;
 try{
  const r=await fetch(url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(provider==='discord'?{Authorization:'Bot '+token}:{})},body:body?JSON.stringify(body):undefined,redirect:'error',signal:AbortSignal.timeout(15000)});
  if(!r.ok)throw fail(r.status===429?429:400,r.status===429?'The bot is sending too quickly. Wait a minute before trying again.':'The bot could not connect. Check its token, destination and permissions.');
  const parts=[];let n=0;for await(const p of r.body){n+=p.length;if(n>1000000)throw Error('Large response');parts.push(p);}const value=JSON.parse(Buffer.concat(parts));
  if(provider==='telegram'&&value.ok!==true)throw fail(400,'Telegram could not complete this step. Check the bot and destination.');return provider==='telegram'?value.result:value;
 }catch(e){if(e.status)throw e;throw fail(503,'The bot connection was interrupted. If you were sending, check the destination before trying again.');}
}
function createCompanyBots({db,key,namespace,request:call=request}){
 db.exec(`CREATE TABLE IF NOT EXISTS company_bots(company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,provider TEXT NOT NULL,revision TEXT NOT NULL,encrypted TEXT NOT NULL,bot_id TEXT NOT NULL,name TEXT NOT NULL,username TEXT NOT NULL DEFAULT '',destination TEXT,destination_name TEXT,pairing TEXT,pairing_expires INTEGER,verified_at INTEGER NOT NULL,PRIMARY KEY(company_id,provider));
 CREATE TABLE IF NOT EXISTS company_bot_sends(id TEXT PRIMARY KEY,company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,provider TEXT NOT NULL,revision TEXT NOT NULL,body_hash TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL);`);
 db.prepare("UPDATE company_bot_sends SET status='uncertain' WHERE status='sending'").run();
 const row=(company,provider)=>db.prepare('SELECT * FROM company_bots WHERE company_id=? AND provider=?').get(company,provider);
 function company(id){if(!Number.isSafeInteger(id)||!db.prepare('SELECT id FROM companies WHERE id=?').get(id))throw fail(404,'Company not found.');}
 function validProvider(p){if(!['discord','telegram'].includes(p))throw fail(404,'Bot provider not found.');}
 function crypt(value,company,provider,decode=false){const aad=Buffer.from(JSON.stringify(['company-bot-v1',namespace,company,provider]));if(decode){const b=Buffer.from(value,'base64'),c=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAAD(aad);c.setAuthTag(b.subarray(12,28));return Buffer.concat([c.update(b.subarray(28)),c.final()]).toString();}const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);c.setAAD(aad);const b=Buffer.concat([c.update(value),c.final()]);return Buffer.concat([iv,c.getAuthTag(),b]).toString('base64');}
 function state(company,provider){const r=row(company,provider);return{saved:!!r,provider,bot_id:r?.bot_id,name:r?.name,username:r?.username,destination:r?.destination,destination_name:r?.destination_name,verified_at:r?.verified_at,pairing_url:r?.pairing&&r.pairing_expires>Date.now()?`https://t.me/${r.username}?start=${r.pairing}`:null};}
 function connected(c,p){const r=row(c,p);if(!r)throw fail(400,'Connect your bot first.');return r;}
 function current(r){company(r.company_id);if(row(r.company_id,r.provider)?.revision!==r.revision)throw fail(409,'The bot connection changed. Refresh this page.');}
 async function connect(c,p,token){company(c);validProvider(p);if(typeof token!=='string'||token.length<20||token.length>256||!/^[A-Za-z0-9_.:-]+$/.test(token))throw fail(400,'Paste the bot token exactly as shown by '+(p==='discord'?'Discord.':'BotFather.'));
  const previous=row(c,p)?.revision;const bot=await call(p,token,p==='discord'?'users/@me':'getMe');company(c);if(row(c,p)?.revision!==previous)throw fail(409,'The connection changed in another tab. Refresh and try again.');if(!(p==='discord'?bot.bot:bot.is_bot)||!/^\d+$/.test(String(bot.id)))throw fail(400,'Use a bot token, not a personal account token.');
  if(p==='telegram'){const info=await call(p,token,'getWebhookInfo');if(info.url)throw fail(409,'This bot already belongs to another bot service. Create a new bot in BotFather for Boardly.');company(c);if(row(c,p)?.revision!==previous)throw fail(409,'The connection changed. Refresh and try again.');}
  const username=String(bot.username||'');if(p==='telegram'&&!/^\w{5,32}$/.test(username))throw fail(400,'The bot username could not be read.');
  db.prepare('INSERT INTO company_bots(company_id,provider,revision,encrypted,bot_id,name,username,verified_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(company_id,provider) DO UPDATE SET revision=excluded.revision,encrypted=excluded.encrypted,bot_id=excluded.bot_id,name=excluded.name,username=excluded.username,destination=NULL,destination_name=NULL,pairing=NULL,verified_at=excluded.verified_at').run(c,p,crypto.randomUUID(),crypt(token,c,p),String(bot.id),String(bot.first_name||username||'Bot').slice(0,100),username,Date.now());return state(c,p);
 }
 async function destinations(c,p,guild){const r=connected(c,p),token=crypt(r.encrypted,c,p,true);if(p!=='discord')throw fail(400,'Use the Open bot button to choose a Telegram chat.');if(guild&&!/^\d{5,22}$/.test(guild))throw fail(400,'Choose a server.');const values=await call(p,token,guild?`guilds/${guild}/channels`:'users/@me/guilds');current(r);if(!Array.isArray(values))throw fail(502,'Discord did not return the list.');return values.filter(v=>!guild||v.type===0||v.type===5).map(v=>({id:String(v.id),name:String(v.name||'Channel').slice(0,100)}));}
 async function destination(c,p,id){const r=connected(c,p);if(p!=='discord'||typeof id!=='string'||!/^\d{5,22}$/.test(id))throw fail(400,'Choose a Discord channel.');const channel=await call(p,crypt(r.encrypted,c,p,true),'channels/'+id);current(r);if(![0,5].includes(channel.type)||String(channel.id)!==id)throw fail(400,'Choose a server text channel.');db.prepare('UPDATE company_bots SET destination=?,destination_name=?,revision=? WHERE company_id=? AND provider=?').run(id,String(channel.name).slice(0,100),crypto.randomUUID(),c,p);return state(c,p);}
 function pair(c){const r=connected(c,'telegram');db.prepare('UPDATE company_bots SET pairing=?,pairing_expires=?,revision=? WHERE company_id=? AND provider=?').run(crypto.randomBytes(18).toString('hex'),Date.now()+600000,crypto.randomUUID(),c,'telegram');return state(c,'telegram');}
 async function findPair(c){const r=connected(c,'telegram');if(!r.pairing||r.pairing_expires<Date.now())throw fail(400,'Click Open my bot again to get a fresh link.');const updates=await call('telegram',crypt(r.encrypted,c,'telegram',true),'getUpdates',{timeout:0,limit:100,allowed_updates:['message']});current(r);const found=updates.find(u=>u.message?.chat?.type==='private'&&u.message.text==='/start '+r.pairing&&u.message.date*1000>r.pairing_expires-600000);if(!found)throw fail(409,'Open your bot in Telegram and press Start, then click Check again.');const m=found.message;if(!Number.isSafeInteger(m.chat.id))throw fail(502,'Telegram returned an invalid chat.');db.prepare('UPDATE company_bots SET destination=?,destination_name=?,pairing=NULL,revision=? WHERE company_id=? AND provider=?').run(String(m.chat.id),String(m.chat.first_name||'Your Telegram chat').slice(0,100),crypto.randomUUID(),c,'telegram');return state(c,'telegram');}
 function preview(c,projectId){company(c);const p=db.prepare('SELECT p.workspace_id id,p.name FROM company_projects p JOIN company_boards b ON b.id=p.parent_board_id WHERE b.company_id=? AND p.workspace_id=?').get(c,projectId);if(!p)throw fail(404,'Choose a project in this company.');const lists=db.prepare('SELECT l.name,COUNT(c.id) n FROM lists l LEFT JOIN cards c ON c.list_id=l.id AND c.archived=0 WHERE l.board_id=? AND l.archived=0 GROUP BY l.id ORDER BY l.position').all(p.id);return `${p.name}\n${lists.map(l=>`${l.name}: ${l.n} tasks`).join('\n')}`.slice(0,1800);}
 async function send(c,p,requestId,body){if(typeof requestId!=='string'||!/^[-a-zA-Z0-9]{16,80}$/.test(requestId))throw fail(400,'A message identifier is required.');const r=connected(c,p);if(!r.destination)throw fail(400,'Choose a destination first.');const hash=crypto.createHash('sha256').update(body+'\n'+r.destination).digest('hex'),old=db.prepare('SELECT * FROM company_bot_sends WHERE id=?').get(requestId);if(old){if(old.company_id!==c||old.provider!==p||old.body_hash!==hash)throw fail(409,'This message identifier was already used.');return{status:old.status};}
  if(db.prepare('SELECT COUNT(*) n FROM company_bot_sends WHERE company_id=? AND created_at>?').get(c,Date.now()-60000).n>=10)throw fail(429,'Wait a minute before sending more updates.');db.prepare("INSERT INTO company_bot_sends VALUES(?,?,?,?,?,'sending',?)").run(requestId,c,p,r.revision,hash,Date.now());
  try{const result=await call(p,crypt(r.encrypted,c,p,true),p==='discord'?`channels/${r.destination}/messages`:'sendMessage',p==='discord'?{content:body,allowed_mentions:{parse:[]}}:{chat_id:r.destination,text:body});if(!(result.id||result.message_id))throw Error('Missing receipt');db.prepare("UPDATE company_bot_sends SET status='accepted' WHERE id=?").run(requestId);return{status:'accepted'};}catch(e){db.prepare("UPDATE company_bot_sends SET status='uncertain' WHERE id=?").run(requestId);throw fail(503,'Message delivery is unconfirmed. Check your chat before sending again.');}
 }
 const router=express.Router();router.use('/api/companies/:company/bots',(req,res,next)=>{if(!req.workspaceIsOwner||req.boardlyConnection)return res.status(403).json({error:'Only the company owner can manage bots.'});company(Number(req.params.company));res.setHeader('Cache-Control','private, no-store');next();});
 router.use(express.json({limit:'8kb'}));
 const route='/api/companies/:company/bots/:provider';
 const handle=fn=>async(req,res,next)=>{try{const c=Number(req.params.company),p=req.params.provider;company(c);validProvider(p);res.json(await fn(req,c,p));}catch(e){next(e);}};
 router.get(route,handle((q,c,p)=>state(c,p)));
 router.put(route,handle((q,c,p)=>connect(c,p,q.body.token)));
 router.delete(route,handle((q,c,p)=>{db.prepare('DELETE FROM company_bots WHERE company_id=? AND provider=?').run(c,p);return{saved:false};}));
 router.get(route+'/destinations',handle((q,c,p)=>destinations(c,p,q.query.guild)));
 router.put(route+'/destination',handle((q,c,p)=>destination(c,p,q.body.id)));
 router.post(route+'/pair',handle((q,c,p)=>{if(p!=='telegram')throw fail(400,'Use the Discord channel picker.');return pair(c);}));
 router.post(route+'/check',handle((q,c,p)=>{if(p!=='telegram')throw fail(400,'Use the Discord channel picker.');return findPair(c);}));
 router.post(route+'/preview',handle((q,c,p)=>({text:preview(c,q.body.project_id)})));
 router.post(route+'/send',handle((q,c,p)=>{const text=q.body.test===true?'Boardly is connected. Your bot can send project updates here.':preview(c,q.body.project_id);if(q.body.test!==true&&q.body.preview!==text)throw fail(409,'The project changed. Preview the update again.');return send(c,p,q.body.request_id,text);}));
 router.use((e,req,res,next)=>e.status?res.status(e.status).json({error:e.message}):next(e));return{router,state};
}
module.exports={createCompanyBots,request};
