import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import ChatGPTConnection from './ChatGPTConnection.jsx';
const input='rounded-lg bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm';
const button='rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const dollars=n=>'$'+Number(n).toFixed(4);
const storage=n=>n===null?'Unlimited storage':n>=1024**4?'1 TB':`${n/1024**3} GB`;
export default function AccountFunding({section}){
 const [plan,setPlan]=useState(null),[ai,setAi]=useState(null),[form,setForm]=useState(null),[billing,setBilling]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[seats,setSeats]=useState(1);
 async function load(){const results=await Promise.allSettled([api.get('/api/account/plan'),api.get('/api/ai/settings'),api.get('/api/billing/status')]);const [p,a,b]=results;if(p.status==='fulfilled')setPlan(p.value);if(a.status==='fulfilled'){setAi(a.value);setForm({mode:a.value.mode==='provider'?'key':a.value.mode,model:a.value.mode==='provider'?a.value.models[0].id:a.value.model,monthly_cap:a.value.monthly_cap,api_key:''});}if(b.status==='fulfilled'){setBilling(b.value);setSeats(b.value.paid_extra_users||1);}const failures=results.filter(r=>r.status==='rejected');if(failures.length)setError(failures.map(r=>r.reason.message).join(' '));}

 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const checkout=(kind,quantity)=>act(async()=>{const result=await api.post('/api/billing/checkout',{kind,quantity});location.assign(result.url);});
 return <div className="space-y-6">
 {!plan&&!ai&&!error&&<p role="status" className="text-sm text-zinc-400">Loading account settings…</p>}
 {error&&<div role="alert" className="text-rose-300">{error} <button className={button} disabled={busy} onClick={()=>act(load)}>Refresh account</button></div>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}
 {section==='billing'&&billing&&plan?.owner&&<section className="rounded-xl border border-zinc-700 p-4 space-y-3"><h3 className="font-semibold">Billing & user seats</h3><p className="text-sm">{billing.paid_extra_users||0} paid extra users · {billing.complimentary_users||0} complimentary users (never billed)</p><p className="text-xs text-zinc-400">Plan users include the account owner. Extra users are a separate subscription. Changing a plan does not cancel your extra-user subscription. Stripe shows the charge or credit before you confirm a change.</p>{(billing.subscriptions||[]).map(s=><p key={s.id} className="text-sm">{s.kind.replaceAll('_',' ')}: {s.status.replaceAll('_',' ')}{s.cancel_at_period_end?' · cancels '+(s.period_end?new Date(s.period_end*1000).toLocaleDateString():'at the end of the paid period'):''}{s.scheduled_change?' · change scheduled in Stripe':''}</p>)}{billing.ready&&<button className={button} disabled={busy} onClick={()=>act(async()=>{const r=await api.post('/api/billing/portal');location.assign(r.url);})}>Billing portal · invoices, card & cancellation</button>}<p className="text-xs text-zinc-400">To return to Free, cancel the paid plan in the portal. To stop all recurring workspace charges, cancel extra users there too. Cancellation takes effect at the end of the paid period. Complimentary seats remain. Existing workspace data is not deleted by a downgrade.</p></section>}
 {section==='ai'&&<section className="space-y-3"><h3 className="font-semibold">Connect your own AI account</h3><p className="text-sm text-zinc-400">Sign in to your ChatGPT/Codex account or connect your provider API key. Your provider handles AI usage charges and limits. Work in companies you own uses your connection; members never receive its credentials.</p><div className="flex flex-wrap gap-2">{[['claude','Claude & Claude Code'],['kimi','Kimi & Kimi Code'],['local','Local AI']].map(([id,name])=><a key={id} href={'#/settings/'+id} className={button}>{name}</a>)}</div>{ai?.mode==='provider'&&<p role="status" className="text-indigo-300 text-sm">Current AI: {ai.provider} · {ai.model||'Reconnect to resume'}. <a className="underline" href={'#/settings/'+ai.provider}>Manage connection</a></p>}</section>}
 {section==='ai'&&<ChatGPTConnection onChange={()=>load().catch(e=>setError(e.message))} ownerSubscription={plan?.owner&&plan.plan.slug==='owner'&&ai?.mode==='none'}/>}
 {section==='billing'&&plan&&<section className="space-y-4"><h3 className="font-semibold">{plan.owner?'Your account':'Shared account'} · {plan.plan.name}</h3><p className="text-sm text-zinc-400">{plan.usage.companies} / {plan.company_limit??'Unlimited'} companies · {plan.usage.users} / {plan.user_limit??'Unlimited'} users · {storage(plan.plan.storage_bytes)} storage allowance</p>{!plan.owner&&<p className="text-sm text-zinc-400">The company owner funds your seat and AI work in this shared workspace. Your own AI settings apply to your own workspace.</p>}
 <div className="grid sm:grid-cols-3 gap-3">{plan.plans.map(p=><article key={p.slug} className="rounded-xl border border-zinc-700 p-4 space-y-2"><h4 className="font-semibold">{p.name}</h4><p className="text-xl">{p.monthly_price?'$'+p.monthly_price:'Free'}{p.monthly_price>0&&<span className="text-xs text-zinc-400"> / month</span>}</p><p className="text-sm text-zinc-400">{p.companies} {p.companies===1?'company':'companies'} · {p.users} {p.users===1?'user':'users'} · {storage(p.storage_bytes)}</p><p className="text-xs text-zinc-400">Additional users: $9 each / month</p>{plan.owner&&plan.plan.slug!=='owner'&&p.monthly_price>0&&<button disabled={busy||!plan.billing_ready} className={button} onClick={()=>checkout(p.slug)}>Choose plan</button>}</article>)}</div>
 {plan.owner&&plan.plan.users!==null&&<div className="flex flex-wrap items-center gap-3"><label className="text-sm">Total paid extra users <input aria-label="Additional paid users" type="number" min="1" max="10000" step="1" value={seats} onChange={e=>setSeats(Number(e.target.value))} className={input+' w-24 ml-2'}/></label><button disabled={busy||!plan.billing_ready||!Number.isInteger(seats)||seats<1||seats>10000} className={button} onClick={()=>checkout('extra_users',seats)}>Review ${seats*9}/month</button><span className="text-xs text-zinc-400">This sets your total paid extra seats, not an additional purchase each time. To remove all paid extra users, cancel that subscription in the billing portal.</span></div>}
 {!plan.billing_ready&&<p className="text-xs text-amber-200">Subscription checkout is awaiting Boardly’s payment-provider setup.</p>}</section>}
 {section==='ai'&&ai&&form&&<section className="border-t border-zinc-700 pt-5 space-y-4"><div><h3 className="font-semibold">OpenAI model & API key</h3><div className="space-y-4 mt-4"><p className="text-sm text-zinc-400">ChatGPT/Codex sign-in uses your account’s plan and limits. An OpenAI API key uses your separate OpenAI API billing. Saving this form selects the OpenAI connection for companies you own.</p>
 <form className="space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{await api.put('/api/ai/settings',form);await load();setNotice('Your AI settings were saved.');});}}><div className="flex flex-wrap gap-4"><label className="text-sm">AI connection<select aria-label="AI payment method" className={input+' block mt-2'} value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="none">{plan?.owner&&plan.plan.slug==='owner'?'Connected Codex subscription':'No AI connection'}</option>{ai.mode==='chatgpt'&&<option value="chatgpt">My ChatGPT account</option>}<option value="key">My OpenAI API key</option></select></label><label className="text-sm">Model<select aria-label="AI model" className={input+' block mt-2'} value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{ai.models.map(m=><option key={m.id}>{m.id}</option>)}</select></label></div>
 {form.mode==='key'&&<label className="block text-sm">OpenAI API key<input type="password" autoComplete="new-password" spellCheck={false} aria-label="OpenAI API key" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} placeholder={ai.has_key?'Key saved · enter a new key to replace it':'sk-…'} className={input+' block w-full mt-2'}/><span className="block text-xs text-zinc-400 mt-2">Encrypted on the server. Your key is never included in project chats or shared with other members.</span></label>}

 <p className="text-xs text-zinc-400">Cloud AI can work with project tasks, text files and enabled SSH connections. Connected Codex workers can also run in a persistent cloud environment.</p>
 <button disabled={busy} className={button+' bg-indigo-600'}>Save AI settings</button>{ai.has_key&&<button type="button" disabled={busy} className={button+' ml-2'} onClick={()=>act(async()=>{await api.put('/api/ai/settings',{...form,mode:'none',api_key:''});await load();setNotice('Personal API key removed.');})}>Remove key</button>}</form>

 <p className="text-sm">This month: OpenAI cost {dollars(ai.usage.provider_cost)} · Boardly AI charges {dollars(ai.usage.boardly_charge)}</p>{ai.review>0&&<p className="text-sm text-amber-200">{ai.review} interrupted request(s) need usage review. Unconfirmed usage is not automatically charged again.</p>}
 <details className="text-sm"><summary className="cursor-pointer text-zinc-400">Usage and rates</summary><p className="my-3 text-xs text-zinc-400">Standard OpenAI USD per 1 million tokens, rate version {ai.rate_version}. Your own API key is billed directly by OpenAI. Set spending limits in your provider dashboard. Longer contexts use OpenAI’s applicable long-context prices.</p><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>Model</th><th>Input</th><th>Cached</th><th>Cache write</th><th>Output</th></tr></thead><tbody>{ai.models.map(m=><tr key={m.id}><td className="py-2">{m.id}</td><td>${m.input}</td><td>${m.cached}</td><td>${m.cache_write}</td><td>${m.output}</td></tr>)}</tbody></table></div>{ai.history.map((h,i)=><p key={i} className="text-xs text-zinc-400 py-1">{new Date(h.created_at).toLocaleString()} · {h.model} · OpenAI {dollars(h.provider_cost)} · Boardly {dollars(h.boardly_charge)}</p>)}</details>
 </div></div></section>}
 </div>;
}
