import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import AccountGithub from './AccountGithub.jsx';
import SshConnections from './SshConnections.jsx';
import TailscaleConnection from './TailscaleConnection.jsx';
const input='rounded-lg bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm';
const button='rounded-lg border border-zinc-700 px-4 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const dollars=n=>'$'+Number(n).toFixed(4);
const storage=n=>n===null?'Unlimited storage':n>=1024**4?'1 TB':`${n/1024**3} GB`;
export default function AccountSettings({onClose,initialSection}){
 const [plan,setPlan]=useState(null),[ai,setAi]=useState(null),[form,setForm]=useState(null),[billing,setBilling]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[seats,setSeats]=useState(1),[consent,setConsent]=useState(false);
 async function load(){const [p,a,b]=await Promise.all([api.get('/api/account/plan'),api.get('/api/ai/settings'),api.get('/api/billing/status')]);setPlan(p);setAi(a);setBilling(b);setForm({mode:a.mode,model:a.model,monthly_cap:a.monthly_cap,api_key:''});}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const checkout=(kind,quantity)=>act(async()=>{const result=await api.post('/api/billing/checkout',{kind,quantity});location.assign(result.url);});
 return <div className="fixed inset-0 z-[70] bg-black/70 p-3 flex items-center justify-center" onClick={onClose}><section role="dialog" aria-modal="true" aria-label="Account and AI settings" onClick={e=>e.stopPropagation()} className="w-full max-w-4xl max-h-[94vh] overflow-auto rounded-2xl border border-zinc-700 bg-zinc-900 p-6 space-y-6">
 <header className="flex justify-between"><div><h2 className="text-xl font-semibold">Account & AI</h2><p className="text-sm text-zinc-400 mt-1">Your workspace subscription and AI funding.</p></div><button aria-label="Close account settings" onClick={onClose}>✕</button></header>
 {error&&<p role="alert" className="text-rose-300">{error}</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}
 {plan?.owner&&<AccountGithub focus={initialSection==='github'}/>}
 {plan&&<section className="space-y-4"><h3 className="font-semibold">{plan.owner?'Your account':'Shared account'} · {plan.plan.name}</h3><p className="text-sm text-zinc-400">{plan.usage.companies} / {plan.company_limit??'Unlimited'} companies · {plan.usage.users} / {plan.user_limit??'Unlimited'} users · {storage(plan.plan.storage_bytes)} storage allowance</p>{!plan.owner&&<p className="text-sm text-zinc-400">The company owner funds your seat and AI work in this shared workspace. Your own AI settings apply to your own workspace.</p>}
 <div className="grid sm:grid-cols-3 gap-3">{plan.plans.map(p=><article key={p.slug} className="rounded-xl border border-zinc-700 p-4 space-y-2"><h4 className="font-semibold">{p.name}</h4><p className="text-xl">{p.monthly_price?'$'+p.monthly_price:'Free'}{p.monthly_price>0&&<span className="text-xs text-zinc-400"> / month</span>}</p><p className="text-sm text-zinc-400">{p.companies} {p.companies===1?'company':'companies'} · {p.users} {p.users===1?'user':'users'} · {storage(p.storage_bytes)}</p><p className="text-xs text-zinc-400">Additional users: $9 each / month</p>{plan.owner&&plan.plan.slug!=='owner'&&p.monthly_price>0&&<button disabled={busy||!plan.billing_ready} className={button} onClick={()=>checkout(p.slug)}>Choose plan</button>}</article>)}</div>
 {plan.owner&&plan.plan.users!==null&&<div className="flex flex-wrap items-center gap-3"><label className="text-sm">Additional users <input aria-label="Additional paid users" type="number" min="1" max="10000" value={seats} onChange={e=>setSeats(Number(e.target.value))} className={input+' w-24 ml-2'}/></label><button disabled={busy||!plan.billing_ready} className={button} onClick={()=>checkout('extra_users',seats)}>Review ${seats*9}/month</button><span className="text-xs text-zinc-400">After your included allowance, on every plan.</span></div>}
 {!plan.billing_ready&&<p className="text-xs text-amber-200">Subscription checkout is awaiting Boardly’s payment-provider setup.</p>}</section>}
 {ai&&form&&<section className="border-t border-zinc-700 pt-5 space-y-4"><h3 className="font-semibold">AI funding for your own workspace</h3><p className="text-sm text-zinc-400">Bring your own OpenAI API key and pay OpenAI directly, or attach a billing card and pay 2× OpenAI’s standard API usage cost. These settings fund AI work by you and your members in companies you own.</p>
 <form className="space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{await api.put('/api/ai/settings',form);await load();setNotice('Your AI settings were saved.');});}}><div className="flex flex-wrap gap-4"><label className="text-sm">Payment method<select aria-label="AI payment method" className={input+' block mt-2'} value={form.mode} onChange={e=>setForm({...form,mode:e.target.value})}><option value="none">{plan?.owner&&plan.plan.slug==='owner'?'Connected Codex subscription':'No API connection'}</option><option value="key">My OpenAI API key</option><option value="card" disabled={!ai.billing_ready}>Card · 2× OpenAI usage</option></select></label><label className="text-sm">Model<select aria-label="AI model" className={input+' block mt-2'} value={form.model} onChange={e=>setForm({...form,model:e.target.value})}>{ai.models.map(m=><option key={m.id}>{m.id}</option>)}</select></label></div>
 {form.mode==='key'&&<label className="block text-sm">OpenAI API key<input type="password" autoComplete="new-password" spellCheck={false} aria-label="OpenAI API key" value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} placeholder={ai.has_key?'Key saved · enter a new key to replace it':'sk-…'} className={input+' block w-full mt-2'}/><span className="block text-xs text-zinc-400 mt-2">Encrypted on the server. Your key is never included in project chats or shared with other members.</span></label>}
 {form.mode==='card'&&<label className="block text-sm">Monthly AI spending cap (USD, resets on the first day of each month UTC)<input aria-label="Monthly AI spending cap" type="number" min="1" max="10000" step="0.01" value={form.monthly_cap} onChange={e=>setForm({...form,monthly_cap:Number(e.target.value)})} className={input+' ml-3 w-28'}/></label>}
 <p className="text-xs text-zinc-400">Cloud AI can work with project tasks, text files and enabled SSH connections. Connected Codex workers can also run in a persistent cloud environment.</p>
 <button disabled={busy} className={button+' bg-indigo-600'}>Save AI settings</button>{ai.has_key&&<button type="button" disabled={busy} className={button+' ml-2'} onClick={()=>act(async()=>{await api.put('/api/ai/settings',{...form,mode:'none',api_key:''});await load();setNotice('Personal API key removed.');})}>Remove key</button>}</form>
 <div className="rounded-xl border border-zinc-700 p-4 space-y-3"><h4 className="text-sm font-medium">Card billing for AI</h4><p className="text-xs text-zinc-400">For example, $1 of OpenAI usage costs $2 through Boardly. Cached input and output are metered separately. Card details are saved by Stripe; this is separate from cards assigned for project purchases.</p>{!ai.billing_ready?<p className="text-sm text-amber-200">Card-funded AI is awaiting Boardly’s Stripe and OpenAI setup. You can use your own API key now.</p>:<><label className="text-sm flex gap-2"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>I agree to monthly billing at 2× OpenAI usage, within my spending cap.</label><button disabled={busy||!consent} className={button} onClick={()=>act(async()=>{await api.put('/api/ai/settings',{...form,mode:'card',api_key:''});const r=await api.post('/api/ai/checkout',{consent});location.assign(r.url);})}>{billing?.ai_active?'Manage AI billing card':'Attach card & activate AI billing'}</button></>}</div>
 <p className="text-sm">This month: OpenAI cost {dollars(ai.usage.provider_cost)} · Boardly AI charges {dollars(ai.usage.boardly_charge)}</p>{ai.review>0&&<p className="text-sm text-amber-200">{ai.review} interrupted request(s) need usage review. Unconfirmed usage is not automatically charged again.</p>}
 <details className="text-sm"><summary className="cursor-pointer text-zinc-400">Usage and rates</summary><p className="my-3 text-xs text-zinc-400">Standard OpenAI USD per 1 million tokens, rate version {ai.rate_version}. Card billing applies 2× these prices. Longer contexts use OpenAI’s applicable long-context prices.</p><div className="overflow-auto"><table className="w-full text-left text-xs"><thead><tr><th>Model</th><th>Input</th><th>Cached</th><th>Cache write</th><th>Output</th></tr></thead><tbody>{ai.models.map(m=><tr key={m.id}><td className="py-2">{m.id}</td><td>${m.input}</td><td>${m.cached}</td><td>${m.cache_write}</td><td>${m.output}</td></tr>)}</tbody></table></div>{ai.history.map((h,i)=><p key={i} className="text-xs text-zinc-400 py-1">{new Date(h.created_at).toLocaleString()} · {h.model} · OpenAI {dollars(h.provider_cost)} · Boardly {dollars(h.boardly_charge)}</p>)}</details>
 </section>}
 {plan?.owner&&<div className="border-t border-zinc-700 pt-5"><SshConnections kind="owner" id={0}/></div>}
 <TailscaleConnection/>
 {billing?.ready&&<button className={button} disabled={busy} onClick={()=>act(async()=>{const r=await api.post('/api/billing/portal');location.assign(r.url);})}>Manage subscriptions, invoices & billing card</button>}
 </section></div>;
}
