import React,{useEffect,useState} from 'react';
import {X,MessageSquare,Users,Square} from 'lucide-react';
import {api} from '../api.js';
const button='rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const field='w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm';
const modes=[['ask','Ask','Answers and clarification'],['plan','Plan','Discuss steps without acting'],['work','Work','Start project agents']];
export default function AgentHub({kind,id,onClose,onOpen}){
 const [data,setData]=useState(null),[mode,setMode]=useState(''),[input,setInput]=useState(''),[selected,setSelected]=useState(''),[thread,setThread]=useState(null),[assignments,setAssignments]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[online,setOnline]=useState(false);
 const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID());
 const base=`/api/agents/${kind}/${id}`;
 async function load(){const [d,s]=await Promise.all([api.get(base),api.get('/api/chat/status')]);setData(d);setOnline(s.online);if(selected)setThread(await api.get(`/api/discussions/threads/${selected}`));}
 useEffect(()=>{let alive=true;const refresh=()=>{if(alive)load().catch(e=>setError(e.message));};refresh();const timer=setInterval(refresh,2000);return()=>{alive=false;clearInterval(timer);};},[base,selected]);
 const running=thread?.runs?.some(r=>['queued','running'].includes(r.status));
 async function send(e){e.preventDefault();if(!mode||!input.trim()||busy)return;setBusy(true);setError('');try{
   if(mode==='work'){
    await api.post(base+'/swarms',{mode:'work',request_key:requestKey,instruction:input,assignments:Object.entries(assignments).filter(([,a])=>a.enabled).map(([project_id,a])=>({project_id:Number(project_id),instruction:a.instruction||''}))});
    setRequestKey(crypto.randomUUID());
   }else{
    let tid=selected;if(!tid){const t=await api.post(base+'/threads',{});tid=t.id;setSelected(tid);}
    await api.post(`/api/discussions/threads/${tid}/messages`,{content:input,mode});setThread(await api.get(`/api/discussions/threads/${tid}`));
   }
   setInput('');await load();
  }catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section role="dialog" aria-label={`${kind} AI`} className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-3 sm:p-6"><div className="w-full max-w-4xl max-h-full flex flex-col rounded-2xl border border-zinc-700 bg-zinc-900 shadow-2xl">
  <header className="flex items-center gap-3 p-5 border-b border-zinc-800"><MessageSquare className="text-indigo-300"/><div className="flex-1"><h2 className="font-semibold text-lg">AI · {data?.scope.name||'Loading…'}</h2><p className="text-xs text-zinc-400">{kind==='company'?'Company-wide':'Board'} conversations and agents · {online?'Connected':'Agent worker offline — requests will wait'}</p></div><button onClick={onClose} aria-label="Close AI"><X/></button></header>
  <div className="overflow-y-auto p-5 space-y-5">
   <fieldset><legend className="text-sm font-medium mb-3">How would you like to work?</legend><div className="grid grid-cols-3 gap-2">{modes.map(([value,label,description])=><button key={value} type="button" aria-pressed={mode===value} onClick={()=>setMode(value)} className={button+` text-left ${mode===value?'border-indigo-400 bg-indigo-500/20':''}`}><strong className="block">{label}</strong><span className="block text-xs text-zinc-400 mt-1">{description}</span></button>)}</div></fieldset>
   {mode!=='work'&&<><div className="flex gap-2"><select aria-label="Company conversation" className={field} value={selected} onChange={e=>{setSelected(e.target.value);setThread(null);}}><option value="">New conversation</option>{data?.threads.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><button className={button} onClick={()=>{setSelected('');setThread(null);}}>New</button></div>
    <p className="text-xs text-zinc-400">Ask and Plan read saved tasks, comments, project information and GitHub connection details.</p>
    {data?.github?.some(g=>g.saved)&&<div aria-label="Saved project repositories" className="rounded-lg border border-zinc-700 p-3 space-y-2 text-xs text-zinc-400">{data.github.filter(g=>g.saved).map(g=><p key={g.project_id} className="break-words"><span className="text-zinc-200">{g.board_name} / {g.project_name}</span> · {g.repository} · {g.branch}{!g.allow_agent?' · Agent access paused':''}</p>)}<p>These connections stay saved across conversations.</p></div>}
    <div className="space-y-3 max-h-80 overflow-y-auto" aria-live="polite">{thread?.runs.map(r=><React.Fragment key={r.id}><div className="rounded-xl bg-indigo-500/15 p-3"><p className="text-xs text-indigo-300 mb-1">You · {r.mode==='plan'?'Plan':'Ask'}</p><p className="text-sm whitespace-pre-wrap">{r.prompt}</p></div><div className="rounded-xl border border-zinc-800 p-3"><p className="text-xs text-zinc-400 mb-1">{r.status==='running'?(Date.now()-r.updated_at>15000?'Waiting for worker to reconnect':'AI is replying'):r.status==='queued'?'Queued':r.status==='completed'?'AI':r.status}</p><p className="text-sm whitespace-pre-wrap">{r.draft||r.error}</p>{['queued','running'].includes(r.status)&&<button className={button+' mt-2'} onClick={async()=>{await api.post(`/api/discussions/jobs/${r.id}/cancel`,{});await load();}}>Stop reply</button>}</div></React.Fragment>)}</div>
   </>}
   {mode==='work'&&<><div><h3 className="font-medium flex gap-2 items-center"><Users size={18}/>Create an agent swarm</h3><p className="text-xs text-zinc-400 mt-2">Choose a project for each agent and describe its assignment. Up to {data?.max_agents||4} projects run together. Work in the same project waits its turn.</p></div>
    {!data?.scope.projects.length&&<p className="text-sm text-amber-300">Add a project to this {kind} before starting agents.</p>}
    {data?.scope.projects.map(p=><div key={p.id} className="rounded-xl border border-zinc-700 p-3 space-y-2"><label className="flex gap-2 text-sm"><input type="checkbox" checked={!!assignments[p.id]?.enabled} onChange={e=>{setRequestKey(crypto.randomUUID());setAssignments({...assignments,[p.id]:{...assignments[p.id],enabled:e.target.checked}});}}/>{p.board_name} / {p.name}</label>{assignments[p.id]?.enabled&&<input aria-label={`Assignment for ${p.board_name} / ${p.name}`} className={field} maxLength={10000} placeholder="Agent assignment (optional — otherwise use the shared objective)" value={assignments[p.id].instruction||''} onChange={e=>{setRequestKey(crypto.randomUUID());setAssignments({...assignments,[p.id]:{...assignments[p.id],instruction:e.target.value}});}}/>}</div>)}
   </>}
   <form onSubmit={send} className="space-y-3"><label className="block text-sm">{mode==='work'?'Shared objective':'Your message'}<textarea aria-label="AI message" className={field+' mt-2'} rows={3} maxLength={30000} value={input} onChange={e=>{setInput(e.target.value);setRequestKey(crypto.randomUUID());}} placeholder={!mode?'Choose Ask, Plan or Work above…':mode==='plan'?'Help me plan…':mode==='work'?'What should these agents accomplish?':'What would you like to understand?'}/></label>{error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}<button disabled={!mode||!input.trim()||busy||(mode!=='work'&&running)||(mode==='work'&&!Object.values(assignments).some(a=>a.enabled))} className={button+' bg-indigo-600'}>{busy?'Sending…':mode==='work'?`Start ${Object.values(assignments).filter(a=>a.enabled).length} agents`:mode==='plan'?'Discuss plan':'Ask AI'}</button></form>
   {!!data?.swarms.length&&<div className="space-y-3 border-t border-zinc-800 pt-4"><h3 className="font-medium">Swarm activity</h3>{data.swarms.map(s=><article key={s.id} className="rounded-xl border border-zinc-700 p-4 space-y-3"><div className="flex items-start gap-3"><h4 className="text-sm font-semibold flex-1">{s.title}</h4>{s.agents.some(a=>['queued','running'].includes(a.status))&&<button className={button} onClick={async()=>{try{await api.post(`/api/swarms/${s.id}/cancel`,{});await load();}catch(e){setError(e.message);}}}><Square size={12} className="inline mr-1"/>Stop swarm</button>}</div>{s.agents.map(a=><div key={a.id} className="flex gap-3 items-center justify-between text-sm"><div><p>{a.board_name} / {a.project_name}</p><p className="text-xs text-zinc-400">{a.status==='running'&&Date.now()-a.updated_at>15000?'Waiting for worker':a.status}{a.status==='running'&&Date.now()-a.updated_at<=15000?` · ${a.progress}`:''}{a.error?` · ${a.error}`:''}</p></div><button className={button} onClick={()=>{onClose();onOpen(a.project_id);}}>Open project</button></div>)}</article>)}</div>}
  </div>
 </div></section>;
}
