import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton,settingsInput,accountSettings} from './SettingsShell.jsx';
const info={claude:{name:'Claude',url:'https://platform.claude.com/settings/keys',description:'Use a Claude API key to power Boardly agents. Your Claude chat subscription is separate from API billing.'},kimi:{name:'Kimi',url:'https://platform.kimi.ai/',description:'Use your Kimi API Platform key for Boardly agents. Kimi API billing is separate from a Kimi Code or chat subscription.'},local:{name:'Local AI',description:'Connect Ollama, LM Studio, vLLM or another OpenAI-compatible model server running on your own computer.'}};
export default function AIProviderConnection({provider,platformOwner=false}){
 const [data,setData]=useState(null),[form,setForm]=useState({token:'',model:'',device_id:'',port:11434}),[devices,setDevices]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const config=info[provider];
 async function load(){const d=await api.get('/api/account/ai-providers'),current=d.connections.find(c=>c.provider===provider);setData({...current,history:d.history.filter(h=>h.provider===provider)});setForm({token:'',model:current.model,device_id:current.device_id,port:current.port});}
 useEffect(()=>{setData(null);setError('');setNotice('');load().catch(e=>setError(e.message));if(provider==='local')api.get('/api/account/tailscale').then(d=>setDevices(d.devices||[])).catch(e=>setError(e.message));},[provider]);
 async function act(fn,notice){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(notice);}catch(e){setError(e.message);}finally{setForm(f=>({...f,token:''}));setBusy(false);}}
 if(!config)return null;
 return <div className="space-y-5">{error&&<p role="alert" className="text-rose-300">{error}</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}<p className="text-sm text-zinc-400">{config.description}</p>
 {!data&&!error&&<p>Loading connection…</p>}
 {data&&<><div className="rounded-xl border border-zinc-700 p-4"><h3 className="font-semibold">{data.active?(data.saved?'Selected for Boardly agents':'Selected · reconnect to resume'):data.saved?'Connection saved':'Set up '+config.name}</h3><p className="text-sm text-zinc-400 mt-2">{data.active?'Work in companies you own uses this provider, including work by permitted members.':'Connect and choose a model, then select Use for Boardly agents when you are ready to switch.'}</p></div>
 <form className="space-y-4" onSubmit={e=>{e.preventDefault();act(()=>api.put('/api/account/ai-providers/'+provider,form),'Connection verified. Choose a model, then activate when ready.');}}>
 {provider==='local'&&<><label className="block text-sm">Tailscale computer<select aria-label="Local AI computer" value={form.device_id} onChange={e=>setForm({...form,device_id:e.target.value})} required className={settingsInput+' mt-2'}><option value="">Choose your model server</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name||d.hostname||d.id}{d.online===false?' · offline':''}</option>)}</select></label><label className="block text-sm">Server port<input aria-label="Local AI port" type="number" min="1" max="65535" required value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})} className={settingsInput+' mt-2'}/></label><p className="text-sm text-zinc-400">Ollama usually uses 11434; LM Studio usually uses 1234. Run the server on its Tailscale address so Boardly can reach it. Load a model with tool calling, and vision support for desktop screenshots.</p><button type="button" className={settingsButton} onClick={()=>accountSettings('tailscale')}>Manage Tailscale network</button></>}
 <label className="block text-sm">{config.name} API key{provider==='local'?' (optional)':''}<input aria-label={config.name+' API key'} type="password" autoComplete="new-password" value={form.token} onChange={e=>setForm({...form,token:e.target.value})} required={provider!=='local'&&!data.saved} className={settingsInput+' mt-2'} placeholder={data.has_key?'Key saved · paste to replace':'Paste API key'}/></label>
 {config.url&&<a className="text-sm text-indigo-300 underline" href={config.url} target="_blank" rel="noreferrer">Open {config.name} API dashboard</a>}
 {!!data.models.length&&<label className="block text-sm">Model<select aria-label={config.name+' model'} value={form.model} onChange={e=>setForm({...form,model:e.target.value})} className={settingsInput+' mt-2'}>{data.models.map(m=><option key={m} value={m}>{m}</option>)}</select></label>}
 <p className="text-sm text-zinc-400">API keys are encrypted and kept out of agent messages. Connection verification lists available models without generating a paid response.</p>
 <button disabled={busy} className={settingsButton+' bg-indigo-600'}>{data.saved?'Verify & save model':'Verify connection'}</button>
 </form>
 <div className="flex gap-3 flex-wrap"><button disabled={busy||!data.saved||data.active||form.model!==data.model} className={settingsButton} onClick={()=>act(()=>api.post('/api/account/ai-providers/'+provider+'/activate'),'Selected for new Boardly AI requests.')}>Use for Boardly agents</button>{data.saved&&<button disabled={busy} className={settingsButton} onClick={()=>act(()=>api.del('/api/account/ai-providers/'+provider),'Disconnected. Requests using this provider are paused until you reconnect or choose another AI connection.')}>Disconnect</button>}</div>
 <p className="text-sm text-zinc-400">{provider==='local'?'Your model server handles inference. Running costs and any upstream provider charges belong to that server.':'API usage is billed by '+config.name+' directly to your provider account.'} Boardly does not add an AI usage markup. Set spending limits in your provider account.</p>
 {provider!=='local'&&<section className="border-t border-zinc-700 pt-4 space-y-3"><h3 className="font-semibold">Connect your {provider==='claude'?'Claude Code':'Kimi Code'} client</h3><p className="text-sm text-zinc-400">Keep your coding client and its sign-in on your own computer. Add Boardly as an MCP server to let that client work with your workspace.</p>{platformOwner?<button className={settingsButton} onClick={()=>accountSettings('mcp')}>Create a coding-client connection</button>:<p className="text-sm text-zinc-400">External MCP client access is currently enabled for the platform owner.</p>}</section>}
 {!!data.history.length&&<details><summary className="text-sm cursor-pointer">Recent provider usage</summary><ul className="mt-3 space-y-2">{data.history.map((h,i)=><li key={i} className="text-sm text-zinc-400">{h.model} · {h.status} · {h.input_tokens??'Unknown'} input / {h.output_tokens??'Unknown'} output tokens · {new Date(h.created_at).toLocaleString()}</li>)}</ul></details>}
 </>}
 </div>;
}
