import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton as button,settingsInput as input} from './SettingsShell.jsx';
const providers=[['s3','Amazon S3'],['r2','Cloudflare R2'],['b2','Backblaze B2'],['wasabi','Wasabi'],['minio','MinIO / another S3 service'],['webdav','WebDAV / Nextcloud']];
const blank={service:'s3',label:'',endpoint:'',region:'us-east-1',bucket:'',prefix:'',access_key:'',secret_key:'',session_token:'',username:'',password:'',read_only:true};
export default function CompanyStorage({companyId,owner,canUpload=owner}){
 const [data,setData]=useState(null),[draft,setDraft]=useState(null),[connection,setConnection]=useState(null),[folder,setFolder]=useState(''),[files,setFiles]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const base=`/api/companies/${companyId}/storage`;
 const load=()=>api.get(base).then(setData);
 useEffect(()=>{let live=true;api.get(base).then(d=>live&&setData(d)).catch(e=>live&&setError(e.message));return()=>{live=false;};},[base]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function browse(c,path='',cursor=''){const result=await api.get(base+'/'+c.id+'/files?'+new URLSearchParams({path,cursor}));setConnection(c);setFolder(path);setFiles(prev=>cursor?{...result,items:[...(prev?.items||[]),...result.items]}:result);}
 if(!data)return <p role={error?'alert':'status'}>{error||'Loading company storage…'}</p>;
 const field=(name,label,type='text',required=false,hint='')=><label className="block text-sm">{label}<input type={type} className={input+' mt-1'} required={required} autoComplete={type==='password'?'new-password':'off'} value={draft[name]} onChange={e=>setDraft({...draft,[name]:e.target.value})}/>{hint&&<span className="block text-xs text-zinc-500 mt-1">{hint}</span>}</label>;
 return <div className="space-y-6" data-testid="company-storage"><div><p className="text-sm text-zinc-400 mt-2">Connect a place for this company’s files. Browse, download and optionally upload without sharing storage passwords with your team.</p><p className="text-xs text-zinc-500 mt-2">Files stay with your storage provider and use its storage allowance. Boardly project uploads remain in Files. This connection does not move existing files. Each transfer can be up to 25 MB.</p></div>
  {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}{notice&&<p role="status" className="text-emerald-300 text-sm">{notice}</p>}
  {owner&&!draft&&<button className={button+' bg-indigo-600'} onClick={()=>setDraft({...blank})}>Connect storage</button>}
  {draft&&owner&&<form className="rounded-xl border border-indigo-500/40 bg-zinc-900 p-4 space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{const {service,...body}=draft;const saved=await api.post(base,{...body,provider:service==='webdav'?'webdav':'s3'});setDraft(null);await load();setNotice('Storage connected. Boardly successfully opened the selected folder.');await browse(saved);});}}>
   <label className="block text-sm">Storage service<select className={input+' mt-1'} value={draft.service} onChange={e=>setDraft({...blank,service:e.target.value,region:e.target.value==='r2'?'auto':'us-east-1'})}>{providers.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
   <details open className="rounded-lg bg-zinc-950 p-4 text-sm"><summary className="cursor-pointer font-medium">Help me connect it, step by step</summary><ol className="list-decimal pl-5 mt-3 space-y-2 text-zinc-300"><li>Open your storage provider and choose the bucket or folder you want this company to use.</li><li>{draft.service==='webdav'?'Create an app password in that service. In Nextcloud, copy the WebDAV address from Files → Files settings.':'Create an access key for that bucket. Give it permission to list the bucket and read its files. Add upload permission only if you want to upload from Boardly.'}</li><li>Copy the details below. An endpoint is just the service address; a bucket is the container for your files.</li><li>Choose Test & connect. If something is missing, your provider’s connection details are the place to check.</li></ol><p className="text-xs text-zinc-500 mt-3">Use a public HTTPS address. Private network and Tailscale storage addresses are not supported by this connector yet.</p><div className="flex flex-wrap gap-3 mt-3"><a href={draft.service==='webdav'?'https://docs.nextcloud.com/server/latest/user_manual/en/files/access_webdav.html':draft.service==='r2'?'https://developers.cloudflare.com/r2/api/s3/tokens/':draft.service==='b2'?'https://www.backblaze.com/docs/cloud-storage-s3-compatible-api':draft.service==='wasabi'?'https://docs.wasabi.com/docs/access-keys-1':'https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-management.html'} target="_blank" rel="noreferrer" className="text-indigo-300 underline">Open provider instructions</a></div></details>
   {field('label','Name in Boardly','text',true,'Example: Marketing files')}
   {draft.service==='webdav'?<>{field('endpoint','WebDAV address','url',true,'Example: https://cloud.example.com/remote.php/dav/files/yourname/')}{field('username','Storage username','text',true)}{field('password','Storage app password','password',true)}</>:<>{field('bucket','Bucket name','text',true)}{field('region','Region','text',true,draft.service==='r2'?'Cloudflare R2 uses auto.':'Copy the region from your provider.')}{field('endpoint','S3 endpoint','url',draft.service!=='s3',draft.service==='s3'?'Leave blank for Amazon S3.':draft.service==='r2'?'Example: https://YOUR-ACCOUNT-ID.r2.cloudflarestorage.com':'Copy the S3 service URL, without the bucket name.')}{field('access_key','Access key ID','password',true)}{field('secret_key','Secret access key','password',true)}<details><summary className="text-sm text-zinc-400 cursor-pointer">Temporary AWS credentials</summary><div className="mt-3">{field('session_token','Session token','password',false,'Only needed if your AWS credentials include one.')}</div></details></>}
   {field('prefix','Folder inside this connection (optional)','text',false,'Example: marketing/ — leave blank to use the whole bucket or WebDAV folder.')}
   <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!draft.read_only} onChange={e=>setDraft({...draft,read_only:!e.target.checked})}/>Allow the owner and company editors to upload files</label>
   <div className="flex gap-2"><button className={button+' bg-indigo-600'} disabled={busy}>Test & connect</button><button type="button" className={button} disabled={busy} onClick={()=>setDraft(null)}>Cancel</button></div>
  </form>}
  {!data.connections.length&&!draft&&<p className="text-sm text-zinc-400">No external storage connected yet.{!owner&&' The account owner can connect a service here.'}</p>}
  <div className="space-y-3">{data.connections.map(c=><article key={c.id} className="rounded-xl border border-zinc-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div className="min-w-0"><h3 className="font-medium break-words">{c.label}</h3><p className="text-xs text-zinc-400 break-all mt-1">{c.provider==='s3'?`S3 · ${c.bucket}`:'WebDAV'}{c.prefix?' / '+c.prefix:''} · {c.read_only?'Browse & download':'Uploads enabled'}</p></div></div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>act(()=>browse(c))}>Browse {c.label}</button>{owner&&<><button className={button} disabled={busy} onClick={()=>act(async()=>{await api.post(base+'/'+c.id+'/test',{});await load();setNotice('Connection test passed.');})}>Test connection</button><button className={button} disabled={busy} onClick={()=>act(async()=>{await api.patch(base+'/'+c.id,{read_only:!c.read_only,revision:c.revision});await load();setConnection(null);setFiles(null);})}>{c.read_only?'Allow uploads':'Disable uploads'}</button><button className={button+' text-rose-300'} disabled={busy} onClick={()=>{if(confirm(`Disconnect ${c.label} from Boardly? Files in your storage service will remain there.`))act(async()=>{await api.del(base+'/'+c.id,{revision:c.revision});await load();setConnection(null);setFiles(null);});}}>Disconnect</button></>}</div></article>)}</div>
  {connection&&files&&<section className="rounded-xl border border-zinc-700 p-4 space-y-4"><div className="flex flex-wrap justify-between gap-3 items-center"><h3 className="font-medium break-all">{connection.label} / {folder||'Home'}</h3><div className="flex flex-wrap gap-2">{folder&&<button className={button} disabled={busy} onClick={()=>act(()=>browse(connection,folder.replace(/\/$/,'').split('/').slice(0,-1).join('/')))}>Up one folder</button>}<button className={button} disabled={busy} onClick={()=>act(()=>browse(connection,folder))}>Refresh files</button>{canUpload&&!connection.read_only&&<label className={button+' cursor-pointer'}>Upload file<input type="file" aria-label="Upload to external storage" className="sr-only" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)act(async()=>{if(file.size>data.max_file_bytes)throw Error('Choose a file up to 25 MB.');const form=new FormData();form.append('path',folder);form.append('file',file);await api.post(base+'/'+connection.id+'/files',form);await browse(connection,folder);setNotice('File uploaded to your storage service. Existing files are never overwritten.');});}}/></label>}</div></div>
   {!files.items.length&&<p className="text-sm text-zinc-400">This folder is empty.</p>}<div className="divide-y divide-zinc-800">{files.items.map(f=><div key={f.path} className="py-3 flex gap-3 items-center justify-between min-w-0"><span className="text-sm break-all">{f.folder?'📁 ':''}{f.name}{!f.folder&&<span className="text-xs text-zinc-500 ml-2">{(f.size/1024).toFixed(1)} KB</span>}</span><button className={button+' shrink-0'} disabled={busy} onClick={()=>act(()=>f.folder?browse(connection,f.path):api.download(base+'/'+connection.id+'/download?'+new URLSearchParams({path:f.path}),f.name))}>{f.folder?'Open folder':'Download'}</button></div>)}</div>{files.cursor&&<button className={button} disabled={busy} onClick={()=>act(()=>browse(connection,folder,files.cursor))}>Load more files</button>}
  </section>}
 </div>;
}
