import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton as button,settingsInput as input} from './SettingsShell.jsx';
const empty={name:'',description:'',instructions:'',enabled:true};
export default function CompanySkills({companyId,owner}){
 const [data,setData]=useState(null),[rules,setRules]=useState(''),[draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const base=`/api/companies/${companyId}/skills`;
 async function load(){const d=await api.get(base);setData(d);setRules(d.rules.instructions);}
 useEffect(()=>{let live=true;api.get(base).then(d=>{if(live){setData(d);setRules(d.rules.instructions);}}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[base]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!data)return <p role={error?'alert':'status'}>{error||'Loading company rules and skills…'}</p>;
 return <div className="space-y-7" data-testid="company-skills">
  <div><p className="text-sm text-zinc-400 mt-2">Tell your AI how this company works. Rules apply throughout this company. Enabled skills are reusable instructions for matching tasks.</p><p className="text-xs text-zinc-500 mt-2">Saved changes are used in new AI replies and runs across this company’s projects. They do not grant extra permissions. Keep passwords and API keys in Connectors.</p></div>
  {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}{notice&&<p role="status" className="text-emerald-300 text-sm">{notice}</p>}
  <form className="space-y-3" onSubmit={e=>{e.preventDefault();act(async()=>{const saved=await api.put(base+'/rules',{instructions:rules,revision:data.rules.revision});setData({...data,rules:saved});setRules(saved.instructions);setNotice('Company rules saved. New AI replies and runs will use them.');});}}>
   <label className="block font-medium">Company workflow rules<textarea aria-label="Company workflow rules" rows={7} maxLength={20000} readOnly={!owner} className={input+' mt-2 font-mono text-sm'} placeholder="Example: Read the task first. Ask me before publishing. Put blocked work in Blocked and explain what is needed." value={rules} onChange={e=>setRules(e.target.value)}/></label>
   {owner?<button disabled={busy||rules===data.rules.instructions} className={button+' bg-indigo-600'}>Save company rules</button>:<p className="text-sm text-zinc-400">The account owner manages these instructions.</p>}
  </form>
  <section className="space-y-4 border-t border-zinc-800 pt-6"><div className="flex flex-wrap justify-between items-center gap-3"><h3 className="font-semibold">Company skills</h3>{owner&&<div className="flex flex-wrap gap-2"><button className={button} disabled={busy} onClick={()=>setDraft({...empty})}>New skill</button><label className={button+' cursor-pointer'}>Import SKILL.md<input className="sr-only" aria-label="Import SKILL.md" type="file" accept=".md,text/markdown,text/plain" disabled={busy} onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)act(async()=>{if(f.size>18000)throw Error('Choose a SKILL.md file under 18 KB.');setDraft(await api.post(base+'/import',{markdown:await f.text()}));setNotice('Imported into the editor. Review it, then save.');});}}/></label></div>}</div>
   {!data.skills.length&&<p className="text-sm text-zinc-400">No skills yet. Start from a template or describe your own workflow.</p>}
   {owner&&!draft&&<div className="flex flex-wrap gap-2">{data.templates.map(t=><button key={t.name} className={button+' text-xs'} onClick={()=>setDraft({...t,enabled:true})}>Use {t.name.replaceAll('-',' ')} template</button>)}</div>}
   {draft&&owner&&<form className="rounded-xl border border-indigo-500/40 bg-zinc-900 p-4 space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{const body={name:draft.name,description:draft.description,instructions:draft.instructions,enabled:draft.enabled,...(draft.id?{revision:draft.revision}:{})};await(draft.id?api.patch(base+'/'+draft.id,body):api.post(base,body));setDraft(null);await load();setNotice('Skill saved.');});}}>
    <h4 className="font-medium">{draft.id?'Edit skill':'Create a skill'}</h4>
    <label className="block text-sm">Skill name<input className={input+' mt-1'} required maxLength={64} placeholder="marketing-review" pattern="[a-z0-9]+(-[a-z0-9]+)*" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value.toLowerCase().replace(/\s/g,'-')})}/></label>
    <label className="block text-sm">When should AI use this skill?<textarea className={input+' mt-1'} required rows={2} maxLength={1000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
    <label className="block text-sm">Skill instructions<textarea className={input+' mt-1 font-mono'} required rows={9} maxLength={15000} value={draft.instructions} onChange={e=>setDraft({...draft,instructions:e.target.value})}/></label>
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Enable for this company’s AI</label>
    <div className="flex gap-2"><button className={button+' bg-indigo-600'} disabled={busy}>Save skill</button><button type="button" className={button} disabled={busy} onClick={()=>setDraft(null)}>Cancel</button></div>
   </form>}
   {data.skills.map(skill=><article key={skill.id} className="rounded-xl border border-zinc-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><div className="min-w-0"><h4 className="font-medium break-words">{skill.name}</h4><p className="text-sm text-zinc-400 mt-1 whitespace-pre-wrap break-words">{skill.description}</p></div><span className={'text-xs '+(skill.enabled?'text-emerald-300':'text-zinc-500')}>{skill.enabled?'Enabled':'Disabled'}</span></div><details><summary className="text-sm text-zinc-400 cursor-pointer">Read instructions</summary><pre className="whitespace-pre-wrap break-words text-sm mt-3">{skill.instructions}</pre></details><div className="flex flex-wrap gap-2">{owner&&<><button className={button} disabled={busy} onClick={()=>setDraft({...skill})}>Edit {skill.name}</button><button className={button} disabled={busy} onClick={()=>act(async()=>{await api.patch(base+'/'+skill.id,{enabled:!skill.enabled,revision:skill.revision});await load();})}>{skill.enabled?'Disable':'Enable'} {skill.name}</button></>}<button className={button} disabled={busy} onClick={()=>act(()=>api.download(base+'/'+skill.id+'/export','SKILL.md'))}>Export SKILL.md</button>{owner&&<button className={button+' text-rose-300'} disabled={busy} onClick={()=>{if(confirm(`Delete the ${skill.name} skill from this company?`))act(async()=>{await api.del(base+'/'+skill.id,{revision:skill.revision});await load();});}}>Delete {skill.name}</button>}</div></article>)}
  </section>
 </div>;
}
