import React,{useEffect,useState} from 'react';
import {Github,Monitor,Terminal,Network,Mail,BrainCircuit,Plug,KeyRound,CreditCard,ArrowUpRight,Search,RefreshCw} from 'lucide-react';
import {api} from '../api.js';
import {settingsButton,settingsInput} from './SettingsShell.jsx';

export const connectorDefinitions=[
 ...['fal','higgsfield'].map(id=>({id,label:id==='fal'?'fal':'Higgsfield',icon:Plug,scope:'Account → Company → Project',category:'Images & video',description:'Generate images and videos using your own '+(id==='fal'?'fal':'Higgsfield')+' API account.',guide:'Save your provider key, approve a model and daily request limit, then enable generation for selected companies or projects.'})),
 {id:'claude',label:'Claude & Claude Code',icon:BrainCircuit,scope:'Account',category:'AI',description:'Use your Claude API key for Boardly agents, or connect your Claude Code client.',guide:'Connect your own API account and choose an available model. Claude Code subscriptions stay in your own coding client.'},
 {id:'kimi',label:'Kimi & Kimi Code',icon:BrainCircuit,scope:'Account',category:'AI',description:'Power Boardly agents with your Kimi API account.',guide:'Verify your API key and choose a model. Your Kimi Code or chat subscription is separate from API billing.'},
 {id:'local',label:'Local AI',icon:BrainCircuit,scope:'Account',category:'AI',description:'Run Boardly agents with Ollama, LM Studio or your own model server.',guide:'Connect your Tailscale network, choose the model server and its port, then select a model with tool calling and optional vision.'},
 {id:'onepassword',label:'1Password',icon:KeyRound,scope:'Account → Company → Project',category:'Passwords',description:'Fill approved account logins on ComputerUse desktops.',guide:'Connect a vault service account, approve login items and websites, then grant access to selected companies or projects.'},
 {id:'ai',label:'Codex, ChatGPT & OpenAI',icon:BrainCircuit,scope:'Account',category:'AI',description:'Power your agents with a ChatGPT connection or OpenAI API key.',guide:'Sign in to your own ChatGPT/Codex account or paste your OpenAI API key. Work in shared companies uses that company owner’s connection.'},
 {id:'github',label:'GitHub',icon:Github,scope:'Account → Company → Project',category:'Code',description:'Give Work agents access to a repository and branch.',guide:'Save an account token once. Choose a company repository; projects inherit it unless they have their own.'},
 {id:'computeruse',label:'ComputerUse',icon:Monitor,scope:'Account → Company → Project',category:'Computers',description:'Assign desktops for browser work and computer automation.',guide:'Connect your ComputerUse API key once. Assign computers per company, then inherit or override in each project.'},
 {id:'ssh',label:'SSH computers & servers',icon:Terminal,scope:'Account, Company or Project',category:'Computers',description:'Let permitted Work agents run commands on your machines.',guide:'Save an account connection for all your companies, or limit it to one company or project. Guided setup creates a dedicated key.'},
 {id:'tailscale',label:'Tailscale',icon:Network,scope:'Account',category:'Network',description:'Reach private computers from Boardly cloud.',guide:'Connect your network at account level, then add a device in SSH settings. Network access alone does not grant agent control.'},
 {id:'emails',label:'Company email',icon:Mail,scope:'Company → Projects',category:'Email',description:'Connect an IMAP inbox for messages and verification codes.',guide:'Add the mailbox in company settings. Explicitly enable agent access for that company’s projects. This connector reads email; it does not send campaigns.'},
 {id:'environment',label:'Environment & secrets',icon:KeyRound,scope:'Project',category:'Development',description:'Save the configuration and API secrets a project needs.',guide:'Store values in the project that uses them. These are separate from account AI keys and repository tokens.'},
 {id:'payments',label:'Agent purchase cards',icon:CreditCard,scope:'Project',category:'Payments',description:'Set project purchase limits and an authorized payment card.',guide:'Configure per project. These cards are for agent purchases and are separate from your Boardly subscription.'},
 {id:'mcp',label:'Boardly MCP',icon:Plug,scope:'Account → External client',category:'Developer tools',description:'Connect an external AI client to your Boardly workspace.',guide:'Create a revocable key for a client supporting Streamable HTTP and Bearer tokens. Currently available to the platform owner.'},
];
const saved=(yes,label='Configured')=>({configured:!!yes,label:yes?label:'Not connected'});
// Only read masked connection summaries. A saved key is not evidence that a
// provider or a remote device is online; the detail page performs explicit tests.
function statusRequest(id,scope,entityId){
 const base=scope==='company'?`/api/companies/${entityId}`:`/api/projects/${entityId}`;
 if(['fal','higgsfield'].includes(id))return [scope==='account'?'/api/account/media/'+id:base+'/media/'+id,d=>saved(d.saved&&(scope==='account'||d.allowed),scope==='account'?'API key saved':'Generation enabled')];
 if(['claude','kimi','local'].includes(id))return ['/api/account/ai-providers',d=>{const c=d.connections.find(p=>p.provider===id);return saved(c?.saved,c?.active?'Active for agents':'Connection saved');}];
 if(id==='onepassword')return [scope==='account'?'/api/account/onepassword':base+'/onepassword',d=>saved(scope==='account'?d.saved:d.saved&&(d.login_ids?.length||d.inherited_ids?.length),scope==='account'?'Vault connected':'Logins approved')];
 if(id==='ai')return ['/api/ai/settings',d=>saved(d.mode!=='none','AI configured')];
 if(id==='github')return scope==='account'?['/api/account/github',d=>saved(d.has_token,'Token saved')]:[base+'/github',d=>saved(d.effective,d.effective?.inherited?'Inherited from company':'Repository assigned')];
 if(id==='computeruse')return scope==='account'?['/api/account/computeruse',d=>saved(d.saved,'API key saved')]:[base+'/computeruse',d=>({configured:!!d.rental_ids?.length,label:d.rental_ids?.length?`${d.rental_ids.length} assigned${d.inherited?' · inherited':''}`:d.saved?'Choose computers':'Account connection needed'})];
 if(id==='ssh')return [scope==='account'?'/api/account/ssh':base+'/ssh',d=>{const n=(d.connections?.length||0)+(d.inherited?.length||0);return saved(n,`${n} saved connection${n===1?'':'s'}`);}];
 if(id==='tailscale')return ['/api/account/tailscale',d=>({configured:d.state==='Running',label:!d.configured?'Server setup needed':d.state==='Running'?'Network connected':'Not connected'})];
 if(id==='emails'&&scope==='company')return [base+'/emails',d=>saved(d.length,`${d.length} saved mailbox${d.length===1?'':'es'}`)];
 if(id==='environment'&&scope==='project')return [`/api/boards/${entityId}/environment`,d=>saved(d.length,`${d.length} saved variable${d.length===1?'':'s'}`)];
 if(id==='payments'&&scope==='project')return [`/api/boards/${entityId}/payments`,d=>saved(d.cards?.length,`${d.cards?.length||0} saved card${d.cards?.length===1?'':'s'}`)];
 if(id==='mcp')return ['/api/connections',d=>{const n=d.connections.filter(c=>c.scope==='mcp'&&!c.revoked_at&&new Date(c.expires_at)>new Date()).length;return saved(n,`${n} active key${n===1?'':'s'}`);}];
 return null;
}
export default function ConnectorCatalog({scope='account',entityId,allowed=()=>true,onSelect,onChooseScope,platformOwner=false}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[statuses,setStatuses]=useState({}),[revision,setRevision]=useState(0);
 const ids=connectorDefinitions.filter(c=>scope==='account'?true:scope==='company'?['github','computeruse','ssh','emails','onepassword','fal','higgsfield'].includes(c.id):['github','computeruse','ssh','environment','payments','onepassword','fal','higgsfield'].includes(c.id)).filter(c=>allowed(c.id));
 const signature=ids.map(c=>c.id).join(',');
 useEffect(()=>{let active=true;setStatuses({});Promise.allSettled(ids.map(async c=>{const elsewhere=scope==='account'&&['emails','environment','payments'].includes(c.id);if(elsewhere)return [c.id,{label:c.id==='emails'?'Choose a company':'Choose a project',elsewhere:true}];if(c.id==='mcp'&&!platformOwner)return[c.id,{label:'Platform owner only',restricted:true}];const request=statusRequest(c.id,scope,entityId);if(!request)return[c.id,{label:'Project configuration'}];try{const value=await api.get(request[0]);return[c.id,c.id==='ai'&&platformOwner&&value.mode==='none'?{configured:true,label:'Codex worker configured'}:request[1](value)];}catch(e){return[c.id,{label:e.status===403?'Permission required':'Status unavailable',error:e.message}];}})).then(results=>{if(active)setStatuses(Object.fromEntries(results.filter(r=>r.status==='fulfilled').map(r=>r.value)));});return()=>{active=false;};},[scope,entityId,signature,platformOwner,revision]);
 const visible=ids.filter(c=>(c.label+' '+c.category+' '+c.description+' '+c.guide).toLowerCase().includes(query.toLowerCase().trim())&&(filter==='all'||(filter==='configured'?statuses[c.id]?.configured:!statuses[c.id]?.configured)));
 return <div className="space-y-5">
  <div className="rounded-xl border border-indigo-500/25 bg-indigo-500/5 p-4"><h3 className="font-medium">Connect → assign → allow access</h3><p className="text-sm text-zinc-400 mt-2 leading-relaxed">{scope==='account'?'Start with a connection below. Company settings choose what is shared across that company. Project settings hold exceptions and project-only resources.':scope==='company'?'Resources saved here are available to this company’s projects. Each project can set its own repository or computer assignment.':'Inherited company resources stay available here. A project repository or computer assignment overrides that company setting.'} Member permissions and each connector’s agent controls still determine who can use it.</p></div>
  <div className="flex flex-wrap items-center gap-3"><label className="relative flex-1 min-w-48"><Search size={16} className="absolute left-3 top-3 text-zinc-500"/><input aria-label="Search connectors" placeholder="Search tools, devices, or what you want to do…" value={query} onChange={e=>setQuery(e.target.value)} className={settingsInput+' pl-9'}/></label><select aria-label="Filter connectors" className={settingsInput+' !w-auto'} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All connectors</option><option value="configured">Configured</option><option value="setup">Needs setup</option></select><button aria-label="Refresh connector status" className={settingsButton} onClick={()=>setRevision(n=>n+1)}><RefreshCw size={16}/></button></div>
  <div className="grid xl:grid-cols-2 gap-4">{visible.map(c=>{const state=statuses[c.id];return <article key={c.id} aria-label={c.label} className="rounded-xl border border-zinc-700/70 bg-zinc-900 p-5 flex flex-col gap-3"><div className="flex items-start justify-between gap-3"><span className="rounded-lg bg-zinc-800 p-2.5"><c.icon size={22} className="text-indigo-300"/></span><span className={'text-xs text-right '+(state?.configured?'text-emerald-300':state?.error?'text-amber-300':'text-zinc-400')}>{state?.label||'Checking…'}</span></div><div><h3 className="font-semibold">{c.label}</h3><p className="text-sm text-zinc-400 mt-2">{c.description}</p></div><p className="text-xs text-indigo-300">{c.scope}</p><p className="text-xs text-zinc-400 leading-relaxed flex-1">{c.guide}</p>{state?.error&&<p className="text-xs text-amber-300">{state.error}</p>}<button disabled={state?.restricted} className={settingsButton+' self-start'} onClick={()=>state?.elsewhere?onChooseScope?.(c.id):onSelect(c.id)}>{state?.restricted?'Not available':state?.elsewhere?state.label:state?.configured?'Manage connection':'Set up connection'}<ArrowUpRight size={15}/></button></article>;})}</div>
  {!visible.length&&<p className="text-sm text-zinc-400 py-6">No connectors match this search or filter.</p>}
 </div>;
}
