import React from 'react';
import {api} from '../api.js';
export const connectorHelp={
 ai:{steps:['Choose Sign in with ChatGPT if you want to use your ChatGPT account. Choose OpenAI API if you have an API key.','For sign-in, copy the short code and open the OpenAI page. Sign in there and approve the connection. For API, paste your key into the password box.','Pick the model you want to use and save or activate the connection. Your AI provider bills usage to your own account.'],check:'ChatGPT shows Connected after sign-in. Use Test ChatGPT connection for a small AI reply. For API, save the key and send a short message in a project chat; your provider may charge for that reply.',fix:'An expired sign-in code needs a new code. An API error usually means the key, billing balance or model access needs checking in your provider account.'},
 claude:{steps:['Open the Claude API dashboard linked below. Sign in and create an API key. A Claude chat subscription is separate.','Copy the key once. Paste it in the Claude API key box here and click Verify connection.','Choose a model from the list returned by Claude. Click Verify & save model, then Use for Boardly agents.'],check:'Verification lists your available models. It does not buy an AI reply.',fix:'No models or a rejected key? Check the API account, key permissions and billing with Claude.'},
 kimi:{steps:['Open the Kimi API dashboard linked below and create an API key.','Paste it into the Kimi API key box. Click Verify connection to load your models.','Choose a model, save it and click Use for Boardly agents.'],check:'Your model appears as the active connection after activation.',fix:'A Kimi chat or Code subscription is separate from API access. Check your API account if a key is rejected.'},
 local:{steps:['Start your model app, such as Ollama or LM Studio, on your own computer and load a model.','Connect that computer and Boardly to your Tailscale network. Choose the computer below and enter the port shown by your model app.','Click Verify connection. Choose a model that supports tools, save it and select Use for Boardly agents.'],check:'Boardly shows the models returned by your computer.',fix:'Keep the computer and model server running. Check Tailscale and the listening port if it cannot be reached.'},
 github:{steps:['Open GitHub and create a fine-grained access token for the repository you want Boardly to use.','Paste the token into your account GitHub connection. Give only the repository access the work needs.','Open Company settings → GitHub and choose the repository and branch. A project can use that choice or have its own.'],check:'Load the repository and branch lists. A saved token alone does not select a repository.',fix:'A missing repository can mean the token needs repository access or your GitHub organization must approve it.'},
 computeruse:{steps:['Open your ComputerUse account and create an API key with the desktop access you need.','Paste the key in Account settings → ComputerUse. Your available computers will appear.','Open Company settings → ComputerUse. Choose its computers and turn on agent control only when you want the AI to use them.'],check:'The computer list shows availability. Open the selected desktop to confirm it is the one you want.',fix:'A saved key does not mean a computer is online. Check the computer, network and ComputerUse account if it is missing.'},
 ssh:{steps:['Click Add SSH connection and follow Guided setup. Choose the computer or server you want to reach.','Boardly creates a special key. Copy the setup command and run it on that computer using an account you control.','Return here and test the connection. Choose where it is shared and enable agent access when ready.'],check:'The connection test must succeed before an agent can use the computer.',fix:'Check the address, username and SSH port. If the computer is private, connect its Tailscale network first.'},
 tailscale:{steps:['Open the connection link below and sign in to the Tailscale network that contains your computer.','Approve Boardly joining that network. Come back and refresh the device list.','Choose that computer in SSH, Local AI or another connector that needs it.'],check:'The network shows Connected and your device appears.',fix:'The device must be on the same network and allowed by its network access rules.'},
 onepassword:{steps:['Create a 1Password service account with access to a vault you want Boardly to use.','Paste its token here. Choose only the login items and websites the AI is allowed to use.','Open the company or project settings and grant those logins to the work that needs them.'],check:'Approved items appear by name. Passwords stay private.',fix:'If an item is missing, check the service account’s vault access and the website saved on the item.'},
 emails:{steps:['Choose the company that owns the inbox. Click Add email.','Enter the address, IMAP server, port and the password or app password from your email provider. An app password is a special password for this connection.','Test the inbox. Enable agent access if you want that company’s agents to read messages and sign-in codes.'],check:'The inbox test should succeed and show messages.',fix:'Check your provider’s IMAP settings and app-password requirements. This connection reads email; it does not send marketing campaigns.'},
 environment:{steps:['Open the project that needs the setting.','Add its name, such as SERVICE_API_KEY, and paste the value in the private value box.','Save it. Add only the settings that this project needs.'],check:'The setting name appears in the saved list; its value is hidden.',fix:'Names must match what your project expects. Account AI keys belong in AI settings instead.'},
 payments:{steps:['Open the project that is allowed to make purchases.','Add the payment details and set the spending limits for that project.','Review the saved permission and limits before asking an agent to buy something.'],check:'The masked card and limits appear in the project.',fix:'This is a card for project purchases. Your Boardly subscription is managed separately in Billing & user seats.'},
 fal:{steps:['Open your fal account and create an API key.','Save the key here, choose the model and options you want to allow, and set a daily request limit.','Enable it for the company or project that will create images or videos.'],check:'The key is saved first. A generation request is what tests the selected model, and the provider may charge for it.',fix:'Check the provider balance, model name, input options and the company’s permission if a job fails.'},
 higgsfield:{steps:['Open your Higgsfield API account and get the credentials requested in this form.','Save them here. Approve a model, its options and a daily request limit.','Enable the connection in the company or project that needs it.'],check:'Saving credentials does not create a paid video. A generation request verifies the model and may be billed by Higgsfield.',fix:'Check the API account balance, credentials and model options in Higgsfield.'},
 mcp:{steps:['Open Boardly MCP and create a key for the AI app you want to connect. This feature is currently available to the platform owner.','Copy the server address and key into that app’s MCP connection settings.','Ask the app to list your Boardly boards. Revoke the key here when you stop using the app.'],check:'The app can list your boards after connecting.',fix:'The AI app must support the listed connection method. A ComputerUse connection alone does not enable Boardly MCP.'},
};
export function downloadConnectorHelp(){const botHelp='## Discord bot\n\nOpen Company settings → Discord bot. Follow Create your bot, Paste the token, Choose a server and channel, and Send a test. Preview a project update before sending.\n\nOfficial guide: https://docs.discord.com/developers/quick-start/getting-started\n\n## Telegram bot\n\nOpen Company settings → Telegram bot. Open BotFather, send /newbot and follow its questions. Paste the new bot token in Boardly. Get the private bot link, open it in Telegram and press Start. Return to Boardly and check the chat, then send a test.\n\nOfficial guide: https://core.telegram.org/bots/features#botfather';const body='# Boardly connection guide\n\nAn API key or bot token is a private password for a connection. Paste it only in its private connection box.\n\n'+Object.entries(connectorHelp).map(([id,g])=>'## '+id+'\n\n'+g.steps.map((s,i)=>(i+1)+'. '+s).join('\n')+'\n\nHow to check: '+g.check+'\n\nIf it gets stuck: '+g.fix).join('\n\n')+'\n\n'+botHelp;return api.saveText(body,'Boardly-connection-guide.md');}
export default function ConnectorHelp({id}){const guide=connectorHelp[id];if(!guide)return null;return <details className="rounded-xl border border-indigo-500/30 bg-indigo-500/5 p-4"><summary className="text-sm font-medium cursor-pointer">Walk me through it, step by step</summary><ol className="list-decimal pl-5 mt-4 space-y-3 text-sm text-zinc-300">{guide.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="text-sm text-zinc-400 mt-4"><strong className="text-zinc-200">How to check: </strong>{guide.check}</p><p className="text-sm text-zinc-400 mt-3"><strong className="text-zinc-200">If it gets stuck: </strong>{guide.fix}</p></details>;}
