import BrandLogo from './BrandLogo.jsx';
import React,{useEffect,useRef,useState} from 'react';
import {api} from '../api.js';
import ChatGPTConnection from './ChatGPTConnection.jsx';
const button='rounded-lg border border-zinc-600 px-4 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const steps=['Welcome','Connect AI','Organize work','Use Boardly','Get started'];
export const lessons=[
 {title:'Companies, boards and projects',text:'A company keeps work for one business together. Boards group related work, such as Web hosting clients. Projects hold individual assignments, such as a client website.',items:['From Companies, choose New company and enter its name.','Open the company, choose New board, and name the group of work.','Open the board and choose New project. Add a clear description of the outcome you want.','Check existing companies and projects before creating another one. Unassigned boards keeps older work available.']},
 {title:'Tasks and checklists',text:'Open a project to see its task lists. A card represents one clear piece of work; its description, checklist, comments and files keep the context together.',items:['Add a card to To Do and explain the desired result. Open it to add checklist steps or a due date.','Use In Progress while someone is actively working. Move a task to Blocked when it needs input or access, and record the exact next action.','Move verified work to Done Awaiting Revisions when that list is available. Drag cards between lists as their status changes.']},
 {title:'Ask, Plan and Work',text:'Open Chat with AI in a company, board or project. Choose the scope that contains the information you want the AI to use.',items:['Ask answers questions about the saved work. Try: “What needs my attention in this project?”','Plan drafts a proposed approach. Try: “Plan the next three steps for this client.”','Work can update project tasks and files and use enabled connections. Give a clear outcome, then review its saved activity and result.','Use a separate conversation for a different topic. Independent projects can run concurrently; work in the same project may wait to avoid conflicting changes.','Expand the chat window when you need more space. If an assignment is blocked, read its next action, restore the missing access or answer the question, then resume the saved assignment.']},
 {title:'Audio briefings and replies',text:'Audio briefing sits beside Chat with AI in companies, boards and projects. It summarizes the saved work and what needs attention.',items:['Choose Audio briefing and start playback. You can also read the briefing on screen.','Type your reply, or use the microphone when your browser supports voice input and you grant microphone access.','Choose Send question to discuss the briefing, or Start work to turn your reply into an assignment. Review the resulting chat and activity.']},
 {title:'Files, folders and project links',text:'Files keeps the documents and deliverables for the current project together.',items:['Open Files and choose New folder to organize related material. Open a folder to work inside it.','Upload files, create nested folders and move files to the appropriate folder. Your account storage allowance applies.','Add useful project links and explain what they are for. Give the AI a specific file or task to use when requesting work.']},
 {title:'GitHub, SSH and other connections',text:'The profile menu opens Settings for your AI funding and Connectors for reusable connections. Project settings control what a project can use.',items:['Connect ChatGPT, approve the code on OpenAI’s website, then use Test ChatGPT connection. No API key is required for this option.','Save reusable GitHub and SSH connections in Profile menu → Connectors, then select and enable the appropriate connection in a company or project.','For SSH, test the connection and verify the server identity. Enable only the connections that project needs.','Project environment variables, email and other integrations have their own setup and permissions. AI can only perform actions supported by its runtime and enabled tools.']},
 {title:'Team access and account settings',text:'Owners can invite members and choose which companies or projects they can access. Shared work uses the sponsoring owner’s AI connection.',items:['Use Settings → Team & permissions in the relevant company or project to invite someone and select their role and scopes.','Viewers can read permitted work. Editors can change permitted work; sensitive integrations have separate permissions.','Use the account selector to switch between your own workspace and accounts shared with you. Your personal ChatGPT connection stays with your account.','Profile menu → Billing & usage shows plan allowances and billing availability. API billing is an optional alternative to ChatGPT; Boardly subscriptions and ChatGPT subscriptions are separate.']},
 {title:'Computer use and troubleshooting',text:'The Computer use panel manages desktops assigned to the project or inherited from its company.',items:['Connect ComputerUse from Companies home or Settings → ComputerUse, then assign computers on each company’s home. Projects inherit those assignments or set their own in Project settings → ComputerUse. Inventory and purchases are provided by the ComputerUse API.','If AI cannot reply, open Profile menu → Settings → AI & models and test your connection. Check ChatGPT usage limits or follow its sign-in instructions.','If a server or repository cannot be reached, test that saved connection and inspect the assignment activity before retrying an external change.','Use Boardly in your browser for the current cloud workspace. Desktop download and sync setup is separate; do not assume an older desktop installation is synchronized.']},
];
function downloadTutorial(){const body='# Boardly tutorial\n\nConnect your ChatGPT account in Profile menu → Settings → AI & models. No OpenAI API key is required when using ChatGPT. Your ChatGPT plan’s Codex access and limits apply.\n\n'+lessons.map(l=>'## '+l.title+'\n\n'+l.text+'\n\n'+l.items.map((t,i)=>`${i+1}. ${t}`).join('\n')).join('\n\n');return api.saveText(body,'Boardly-tutorial.md').catch(error=>window.alert(error.message));}
export default function GettingStarted({access,registerOpen}){
 const directTutorial=useRef(location.hash==='#/tutorial');
 const [open,setOpen]=useState(directTutorial.current),[step,setStep]=useState(directTutorial.current?3:0),[lesson,setLesson]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[tutorial,setTutorial]=useState(directTutorial.current);
 const dialog=useRef(null),heading=useRef(null),restoreFocus=useRef(null),loaded=useRef(false);
 async function load(){try{const r=await api.get('/api/onboarding');if(!directTutorial.current){setStep(r.step||0);if(['new','started'].includes(r.status))setOpen(true);}setError('');loaded.current=true;}catch(e){setError(e.message);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{registerOpen(()=>{setTutorial(true);setStep(3);setOpen(true);});return()=>registerOpen(null);},[registerOpen]);
 useEffect(()=>{if(!open)return;restoreFocus.current=document.activeElement;heading.current?.focus();const handler=e=>{if(e.key==='Tab'){const elements=[...dialog.current.querySelectorAll('button:not([disabled]),a[href],input,select,summary')].filter(x=>x.getClientRects().length);if(!elements.length)return;const first=elements[0],last=elements.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===heading.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);return()=>{document.removeEventListener('keydown',handler);restoreFocus.current?.focus?.();};},[open]);
 useEffect(()=>{if(open)heading.current?.focus();},[step,open]);
 async function save(next,status='started',close=false){setBusy(true);setError('');try{await api.put('/api/onboarding',{step:next,status});setStep(next);if(close)setOpen(false);}catch(e){setError(e.message);}finally{setBusy(false);}}
 function close(){if(tutorial){setOpen(false);if(location.hash==='#/tutorial')location.hash='#/';return;}save(step,'skipped',true);}
 if(!open)return error&&!loaded.current?<div role="status" className="px-5 py-2 text-sm text-amber-200">Your welcome guide could not load. <button className="underline" onClick={load}>Retry setup guide</button></div>:null;
 return <div className="fixed inset-0 z-[80] bg-black/75 p-2 sm:p-5 flex items-center justify-center"><section ref={dialog} role="dialog" aria-modal="true" aria-label={tutorial?'Boardly tutorial':'Welcome to Boardly'} className="bg-zinc-900 border border-zinc-700 rounded-2xl w-full max-w-4xl max-h-[94dvh] flex flex-col overflow-hidden">
 <header className="p-4 sm:p-6 border-b border-zinc-700 flex items-start justify-between gap-3"><div><BrandLogo size={28} className="mb-3 text-base"/><p className="text-xs text-indigo-300 mb-1">{tutorial?'YOUR BOARDLY GUIDE':`GETTING STARTED · ${step+1} OF ${steps.length}`}</p><h2 ref={heading} tabIndex={-1} className="text-xl sm:text-2xl font-semibold outline-none">{tutorial?'How to use Boardly':step===0?'Welcome to Boardly':steps[step]}</h2></div><button disabled={busy} className={button} aria-label="Close tutorial" onClick={close}>✕</button></header>
 <div className="p-4 sm:p-6 space-y-5 overflow-y-auto min-h-0">
 {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}
 {!tutorial&&<nav aria-label="Setup steps" className="flex gap-2 overflow-x-auto pb-1 sm:flex-wrap">{steps.map((s,i)=><button key={s} disabled={busy} onClick={()=>save(i)} aria-current={step===i?'step':undefined} className={'shrink-0 text-xs rounded-full border px-3 py-1.5 '+(step===i?'border-indigo-400 bg-indigo-500/20':'border-zinc-700 text-zinc-400')}>{i+1}. {s}</button>)}</nav>}
 {step===0&&<><p className="text-zinc-300">Keep each company’s projects, conversations and next steps together. This short guide helps you connect AI and start your first project.</p><div className="grid sm:grid-cols-3 gap-3">{[['1','Connect ChatGPT','Use the account you already have.'],['2','Organize your work','Create a company, board and project.'],['3','Ask, listen or start work','Choose how you want AI to help.']].map(([n,t,d])=><article key={n} className="rounded-xl border border-zinc-700 p-4"><span className="text-indigo-300 text-sm">{n}</span><h3 className="font-semibold mt-2">{t}</h3><p className="text-sm text-zinc-400 mt-2">{d}</p></article>)}</div><p className="text-sm text-zinc-400">You can leave this guide at any time and reopen it from the profile menu → Help & tutorial.</p></>}
 {step===1&&<>{!access.workspaceOwner&&<p className="text-sm text-indigo-200">You are viewing a shared workspace. Its owner supplies AI access for shared projects. A connection you add here applies to your own companies and projects.</p>}<ChatGPTConnection ownerSubscription={access.plan==='owner'}/></>}
 {step===2&&<><p className="text-zinc-300">Choose a structure that makes sense for your business. For example:</p><div className="rounded-xl bg-zinc-950 border border-zinc-700 p-4 space-y-2 text-sm"><p>Company: Advanced Marketing Limited</p><p className="pl-4">↳ Board: Web hosting clients</p><p className="pl-8">↳ Project: Client website</p><p className="pl-12 text-zinc-400">↳ Tasks: Review hosting, update pages, test launch</p></div><ol className="list-decimal pl-5 space-y-2 text-sm text-zinc-300">{lessons[0].items.map(t=><li key={t}>{t}</li>)}</ol>{!access.workspaceOwner&&<p className="text-sm text-amber-200">In this shared workspace, open a project shared with you. Ask its owner if you need a new company, board or project.</p>}</>}
 {step===3&&<div className="grid sm:grid-cols-[190px_1fr] gap-5"><nav aria-label="Tutorial lessons" className="flex sm:flex-col gap-2 overflow-x-auto sm:overflow-visible pb-2">{lessons.map((l,i)=><button key={l.title} aria-current={lesson===i?'page':undefined} onClick={()=>setLesson(i)} className={'text-left shrink-0 sm:shrink text-sm rounded-lg px-3 py-2 border '+(lesson===i?'border-indigo-400 bg-indigo-500/15':'border-zinc-700 text-zinc-400')}>{l.title}</button>)}</nav><article className="min-w-0"><h3 className="text-lg font-semibold">{lessons[lesson].title}</h3><p className="mt-3 text-sm text-zinc-300">{lessons[lesson].text}</p><ol className="mt-4 list-decimal pl-5 space-y-3 text-sm text-zinc-300">{lessons[lesson].items.map(t=><li key={t}>{t}</li>)}</ol><div className="flex justify-between mt-6 gap-3"><button className={button} disabled={lesson===0} onClick={()=>setLesson(lesson-1)}>Previous lesson</button><button className={button} disabled={lesson===lessons.length-1} onClick={()=>setLesson(lesson+1)}>Next lesson</button></div></article></div>}
 {step===4&&<><h3 className="text-lg font-semibold">Try your first project conversation</h3><p className="text-sm text-zinc-300">Open a project and choose Chat with AI → Ask. Start with:</p><blockquote className="rounded-xl border border-indigo-500/40 p-4 text-indigo-100">“Summarize this project, tell me what needs doing next, and point out anything you need from me.”</blockquote><p className="text-sm text-zinc-300">Use Plan to discuss an approach. Choose Work when you are ready for the AI to make changes. Audio briefing lets you listen and reply instead.</p><p className="text-sm text-zinc-400">Help & tutorial stays available in your profile menu. Finishing this guide does not activate a paid plan or mark any project tasks complete.</p></>}
 </div><footer className="shrink-0 flex flex-wrap items-center justify-between gap-3 border-t border-zinc-700 p-4"><div className="flex flex-wrap gap-2"><button className={button} onClick={downloadTutorial}>Download tutorial</button>{tutorial?<button className={button} onClick={()=>{setTutorial(false);save(0);}}>Replay setup guide</button>:<button disabled={busy} className="text-sm text-zinc-400 px-2" onClick={close}>Set up later</button>}</div><div className="flex gap-2">{!tutorial&&step>0&&<button disabled={busy} className={button} onClick={()=>save(step-1)}>Back</button>}{tutorial?<button className={button+' bg-indigo-600'} onClick={close}>Close guide</button>:<button disabled={busy} className={button+' bg-indigo-600'} onClick={()=>step===4?save(step,'completed',true):save(step+1)}>{step===4?'Finish guide':'Next'}</button>}</div></footer>
 </section></div>;
}
