import React,{useEffect,useRef,useState} from 'react';
import {Github,CheckCircle2,ExternalLink,LockKeyhole} from 'lucide-react';
import {api} from '../api.js';
const button='rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const input='mt-1 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm';
export default function GithubConnection({kind,id}){
 const [state,setState]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const base=`/api/${kind}/${id}/github`,generation=useRef(0),writing=useRef(false);
 const load=async()=>{const seq=++generation.current,value=await api.get(base);if(seq===generation.current)setState(value);};
 useEffect(()=>{setState(null);setForm(null);setError('');setNotice('');let active=true,pending=false;
  const refresh=async()=>{if(!active||pending||writing.current)return;pending=true;try{await load();}catch(e){if(active)setError(e.message);}finally{pending=false;}};
  const visible=()=>{if(document.visibilityState==='visible')refresh();};refresh();const timer=setInterval(visible,3000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',visible);
  return()=>{active=false;generation.current++;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',visible);};},[base]);
 async function act(fn){writing.current=true;generation.current++;setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e.message);}finally{writing.current=false;setBusy(false);}}
 const connection=state?.connection,effective=state?.effective;
 const openAccount=()=>window.dispatchEvent(new CustomEvent('boardly-account',{detail:{section:'github'}}));
 const accountPrompt=<p className="text-sm text-zinc-400">{state?.account_has_token?'Uses the saved account PAT.':state?.can_manage_account?'Add your account PAT to activate this repository.':'Ask the company owner to add their account PAT.'}{state?.can_manage_account&&<button type="button" className="ml-2 text-indigo-300 underline" onClick={openAccount}>{state?.account_has_token?'Manage account GitHub PAT':'Set up account GitHub PAT'}</button>}</p>;
 const edit=()=>setForm({repository:connection?.repository||'',branch:connection?.branch||'main',token:'',credential_source:connection?.credential_source||(state?.can_manage_account?'account':'scoped'),allow_agent:connection?!!connection.allow_agent:true});
 return <section className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-semibold flex items-center gap-2"><Github size={20}/>GitHub repository</h3><p className="text-sm text-zinc-400 mt-2 max-w-xl">{kind==='companies'?'Projects inherit this repository unless they have their own connection.':'Connect this project to its repository, or inherit the company connection.'}</p></div>{!form&&<button disabled={!state||busy} className={button} onClick={edit}>{connection?'Edit connection':effective?'Use a project repository':'Connect GitHub'}</button>}</div>
  {state?.scope&&<p className="rounded-lg border border-zinc-800 p-3 text-xs text-zinc-400">{kind==='companies'?`Save to company: ${state.scope.company_name}`:`Save to project: ${state.scope.company_name||'Unassigned'} / ${state.scope.parent_board_name} / ${state.scope.project_name}`}<span className="block mt-1">{kind==='companies'?'Saved connections are inherited by this company’s projects and their chats.':'Saved connections are shared by every project and task chat in this project.'} The token stays saved when you close a chat or reload.</span></p>}
  {error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-300">{notice}</p>}
  {!state&&!error&&<p className="text-sm text-zinc-400">Loading GitHub connection…</p>}
  {form&&<form className="p-5 rounded-xl border border-indigo-500/40 bg-zinc-900 space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{await api.put(base,form);setForm(null);setNotice('GitHub connection saved for all chats in this scope. Test access to verify the repository and branch.');});}}>
   <label className="block text-sm text-zinc-300">Repository URL<input required readOnly={!state?.can_manage_account&&form.credential_source==='account'} className={input} placeholder="https://github.com/your-company/your-repo" value={form.repository} onChange={e=>setForm({...form,repository:e.target.value})}/></label>
   <label className="block text-sm text-zinc-300">Target branch<input required className={input} placeholder="main" value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/></label>
   <label className="block text-sm text-zinc-300">GitHub credential<select aria-label="GitHub credential" className={input} value={form.credential_source} onChange={e=>setForm({...form,credential_source:e.target.value,token:''})}><option value="account" disabled={!state?.can_manage_account&&connection?.credential_source!=='account'}>Account PAT</option><option value="scoped">Separate repository token</option></select></label>
   {form.credential_source==='account'?accountPrompt:<><label className="block text-sm text-zinc-300">GitHub access token<input required={connection?.credential_source!=='scoped'||(!state?.can_manage_account&&form.repository!==connection?.repository)} className={input} autoComplete="new-password" spellCheck={false} type="password" placeholder={connection?.credential_source==='scoped'?'Leave blank to keep the saved token':'Paste your GitHub personal access token'} value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/></label>
   <p className="text-sm text-zinc-400">Choose a token with access to this repository and Contents read/write permission. Your organization may require approval. Protected branches still enforce their rules.</p></>}
   <label className="flex items-start gap-3 text-sm"><input className="mt-1 accent-indigo-500" type="checkbox" checked={form.allow_agent} onChange={e=>setForm({...form,allow_agent:e.target.checked})}/><span>Allow project Work agents to read and push to this repository<span className="block text-zinc-400 mt-1">Ask and Plan cannot change the repository. Deployment requires the tested commit to be on the selected GitHub branch.</span></span></label>
   <div className="flex gap-3"><button disabled={busy} className={button+' bg-indigo-600 border-indigo-500'}>{busy?'Saving…':'Save GitHub connection'}</button><button type="button" disabled={busy} className={button} onClick={()=>setForm(null)}>Cancel</button></div>
  </form>}
  {effective&&!form&&<div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5 space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><a className="font-semibold text-indigo-300 inline-flex items-center gap-2" href={'https://github.com/'+effective.repository} target="_blank" rel="noreferrer">{effective.repository}<ExternalLink size={15}/></a><p className="text-sm text-zinc-400 mt-1">Branch: <span className="font-mono text-zinc-200">{effective.branch}</span>{effective.inherited?' · Inherited from company':''}</p></div><span className={'text-sm '+(effective.allow_agent?'text-emerald-300':'text-zinc-400')}>{!effective.credential_ready?'Account PAT needed':effective.allow_agent?'Work agents enabled':'Agent access paused'}</span></div>
   <p className="text-sm text-zinc-400 flex items-center gap-2"><LockKeyhole size={16}/>{effective.credential_source==='account'?'Uses your account GitHub PAT.':'Separate repository token saved with encryption.'} It is never shown to agents.</p>
   {effective.credential_source==='account'&&accountPrompt}
   {effective.last_commit_sha&&<p className="text-sm text-zinc-400">Last pushed commit: <a className="text-indigo-300 font-mono" href={'https://github.com/'+effective.repository+'/commit/'+effective.last_commit_sha} target="_blank" rel="noreferrer">{effective.last_commit_sha.slice(0,10)}</a></p>}
   <div className="flex flex-wrap items-center gap-3"><button disabled={busy||!effective.credential_ready} className={button} onClick={()=>act(async()=>{const result=await api.post(base+'/test',{});setNotice(`Connected to ${result.repository} / ${result.branch} at ${result.sha.slice(0,8)}. ${result.can_push===false?'This token has read-only access.':result.can_push===true?'Repository write access reported; branch rules still apply.':'Read access verified. Write permission is checked when pushing.'}`);})}>{busy?'Checking…':'Test connection'}</button>{effective.tested_at&&<span className="text-xs text-zinc-400 flex items-center gap-1"><CheckCircle2 size={14}/>Last verified {new Date(effective.tested_at).toLocaleString()}</span>}</div>
   {connection&&<div className="flex flex-wrap gap-4"><button disabled={busy} className="text-sm text-zinc-400 hover:text-indigo-300" onClick={()=>act(()=>api.put(base,{allow_agent:!connection.allow_agent}))}>{connection.allow_agent?'Pause agent access':'Enable agent access'}</button><button disabled={busy} className="text-sm text-zinc-400 hover:text-rose-300" onClick={()=>{if(window.confirm(kind==='projects'?'Remove this project connection? The company connection, if present, will apply again.':'Remove this company connection? Projects with their own connections are unaffected.'))act(()=>api.del(base));}}>{kind==='projects'?'Remove project connection':'Remove connection'}</button></div>}
  </div>}
  {state&&!effective&&!form&&<div className="rounded-xl border border-dashed border-zinc-700 p-6 text-sm text-zinc-400">Connect a GitHub repository so Work agents can read the source, save verified changes and check the release commit before deployment.</div>}
  <div className="rounded-xl border border-zinc-800 p-5"><h4 className="font-medium text-sm">Read → verify → push → deploy</h4><p className="text-sm text-zinc-400 mt-2">Agents check the repository before working. Changes are committed without force-pushing. Boardly's GitHub deployment step checks that the tested commit is the current remote branch before running your deployment command through an enabled SSH connection.</p></div>
 </section>;
}
