import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton,settingsInput} from './SettingsShell.jsx';
const roles={pull:'Read',triage:'Triage',push:'Write',maintain:'Maintain',admin:'Admin'};
export default function GithubAccess(){
 const [form,setForm]=useState({repository:'',username:'',role:'pull'}),[reviews,setReviews]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const base='/api/account/github/access';
 const load=()=>api.get(base).then(r=>setReviews(r.reviews));
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function act(fn){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section aria-label="GitHub invitations" className="border-t border-zinc-700 pt-5 space-y-4"><h3 className="font-semibold">Repository invitations & access</h3><p className="text-sm text-zinc-400">Prepare an invitation or role change, then confirm its exact recipient and permission. Your GitHub token needs Administration write access. Voice and agents can prepare a review; only you can approve it here.</p>{error&&<p role="alert" className="text-rose-300">{error}</p>}<form className="space-y-3" onSubmit={e=>{e.preventDefault();act(()=>api.post(base+'/preview',form));}}><label className="block text-sm">Repository<input required value={form.repository} placeholder="owner/repository" onChange={e=>setForm({...form,repository:e.target.value})} className={settingsInput}/></label><label className="block text-sm">GitHub username<input required value={form.username} onChange={e=>setForm({...form,username:e.target.value})} className={settingsInput}/></label><label className="block text-sm">Permission<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className={settingsInput}>{Object.entries(roles).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><button disabled={busy} className={settingsButton}>Review access change</button></form>{reviews.map(r=><article key={r.id} className="rounded-xl border border-zinc-700 p-4 space-y-3"><h4 className="font-semibold break-all">{r.username} → {r.repository}</h4><p className="text-sm">Current: {r.current_role||'No direct access'} · Requested: {roles[r.role]}</p><p className="text-sm text-zinc-400">{r.result?.status==='invitation_pending'?'Invitation sent · awaiting recipient acceptance':r.result?.status==='access_updated'?'Access updated':r.status==='needs_review'?'Outcome uncertain · check GitHub before retrying':r.status==='pending'?'Awaiting your confirmation · expires after 10 minutes':r.status}</p>{r.status==='pending'&&Date.now()-r.created_at<600000&&<button disabled={busy} className={settingsButton} onClick={()=>act(()=>api.post(base+'/'+r.id+'/confirm',{confirmed:true}))}>Confirm {roles[r.role]} access for {r.username}</button>}</article>)}</section>;
}
