import React, {useCallback, useEffect, useRef, useState} from 'react';
import {Cpu, Workflow, ListOrdered, Plus, RefreshCw, Settings2, ArrowDown, ArrowUp, X, Play, Pause, Download, Check, AlertCircle, Image, Film, MessageSquare, ChevronRight, Eye, Mail, Send, Pencil} from 'lucide-react';
import {api} from '../api.js';
import {accountSettings} from './SettingsShell.jsx';
import './gpu-workflows.css';

const base = '/api/gpu';
const notify = () => window.dispatchEvent(new Event('boardly-gpu-change'));
const labels = {queued:'Queued',waiting:'Reconnecting',running:'Running',submitted:'In GPU queue',completed:'Completed',published:'Published',failed:'Failed',blocked:'Needs attention',paused:'Paused',cancelled:'Cancelled',submitting:'Submitting'};
const icon = {prompt:MessageSquare,image:Image,video:Film,email:Mail,social:Send,action:Workflow};
const kindLabel={prompt:'AI prompt',image:'Create image',video:'Create video',email:'Email output',social:'Post to social media',action:'Custom output action'};
const mediaKind=kind=>['image','video'].includes(kind);
const actionKind=kind=>['email','social','action'].includes(kind);
const date = value => value ? new Date(value).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}) : 'Not checked';
const outputUrl = (worker, port, file) => `${base}/workers/${worker}/output?${new URLSearchParams({port,filename:file.filename,subfolder:file.subfolder||'',type:file.type||'output'})}`;
function Badge({status}) {return <span className={'gpu-badge gpu-state-'+status}>{labels[status]||status}</span>;}
function Field({label,children,hint}) {const id=React.useId();return <div className="gpu-field"><label htmlFor={id}>{label}</label>{React.cloneElement(children,{id,'aria-describedby':hint?id+'-hint':undefined})}{hint&&<small id={id+'-hint'}>{hint}</small>}</div>;}
function ErrorBox({error}) {return error?<div role="alert" className="gpu-error"><AlertCircle size={18} aria-hidden="true"/>{error}</div>:null;}

export function GpuWorkersSettings() {
  const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[form,setForm]=useState({name:'',ssh_id:'',ports:'8188',manifest_dir:''});
  const [template,setTemplate]=useState({name:'',kind:'image',worker_id:'',port:'8188',graph:''}),[message,setMessage]=useState('');
  const reload=useCallback(async()=>{const d=await api.get(base+'/workers');setData(d);},[]);
  useEffect(()=>{reload().catch(e=>setError(e.message));},[reload]);
  const act=async(key,fn)=>{setBusy(key);setError('');setMessage('');try{await fn();await reload();notify();}catch(e){setError(e.message);}finally{setBusy('');}};
  return <div className="gpu-ui gpu-settings">
    <ErrorBox error={error}/>{message&&<p className="gpu-success" role="status"><Check size={16} aria-hidden="true"/>{message}</p>}
    {!data?<p role="status">Loading your GPU workers…</p>:<>
      <div className="gpu-note"><Cpu size={20} aria-hidden="true"/><p>Add a computer with an NVIDIA GPU and ComfyUI. GPU Workflows appears in your navigation after the first worker connects.</p></div>
      {data.workers.map(w=><section className="gpu-panel" key={w.id}><div className="gpu-row"><div><h3>{w.name}</h3><p>{w.snapshot?.gpus?.find(g=>g.uuid===w.gpu_uuid)?.name||'NVIDIA GPU'}</p></div><Badge status={w.error?'blocked':'completed'}/></div><p className="gpu-muted">Checked {date(w.observed_at)} · ComfyUI ports {w.config.ports.join(', ')}</p>{w.error&&<ErrorBox error={w.error}/>}<div className="gpu-actions"><button disabled={!!busy} onClick={()=>act(w.id,()=>api.post(`${base}/workers/${w.id}/refresh`,{}))}><RefreshCw size={16}/>{busy===w.id?'Checking…':'Test connection'}</button><button disabled={!!busy} onClick={()=>act(w.id,()=>api.del(`${base}/workers/${w.id}`))}>Remove worker</button></div></section>)}
      <form className="gpu-panel gpu-stack" onSubmit={e=>{e.preventDefault();act('add',async()=>{await api.post(base+'/workers',{...form,ports:form.ports.split(',').map(p=>Number(p.trim()))});setForm({...form,name:''});setMessage('Worker connected. GPU Workflows is ready.');});}}>
        <h3>Add GPU worker</h3><div className="gpu-form-grid"><Field label="Worker name"><input required maxLength={80} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Studio RTX 3090"/></Field><Field label="Computer connection"><select required value={form.ssh_id} onChange={e=>setForm({...form,ssh_id:e.target.value})}><option value="">Choose a saved computer</option>{data.connections.map(c=><option key={c.id} value={c.id} disabled={!c.allow_agent}>{c.label}{!c.allow_agent?' (enable Work access first)':''}</option>)}</select></Field></div>
        <button type="button" className="gpu-link" onClick={()=>accountSettings('ssh')}>Add or manage computer connections <ChevronRight size={15}/></button>
        <details><summary>Connection options</summary><div className="gpu-stack gpu-top"><Field label="ComfyUI ports" hint="Comma separated; list every ComfyUI engine sharing this GPU."><input value={form.ports} onChange={e=>setForm({...form,ports:e.target.value})}/></Field><Field label="Producer manifest folder (optional)" hint="For an existing batch producer, show jobs waiting outside ComfyUI."><input value={form.manifest_dir} onChange={e=>setForm({...form,manifest_dir:e.target.value})} placeholder="/home/you/Exports/Continuous"/></Field></div></details>
        <button className="gpu-primary" disabled={!!busy||!form.ssh_id}>{busy==='add'?'Detecting GPU and testing ComfyUI…':'Connect GPU worker'}</button>
      </form>
      {data.workers.length>0&&<><a className="gpu-primary gpu-button" href="#/gpu-workflows">Open GPU Workflows <ChevronRight size={16}/></a><section className="gpu-panel gpu-stack"><h3>Generation templates</h3><p>Templates use the models and settings installed on each GPU. Your workflow prompts fill in their text inputs.</p>{data.templates.map(t=><div className="gpu-row gpu-template" key={t.id}><span>{t.name}</span><span className="gpu-muted">{t.kind} · {data.workers.find(w=>w.id===t.worker_id)?.name}</span></div>)}
        <details><summary>Add a generation template</summary><form className="gpu-stack gpu-top" onSubmit={e=>{e.preventDefault();act('template',async()=>{let graph;try{graph=JSON.parse(template.graph);}catch{throw Error('Paste valid ComfyUI API workflow JSON.');}await api.post(base+'/templates',{...template,port:Number(template.port),graph});setTemplate({...template,name:'',graph:''});setMessage('Template saved. It is available in your workflow builder.');});}}>
          <Field label="Template name"><input required value={template.name} onChange={e=>setTemplate({...template,name:e.target.value})} placeholder="FLUX photo · 512 px"/></Field><div className="gpu-form-grid"><Field label="GPU worker"><select required value={template.worker_id} onChange={e=>setTemplate({...template,worker_id:e.target.value,port:String(data.workers.find(w=>w.id===e.target.value)?.config.ports[0]||8188)})}><option value="">Select worker</option>{data.workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="Creates"><select value={template.kind} onChange={e=>setTemplate({...template,kind:e.target.value})}><option value="image">Image</option><option value="video">Video</option></select></Field></div><Field label="ComfyUI port"><select value={template.port} onChange={e=>setTemplate({...template,port:e.target.value})}>{(data.workers.find(w=>w.id===template.worker_id)?.config.ports||[8188]).map(p=><option key={p}>{p}</option>)}</select></Field>
          <Field label="ComfyUI API workflow" hint={'Export API format from ComfyUI. Use {{prompt}} in the positive text input, {{seed}} for a fresh seed and {{run_id}} in the output prefix. {{previous_file}} uses a preceding image on the same worker and port.'}><textarea required rows={9} value={template.graph} onChange={e=>setTemplate({...template,graph:e.target.value})}/></Field><button className="gpu-primary" disabled={!!busy}>{busy==='template'?'Saving…':'Save template'}</button>
        </form></details></section></>}
    </>}
  </div>;
}

function WorkerCard({worker,onAdd}) {
  const gpu=worker.snapshot?.gpus?.find(g=>g.uuid===worker.gpu_uuid),stale=!!worker.error||!worker.observed_at||Date.now()-worker.observed_at>60000;
  const memory=gpu?.memory_total?Math.round(gpu.memory_used/gpu.memory_total*100):null;
  const running=worker.snapshot?.jobs?.filter(j=>j.status==='running').length||0;
  return <article className="gpu-panel gpu-worker"><div className="gpu-row"><span className="gpu-chip"><Cpu size={20} aria-hidden="true"/></span><span className={'gpu-connection '+(stale?'gpu-stale':'')}>{stale?'Connection needs attention':running?'Rendering':'Connected'}</span></div><h2>{worker.name}</h2><p>{gpu?.name||'GPU details unavailable'}</p><div className="gpu-telemetry"><div><strong>{gpu?.utilization??'—'}<small>%</small></strong><span>GPU use{stale?' · last reading':''}</span></div><div><strong>{gpu?.temperature??'—'}<small>°C</small></strong><span>Temperature</span></div></div><div className="gpu-row gpu-muted"><span>GPU memory</span><span>{gpu?.memory_used!=null?(gpu.memory_used/1024).toFixed(1):'—'} / {gpu?.memory_total?(gpu.memory_total/1024).toFixed(1):'—'} GB</span></div><div className="gpu-meter" role="meter" aria-label={worker.name+' memory usage'} aria-valuemin={0} aria-valuemax={100} aria-valuenow={memory??0}><span style={{width:(memory??0)+'%'}}/></div><div className="gpu-row"><p className="gpu-small">Updated {date(worker.observed_at)}{stale?' · readings may be out of date':''}</p><button onClick={()=>onAdd(worker)} aria-label={'Add job to '+worker.name}><Plus size={15}/>Add job</button></div>{worker.error&&<p className="gpu-warn">{worker.error}</p>}{worker.snapshot?.warnings?.map(w=><p className="gpu-warn" key={w}>{w}</p>)}</article>;
}

function OutputViewer({file,url,onClose}) {
  const dialog=useRef(null),[source,setSource]=useState(''),[error,setError]=useState('');
  const name=file.filename||file.name;
  useEffect(()=>{const controller=new AbortController();let object;dialog.current?.showModal();api.blob(url,controller.signal).then(blob=>{if(controller.signal.aborted)return;object=URL.createObjectURL(blob);setSource(object);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>{controller.abort();if(object)URL.revokeObjectURL(object);};},[url]);
  return <dialog ref={dialog} className="gpu-viewer gpu-ui" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===dialog.current)onClose();}}><div className="gpu-viewer-content"><div className="gpu-row"><h2>{name}</h2><button onClick={onClose} aria-label="Close output preview"><X size={20}/></button></div><ErrorBox error={error}/>{!source&&!error&&<p role="status">Loading output from your GPU…</p>}{source&&(/\.(mp4|webm|mov)$/i.test(name)?<video controls playsInline preload="metadata" src={source}/>:/\.(mp3|wav)$/i.test(name)?<audio controls src={source}/>:<img src={source} alt={name}/>)}{source&&<a className="gpu-button" href={source} download={name}><Download size={16}/>Download file</a>}</div></dialog>;
}

function Outputs({files,worker,port,onError}) {
  const [busy,setBusy]=useState(''),[view,setView]=useState(null);
  return files?.length?<div className="gpu-output-files"><h3>Output files</h3>{files.map((file,i)=>{const name=file.filename||file.name,url=file.url||outputUrl(worker,port,file);return <div key={i} className="gpu-output-file"><button className="gpu-output-open" onClick={()=>setView({file,url})}><Eye size={18}/><span>{name}<small>Click to view {/\.(mp4|webm|mov)$/i.test(name)?'video':'output'}</small></span></button><button disabled={!!busy} aria-label={'Download '+name} onClick={async()=>{setBusy(name);try{await api.download(url,name);}catch(e){onError(e.message);}finally{setBusy('');}}}><Download size={16}/>{busy===name?'Loading…':'Download'}</button></div>;})}{view&&<OutputViewer {...view} onClose={()=>setView(null)}/>}</div>:null;
}

function JobPrompts({job,onSaved}) {
  const [data,setData]=useState(null),[values,setValues]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const url=`${base}/workers/${job.worker_id}/jobs/${job.id}`;
  useEffect(()=>{let live=true;setData(null);api.get(url).then(d=>{if(live){setData(d);setValues(Object.fromEntries(d.fields.map(f=>[f.key,f.value])));}}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[url]);
  return <form className="gpu-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const d=await api.patch(url,{revision:data.revision,changes:values});setData(d);setMessage('Queued prompt updated.');onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}}><h3>Job prompts</h3><ErrorBox error={error}/>{!data&&!error&&<p>Loading saved prompts…</p>}{data?.fields.map(f=><Field key={f.key} label={f.label}><textarea rows={f.value.length>500?7:3} readOnly={!data.editable} value={values[f.key]||''} onChange={e=>{setValues({...values,[f.key]:e.target.value});setMessage('');}}/></Field>)}{data?.editable?<button className="gpu-primary" disabled={busy}>{busy?'Saving…':'Save queued prompt'}</button>:data&&<p className="gpu-small">{data.reason}</p>}{message&&<p role="status" className="gpu-success">{message}</p>}</form>;
}

function StepPrompt({run,step,index,onSaved}) {
  const [editing,setEditing]=useState(false),[value,setValue]=useState(step.prompt),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const editable=!['completed','cancelled'].includes(run.status)&&index>=run.step_index&&!step.submitted&&!step.action_id&&['queued','waiting'].includes(step.status);
  return <div className="gpu-stack"><p className="gpu-pre">{step.resolved_prompt||step.prompt}</p>{editable&&!editing&&<button onClick={()=>{setValue(step.prompt);setEditing(true);}}><Pencil size={14}/>Edit queued prompt</button>}{editing&&<form className="gpu-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api.patch(`${base}/runs/${run.id}/steps/${index}`,{prompt:value,previous_prompt:step.prompt});setEditing(false);onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}}}><Field label={'Edit step '+(index+1)+' prompt'}><textarea rows={4} value={value} onChange={e=>setValue(e.target.value)}/></Field><ErrorBox error={error}/><div className="gpu-actions"><button disabled={busy} className="gpu-primary">{busy?'Saving…':'Save prompt'}</button><button type="button" onClick={()=>setEditing(false)}>Cancel</button></div></form>}</div>;
}

function QuickJob({worker,templates,onStart,onClose,busy}) {
  const choices=templates.filter(t=>t.worker_id===worker.id),[template,setTemplate]=useState(choices[0]?.id||''),[prompt,setPrompt]=useState('');
  return <form className="gpu-panel gpu-stack gpu-quick-job" onSubmit={e=>{e.preventDefault();onStart({template_id:template,prompt});}}><div className="gpu-row"><h2>Add a job to {worker.name}</h2><button type="button" aria-label="Close add job" onClick={onClose}><X size={18}/></button></div>{choices.length?<><Field label="Generation template"><select value={template} onChange={e=>setTemplate(e.target.value)}>{choices.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Job prompt"><textarea autoFocus required rows={4} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe what this GPU should create…"/></Field><button className="gpu-primary" disabled={busy}>{busy?'Adding…':'Add to GPU queue'}</button></>:<><p>Add a generation template for this worker to submit jobs.</p><button type="button" onClick={()=>accountSettings('gpu')}>Open GPU worker settings</button></>}</form>;
}

function Builder({definition,templates,projects,onSave,onClose,busy}) {
  const [name,setName]=useState(definition?.name||'My creative workflow'),[steps,setSteps]=useState(definition?.steps||[{kind:'prompt',prompt:'Write a detailed visual prompt based on {{prompt}}. Return only the visual prompt.'},{kind:'image',prompt:'{{previous_text}}',template_id:templates.find(t=>t.kind==='image')?.id||''},{kind:'prompt',prompt:'Write a short caption for this creative concept: {{previous_text}}'}]);
  const change=(i,value)=>setSteps(steps.map((s,n)=>n===i?{...s,...value}:s));
  const move=(i,delta)=>{const copy=[...steps];[copy[i],copy[i+delta]]=[copy[i+delta],copy[i]];setSteps(copy);};
  return <form className="gpu-builder gpu-panel gpu-stack" onSubmit={e=>{e.preventDefault();onSave({name,steps},definition?.id);}}><div className="gpu-row"><div><p className="gpu-eyebrow">WORKFLOW BUILDER</p><h2>{definition?'Edit workflow':'Make something, step by step'}</h2></div><button type="button" aria-label="Close workflow builder" onClick={onClose}><X size={18}/></button></div><Field label="Workflow name"><input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="gpu-trigger"><span className="gpu-step-number"><Play size={16}/></span><div><strong>When I give a prompt</strong><p>Start this workflow with your idea. Each step can use the result before it.</p></div></div>
    {steps.map((s,i)=>{const Icon=icon[s.kind];return <React.Fragment key={i}><ArrowDown className="gpu-connector" size={20} aria-hidden="true"/><section className="gpu-step"><div className="gpu-row"><div className="gpu-step-title"><span className="gpu-step-number">{i+1}</span><Icon size={18} aria-hidden="true"/><strong>{kindLabel[s.kind]}</strong></div><div className="gpu-actions"><button type="button" aria-label={'Move step '+(i+1)+' up'} disabled={i===0} onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button type="button" aria-label={'Move step '+(i+1)+' down'} disabled={i===steps.length-1} onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button type="button" aria-label={'Remove step '+(i+1)} disabled={steps.length===1} onClick={()=>setSteps(steps.filter((_,n)=>n!==i))}><X size={15}/></button></div></div><Field label={'Step '+(i+1)+' action'}><select value={s.kind} onChange={e=>change(i,{kind:e.target.value,template_id:templates.find(t=>t.kind===e.target.value)?.id||''})}><option value="prompt">Ask AI to write or transform text</option><option value="image">Generate an image</option><option value="video">Generate a video</option><option value="email">Email the output to a client</option><option value="social">Post the output to social media</option><option value="action">Ask AI to act on the output</option></select></Field>{mediaKind(s.kind)&&<Field label={'Step '+(i+1)+' generation template'}><select required value={s.template_id||''} onChange={e=>change(i,{template_id:e.target.value})}><option value="">Choose a template and GPU</option>{templates.filter(t=>t.kind===s.kind).map(t=><option key={t.id} value={t.id}>{t.name} · {t.worker_name}</option>)}</select></Field>}{actionKind(s.kind)&&<Field label={'Step '+(i+1)+' project'} hint="Use this project's enabled email, social and computer connections."><select required value={s.project_id||''} onChange={e=>change(i,{project_id:Number(e.target.value)})}><option value="">Choose a project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.company_name?p.company_name+' / ':''}{p.name}</option>)}</select></Field>}<Field label={'Step '+(i+1)+' prompt'} hint={actionKind(s.kind)?'Tell AI exactly what to do with the generated files. Include the recipient email or social platform/account and any caption or product-link instructions.':undefined}><textarea required rows={3} value={s.prompt} onChange={e=>change(i,{prompt:e.target.value})}/></Field><div className="gpu-actions gpu-variables"><span>Insert:</span>{['prompt','previous_text'].map(v=><button type="button" key={v} onClick={()=>change(i,{prompt:s.prompt+' {{'+v+'}}'})}>{v==='prompt'?'Starting prompt':'Previous text'}</button>)}</div></section></React.Fragment>;})}
    <button type="button" disabled={steps.length>=12} onClick={()=>setSteps([...steps,{kind:'prompt',prompt:'Use the previous result to '}])}><Plus size={16}/>Add next step</button><div className="gpu-actions"><button className="gpu-primary" disabled={busy}>{busy?'Saving…':'Save workflow'}</button><button type="button" onClick={onClose}>Cancel</button></div>
  </form>;
}

export default function GpuWorkflows() {
  const [data,setData]=useState(null),[error,setError]=useState(''),[locked,setLocked]=useState(false),[tab,setTab]=useState('queue'),[filter,setFilter]=useState('active'),[workerFilter,setWorkerFilter]=useState('all'),[auto,setAuto]=useState(true),[builder,setBuilder]=useState(null),[busy,setBusy]=useState(''),[starting,setStarting]=useState(null),[prompt,setPrompt]=useState(''),[selected,setSelected]=useState(null),[quick,setQuick]=useState(null);
  const mounted=useRef(true),loading=useRef(false),requestId=useRef(null);
  const load=useCallback(async()=>{if(loading.current)return;loading.current=true;try{const d=await api.get(base+'/dashboard');if(mounted.current){setData(d);setLocked(false);setError('');}}catch(e){if(mounted.current){setError(e.message);setLocked([403,409].includes(e.status));}}finally{loading.current=false;}},[]);
  useEffect(()=>{mounted.current=true;load();const timer=setInterval(()=>{if(auto&&document.visibilityState==='visible')load();},15000);return()=>{mounted.current=false;clearInterval(timer);};},[load,auto]);
  const act=async(key,fn)=>{setBusy(key);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy('');}};
  if(locked)return <main className="gpu-ui gpu-shell"><div className="gpu-panel gpu-empty"><Cpu size={36}/><h1>Connect a GPU to get started</h1><p>{error}</p><button className="gpu-primary" onClick={()=>accountSettings('gpu')}>Open GPU worker settings</button></div></main>;
  if(!data)return <main className="gpu-ui gpu-shell"><h1>Boardly GPU Workflows</h1><ErrorBox error={error}/><p role="status">Loading your workers and queues…</p></main>;
  const templates=data.templates.map(t=>({...t,worker_name:data.workers.find(w=>w.id===t.worker_id)?.name||'Worker removed'}));
  const runIds=new Set(data.runs.flatMap(r=>r.steps.map(s=>s.id)));
  const external=data.workers.flatMap(w=>(w.snapshot?.jobs||[]).filter(j=>!runIds.has(j.id)).map(j=>({...j,key:w.id+j.id,worker_id:w.id,worker_name:w.name,stale:!!w.error||Date.now()-w.observed_at>60000})));
  const runs=data.runs.map(r=>({...r,key:r.id,title:r.name,source:'Workflow',worker_id:r.steps[Math.min(r.step_index,r.steps.length-1)]?.worker_id,worker_name:data.workers.find(w=>w.id===r.steps[Math.min(r.step_index,r.steps.length-1)]?.worker_id)?.name||'AI connection',isRun:true}));
  const all=[...runs,...external],active=['running','submitted','submitting','waiting'],attention=['blocked','failed'];
  const shown=all.filter(j=>(workerFilter==='all'||j.worker_id===workerFilter)&&(filter==='all'||filter==='active'&&[...active,'queued','paused'].includes(j.status)||filter==='attention'&&attention.includes(j.status)||filter==='completed'&&['completed','published'].includes(j.status))).sort((a,b)=>Number(active.includes(b.status))-Number(active.includes(a.status))||Number(b.isRun)-Number(a.isRun));
  const detail=selected?all.find(j=>j.key===selected):null;
  return <main className="gpu-ui gpu-shell"><header className="gpu-page-header"><div><p className="gpu-eyebrow">YOUR HARDWARE. YOUR CREATIVE PIPELINE.</p><h1>Boardly GPU Workflows</h1><p>See what’s running. Turn an idea into a sequence of creations.</p></div><div className="gpu-actions"><button className="gpu-primary" onClick={()=>{setTab('workflows');setBuilder({});setQuick(null);}}><Plus size={17}/>Add workflow</button><button onClick={()=>accountSettings('gpu')}><Settings2 size={17}/>GPU workers</button></div></header><ErrorBox error={error}/>
    <section className="gpu-workers" aria-label="GPU workers">{data.workers.map(w=><WorkerCard key={w.id} worker={w} onAdd={w=>{setQuick(w);setTab('queue');requestId.current=crypto.randomUUID();}}/>)}</section>
    {quick&&<QuickJob key={quick.id} worker={quick} templates={templates} busy={busy==='quick'} onClose={()=>setQuick(null)} onStart={value=>act('quick',async()=>{const r=await api.post(`${base}/workers/${quick.id}/jobs`,{...value,request_id:requestId.current});setQuick(null);setSelected(r.id);setFilter('active');setTab('queue');})}/>}
    <div className="gpu-toolbar"><nav className="gpu-tabs" aria-label="GPU views"><button aria-current={tab==='queue'?'page':undefined} onClick={()=>{setTab('queue');setSelected(null);}}><ListOrdered size={18}/>Queue <span>{all.filter(j=>[...active,'queued'].includes(j.status)).length}</span></button><button aria-current={tab==='workflows'?'page':undefined} onClick={()=>setTab('workflows')}><Workflow size={18}/>Workflows <span>{data.workflows.length}</span></button></nav><div className="gpu-actions"><button aria-pressed={!auto} onClick={()=>setAuto(!auto)}>{auto?<Pause size={15}/>:<Play size={15}/>} {auto?'Pause updates':'Resume updates'}</button><button disabled={!!busy} onClick={()=>act('refresh',async()=>{await Promise.all(data.workers.map(w=>api.post(`${base}/workers/${w.id}/refresh`,{})));})}><RefreshCw size={15}/>{busy==='refresh'?'Refreshing…':'Refresh'}</button></div></div>
    {tab==='queue'?<>
      <div className="gpu-queue-summary"><span><strong>{all.filter(j=>active.includes(j.status)).length}</strong> running / reconnecting</span><span><strong>{all.filter(j=>j.status==='queued').length}</strong> queued</span><span><strong>{all.filter(j=>attention.includes(j.status)).length}</strong> need attention</span></div>
      <div className="gpu-filters"><Field label="Show jobs"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="active">Active & queued</option><option value="attention">Needs attention</option><option value="completed">Completed & published</option><option value="all">All recent jobs</option></select></Field><Field label="GPU"><select value={workerFilter} onChange={e=>setWorkerFilter(e.target.value)}><option value="all">All GPUs</option>{data.workers.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field></div>
      <section className="gpu-panel gpu-job-list" aria-label="GPU job queue">{shown.length?shown.map(j=><button className="gpu-job" key={j.key} onClick={()=>setSelected(selected===j.key?null:j.key)} aria-expanded={selected===j.key}><span className={'gpu-job-icon '+(active.includes(j.status)?'gpu-job-live':'')}><Film size={19} aria-hidden="true"/></span><span className="gpu-job-title"><strong>{j.title}</strong><small>{j.worker_name} · {j.source}{j.stale?' · last known state':''}{j.batch?' · '+j.batch:''}</small></span><span className="gpu-job-progress">{j.isRun?`${Math.min(j.step_index,j.steps.length)} / ${j.steps.length} steps`:j.status==='queued'&&j.position?'#'+j.position:active.includes(j.status)?'Rendering':''}</span><Badge status={j.status}/><ChevronRight size={16}/></button>):<div className="gpu-empty"><ListOrdered size={30}/><h2>No jobs in this view</h2><p>{filter==='active'?'Create a workflow or submit a job to a connected GPU.':'Choose another filter to see your other jobs.'}</p><button onClick={()=>setTab('workflows')}>Open workflows</button></div>}</section>
      <p className="gpu-small gpu-top">ComfyUI provides job state; a render percentage is shown only when the engine supplies one. Recent engine history and the last three producer batches are included.</p>
      {detail&&<section className="gpu-panel gpu-stack gpu-top"><div className="gpu-row"><h2>{detail.title}</h2><button aria-label="Close job details" onClick={()=>setSelected(null)}><X size={17}/></button></div><ErrorBox error={detail.error}/>{detail.prompt&&<p className="gpu-pre">{detail.prompt}</p>}{detail.isRun?<><div className="gpu-actions">{['queued','running'].includes(detail.status)&&<button disabled={!!busy} onClick={()=>act('pause',()=>api.post(`${base}/runs/${detail.id}/pause`,{}))}><Pause size={15}/>Pause workflow</button>}{(detail.status==='paused'||detail.status==='blocked'&&actionKind(detail.steps[detail.step_index]?.kind))&&<button disabled={!!busy} onClick={()=>act('resume',()=>api.post(`${base}/runs/${detail.id}/resume`,{}))}><Play size={15}/>Resume</button>}{detail.status==='blocked'&&detail.steps[detail.step_index]?.kind==='prompt'&&<button disabled={!!busy} onClick={()=>act('retry',()=>api.post(`${base}/runs/${detail.id}/retry`,{}))}>Retry AI step</button>}{!['completed','cancelled'].includes(detail.status)&&<button disabled={!!busy} onClick={()=>act('cancel',()=>api.post(`${base}/runs/${detail.id}/cancel`,{}))}>Cancel remaining steps</button>}</div><p className="gpu-small">Pause stops future steps. Cancel also stops pending project actions. A render or external send already in progress may finish.</p>{detail.steps.map((s,i)=><article className="gpu-step" key={s.id}><div className="gpu-row"><strong>{i+1}. {s.template_name||kindLabel[s.kind]}</strong><Badge status={s.status}/></div><StepPrompt run={detail} step={s} index={i} onSaved={load}/>{s.text&&<div className="gpu-text-output">{s.text}</div>}{s.message&&<p>{s.message}</p>}<ErrorBox error={s.error}/><Outputs files={s.outputs||s.files} worker={s.worker_id} port={s.port} onError={setError}/>{s.thread_id&&<a className="gpu-button" href={`#/board/${s.project_id}?chat=${s.thread_id}`}>Open project action <ChevronRight size={15}/></a>}</article>)}</>:<><JobPrompts key={detail.key} job={detail} onSaved={load}/><Outputs files={detail.outputs} worker={detail.worker_id} port={detail.port} onError={setError}/></>}</section>}
    </>:<section className="gpu-stack"><div className="gpu-row"><div><h2>Your workflows</h2><p>Start with a prompt. Let each step build on the last.</p></div><button className="gpu-primary" onClick={()=>setBuilder({})}><Plus size={17}/>New workflow</button></div>{builder&&<Builder key={builder.id||'new'} definition={builder.id?builder:null} templates={templates} projects={data.projects||[]} busy={busy==='save'} onClose={()=>setBuilder(null)} onSave={(value,id)=>act('save',async()=>{await (id?api.put(`${base}/workflows/${id}`,value):api.post(base+'/workflows',value));setBuilder(null);})}/>}{!templates.length&&<div className="gpu-note">Add generation templates in GPU worker settings to enable image and video steps. AI prompt steps use your connected Boardly AI account.</div>}
      <div className="gpu-workflow-grid">{data.workflows.map(w=><article className="gpu-panel gpu-stack" key={w.id}><div className="gpu-row"><span className="gpu-chip"><Workflow size={20}/></span><span className="gpu-muted">{w.steps.length} steps</span></div><h3>{w.name}</h3><div className="gpu-chain">{w.steps.map((s,i)=>{const Icon=icon[s.kind];return <span key={i}><Icon size={15}/>{kindLabel[s.kind]}{i<w.steps.length-1&&<ChevronRight size={12}/>}</span>;})}</div><div className="gpu-actions"><button className="gpu-primary" onClick={()=>{setStarting(w);setPrompt('');requestId.current=crypto.randomUUID();}}><Play size={15}/>Run with a prompt</button><button onClick={()=>setBuilder(w)}>Edit</button></div></article>)}</div>{!data.workflows.length&&!builder&&<div className="gpu-panel gpu-empty"><Workflow size={32}/><h3>Build your first creative workflow</h3><p>For example: write a scene → create an image → write a caption.</p><button className="gpu-primary" onClick={()=>setBuilder({})}>Create workflow</button></div>}
      {starting&&<form className="gpu-panel gpu-stack" onSubmit={e=>{e.preventDefault();act('run',async()=>{const r=await api.post(`${base}/workflows/${starting.id}/run`,{prompt,request_id:requestId.current});setStarting(null);setSelected(r.id);setFilter('active');setTab('queue');});}}><h3>Run: {starting.name}</h3>{starting.steps.some(s=>actionKind(s.kind))&&<div className="gpu-note">This workflow will perform its saved output actions using the selected project connections: {starting.steps.filter(s=>actionKind(s.kind)).map(s=>kindLabel[s.kind]).join(', ')}.</div>}<Field label="Your starting prompt"><textarea required autoFocus rows={4} value={prompt} onChange={e=>{setPrompt(e.target.value);requestId.current=crypto.randomUUID();}} placeholder="Granny skydiving with a bag of Got Beef jerky, filmed like a real action camera…"/></Field><div className="gpu-actions"><button className="gpu-primary" disabled={!!busy}>{busy==='run'?'Adding to queue…':'Start workflow'}</button><button type="button" disabled={!!busy} onClick={()=>setStarting(null)}>Cancel</button></div></form>}
    </section>}
  </main>;
}
