import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton,settingsInput} from './SettingsShell.jsx';
export default function HuggingFaceConnection(){
 const [data,setData]=useState(null),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const base='/api/account/huggingface';
 useEffect(()=>{api.get(base).then(setData).catch(e=>setError(e.message));},[]);
 async function act(fn){setBusy(true);setError('');try{setData(await fn());}catch(e){setError(e.message);}finally{setToken('');setBusy(false);}}
 return <section aria-label="Hugging Face connection" className="space-y-4"><p className="text-sm text-zinc-400">Connect your Hugging Face account. Your token is encrypted and stays out of agent messages.</p>{error&&<p role="alert" className="text-rose-300">{error}</p>}{data&&<><p role="status">{data.connected?'Connected as '+data.username:'Hugging Face is not connected'}</p><form className="space-y-4" onSubmit={e=>{e.preventDefault();act(()=>api.put(base,{token}));}}><label className="block text-sm">Hugging Face token<input type="password" required autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} className={settingsInput}/></label><a href="https://huggingface.co/settings/tokens" target="_blank" rel="noreferrer" className="text-indigo-300 underline">Create a Hugging Face token</a><div><button disabled={busy||!token} className={settingsButton}>{busy?'Checking…':'Verify & save connection'}</button></div></form>{data.connected&&<><div className="flex flex-wrap gap-3"><button disabled={busy} onClick={()=>act(()=>api.post(base+'/test'))} className={settingsButton}>Refresh account</button><button disabled={busy} onClick={()=>act(()=>api.del(base))} className={settingsButton}>Disconnect</button></div><h3 className="font-semibold">Your organizations</h3>{data.organizations.length?data.organizations.map(o=><article key={o.name} className="rounded-xl border border-zinc-700 p-4"><p>{o.name} · {o.role}</p><a href={'https://huggingface.co/organizations/'+o.name+'/settings/members'} target="_blank" rel="noreferrer" className="text-sm text-indigo-300 underline">Manage members on Hugging Face</a></article>):<p className="text-sm text-zinc-400">No organizations were returned for this token.</p>}<p className="text-sm text-zinc-400">Automated invitations are not enabled yet. Organization plans and SSO settings determine the supported invitation method; use the organization’s member settings for now.</p></>}</>}</section>;
}
