import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
import {settingsButton as button,settingsInput as input} from './SettingsShell.jsx';
export default function MasterChat(){
 const [threads,setThreads]=useState([]),[catalog,setCatalog]=useState([]),[selected,setSelected]=useState(null),[chat,setChat]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const base='/api/master-chat';
 const loadThreads=async()=>{const result=await api.get(base+'/threads');setThreads(result.threads);setCatalog(result.catalog);return result.threads;};
 useEffect(()=>{let live=true;api.get(base+'/threads').then(result=>{if(live){setThreads(result.threads);setCatalog(result.catalog);setSelected(result.threads[0]?.id||null);}}).catch(e=>live&&setError(e.message));return()=>{live=false;};},[]);
 useEffect(()=>{if(!selected){setChat(null);return;}let live=true,pending=false;const load=async()=>{if(pending)return;pending=true;try{const result=await api.get(base+'/threads/'+selected);if(live)setChat(result);}catch(e){if(live)setError(e.message);}finally{pending=false;}};setChat(null);load();const timer=setInterval(load,1800);return()=>{live=false;clearInterval(timer);};},[selected]);
 async function act(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const active=chat?.turns.find(t=>['queued','running'].includes(t.status));
 async function refresh(){if(selected)setChat(await api.get(base+'/threads/'+selected));await loadThreads();}
 async function submit(e){e.preventDefault();await act(async()=>{let id=selected;if(!id){const created=await api.post(base+'/threads',{});id=created.id;setSelected(id);}const result=await api.post(base+'/threads/'+id+'/messages',{content:message,client_id:crypto.randomUUID()});setChat(result);setMessage('');await loadThreads();});}
 return <main className="max-w-6xl mx-auto px-4 sm:px-6 py-8 space-y-5" data-testid="master-chat">
  <button className={button} onClick={()=>location.hash='#/'}>Back to companies</button><div><h1 className="text-2xl font-semibold">Master Chat</h1><p className="text-sm text-zinc-400 mt-2">One conversation across your companies. Ask questions, create company skills and change settings from here.</p><p className="text-xs text-zinc-500 mt-2">Only the account owner can use Master Chat. Review each change and press Apply changes. Enter passwords and API keys in the secure connection forms.</p></div>
  <div className="grid md:grid-cols-[220px_minmax(0,1fr)] gap-5">
   <aside className="space-y-3 min-w-0"><button className={button+' w-full justify-center'} disabled={busy} onClick={()=>act(async()=>{const t=await api.post(base+'/threads',{});setSelected(t.id);setMessage('');await loadThreads();})}>New Master Chat</button><nav aria-label="Master Chat history" className="max-h-64 md:max-h-[65vh] overflow-auto space-y-1">{threads.map(t=><button key={t.id} className={'text-sm text-left w-full p-3 rounded-lg break-words '+(selected===t.id?'bg-indigo-600/20 text-indigo-200':'hover:bg-zinc-900 text-zinc-400')} onClick={()=>{setSelected(t.id);setError('');setMessage('');}}>{t.title}</button>)}</nav><details className="text-xs text-zinc-400"><summary className="cursor-pointer">Settings I can change</summary><ul className="list-disc pl-4 mt-2 space-y-2">{catalog.map(c=><li key={c.type}>{c.description}</li>)}</ul></details></aside>
   <section className="min-w-0 space-y-4">
    {error&&<p role="alert" className="rounded-xl bg-rose-950/30 border border-rose-500/30 p-3 text-sm text-rose-200">{error}</p>}
    {!chat?.turns.length&&<div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5 space-y-3"><h2 className="font-medium">What would you like to change?</h2><div className="flex flex-wrap gap-2">{['Show me all my companies and their rules.','Help me turn a workflow into a company skill.','Help me update a company’s settings.'].map(s=><button key={s} className={button+' text-left'} onClick={()=>setMessage(s)}>{s}</button>)}</div></div>}
    {chat?.turns.map(t=><article key={t.id} className="space-y-4"><div className="rounded-xl bg-indigo-600/15 border border-indigo-500/25 p-4 whitespace-pre-wrap break-words text-sm"><span className="block text-xs text-indigo-300 mb-2">You</span>{t.prompt}</div>{t.reply&&<div className="rounded-xl border border-zinc-800 p-4 whitespace-pre-wrap break-words text-sm"><span className="block text-xs text-zinc-500 mb-2">Master Chat</span>{t.reply}</div>}{t.error&&<p role="alert" className="text-rose-300 text-sm">{t.error}</p>}
     {t.changes.map(c=><section key={c.id} aria-label={`Change for ${c.company_name}`} className="rounded-xl border border-amber-500/40 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-medium">{c.company_name}</h3><span className={'text-xs '+(c.status==='applied'?'text-emerald-300':'text-amber-300')}>{c.status==='pending'?'Review required':c.status}</span></div><p className="text-sm whitespace-pre-wrap break-words">{c.summary}</p><p className="text-xs text-zinc-500">Setting: {c.type.replaceAll('_',' ')}</p><div className="rounded-lg bg-zinc-950 p-3 space-y-3">{Object.entries(c.changes).map(([key,value])=><div key={key}><span className="text-xs text-zinc-500">{key.replaceAll('_',' ')}</span><pre className="text-sm whitespace-pre-wrap break-words">{typeof value==='string'?value:JSON.stringify(value)}</pre></div>)}{c.type==='remove_skill'&&<p className="text-sm text-rose-300">Remove skill: {c.before?.name}</p>}</div><details><summary className="text-xs text-zinc-400 cursor-pointer">Current values used for this preview</summary><pre className="text-xs whitespace-pre-wrap break-words mt-2 max-h-64 overflow-auto">{JSON.stringify(c.before,null,2)}</pre></details>{c.error&&<p className="text-sm text-rose-300">{c.error}</p>}{c.status==='pending'&&<div className="flex gap-2"><button className={button+' bg-indigo-600'} disabled={busy} onClick={()=>act(async()=>{await api.post(base+'/changes/'+c.id+'/apply',{reviewed:true});await refresh();})}>Apply changes</button><button className={button} disabled={busy} onClick={()=>act(async()=>{await api.post(base+'/changes/'+c.id+'/dismiss',{});await refresh();})}>Dismiss</button></div>}{c.status==='applied'&&<p className="text-sm text-emerald-300" role="status">Applied to {c.company_name}. The saved settings have been updated.</p>}</section>)}
     {t.status==='failed'&&<button className={button} disabled={busy||!!active} onClick={()=>act(async()=>{await api.post(base+'/turns/'+t.id+'/retry',{});await refresh();})}>Retry reply</button>}
    </article>)}
    {active&&<p role="status" className="text-sm text-indigo-300">Master Chat is checking your request… <button className="underline ml-2" disabled={busy} onClick={()=>act(async()=>{await api.post(base+'/turns/'+active.id+'/cancel',{});await refresh();})}>Stop</button></p>}
    <form className="space-y-3 sticky bottom-0 bg-zinc-950 py-3" onSubmit={submit}><label className="sr-only" htmlFor="master-message">Message Master Chat</label><textarea id="master-message" className={input+' min-h-24'} rows={3} maxLength={12000} required value={message} onChange={e=>setMessage(e.target.value)} placeholder="For Acme, save a rule that marketing posts need my approval before publishing."/><div className="flex justify-end"><button className={button+' bg-indigo-600'} disabled={busy||!!active||!message.trim()}>Send to Master Chat</button></div></form>
   </section>
  </div>
 </main>;
}
