import React,{useEffect,useState,useRef} from 'react';
import {api} from '../api.js';
import {accountSettings,settingsButton,settingsInput} from './SettingsShell.jsx';
const names={fal:'fal',higgsfield:'Higgsfield'},dashboards={fal:'https://fal.ai/dashboard/keys',higgsfield:'https://cloud.higgsfield.ai/'},docs={fal:'https://fal.ai/models',higgsfield:'https://docs.higgsfield.ai/docs'};
export default function MediaConnection({provider,kind='account',id}){
 const [data,setData]=useState(null),[token,setToken]=useState(''),[secret,setSecret]=useState(''),[model,setModel]=useState(''),[options,setOptions]=useState('{}'),[limit,setLimit]=useState(10),[enabled,setEnabled]=useState(false),[prompt,setPrompt]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const requestKey=useRef(null),name=names[provider],account=kind==='account',base=account?'/api/account/media/'+provider:`/api/${kind==='company'?'companies':'projects'}/${id}/media/${provider}`;
 async function load(){const d=await api.get(base);setData(d);setModel(d.model);setOptions(JSON.stringify(d.defaults,null,2));setLimit(d.daily_limit);setEnabled(d.enabled||false);}
 useEffect(()=>{let active=true;load().catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[base]);
 async function act(fn,message){setBusy(true);setError('');setNotice('');try{await fn();await load();setNotice(message);}catch(e){setError(e.message);}finally{setToken('');setSecret('');setBusy(false);}}
 const operate=(job,action)=>act(()=>api.post(`/api/projects/${id}/media-jobs/${job.id}/${action}`),action==='cancel'?'Cancellation requested. Check the final status; a running job may still be charged.':'Job status refreshed.');
 return <div className="space-y-5">{error&&<p role="alert" className="text-rose-300">{error}</p>}{notice&&<p role="status" className="text-emerald-300">{notice}</p>}{!data&&!error&&<p>Loading media connection…</p>}{data&&<>
 <div className="rounded-xl border border-zinc-700 p-4"><h3 className="font-semibold">{data.saved?(data.verified?'Provider accepted a generation':'API key saved · not yet verified'):'Connect your own '+name+' account'}</h3><p className="text-sm text-zinc-400 mt-2">Generations use your provider account and credits. Boardly does not supply media credits. Saving a key does not start a paid generation.</p></div>
 {account?<><form className="space-y-4" onSubmit={e=>{e.preventDefault();act(async()=>{let defaults;try{defaults=JSON.parse(options);}catch{throw Error('Model options must be valid JSON.');}await api.put(base,{token:token?(provider==='higgsfield'?token+':'+secret:token):'',model,defaults,daily_limit:limit});},'Media settings saved. Enable access in selected company or project settings.');}}>
 <label className="block text-sm">{name} {provider==='higgsfield'?'API key ID':'API key'}<input aria-label={name+' API key'} type="password" autoComplete="new-password" value={token} onChange={e=>setToken(e.target.value)} required={!data.saved} placeholder={data.saved?'Saved · paste to replace':'Paste your provider key'} className={settingsInput+' mt-2'}/></label>
 {provider==='higgsfield'&&<label className="block text-sm">Higgsfield API key secret<input aria-label="Higgsfield API secret" type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} required={!!token||!data.saved} className={settingsInput+' mt-2'}/></label>}
 <a href={dashboards[provider]} target="_blank" rel="noreferrer" className="text-sm text-indigo-300 underline">Open {name} API dashboard</a>
 <label className="block text-sm">Approved model endpoint<input aria-label={name+' model endpoint'} value={model} onChange={e=>setModel(e.target.value)} required className={settingsInput+' mt-2'}/></label>
 <p className="text-sm text-zinc-400">Copy an image or video model endpoint ID from the <a href={docs[provider]} target="_blank" rel="noreferrer" className="text-indigo-300 underline">provider’s model documentation</a>. Agents can change the prompt; the model and options below stay under your control.</p>
 <label className="block text-sm">Model options (JSON)<textarea aria-label={name+' model options'} rows={4} value={options} onChange={e=>setOptions(e.target.value)} className={settingsInput+' mt-2 font-mono'}/></label>
 <p className="text-xs text-zinc-400">Set options such as image size, duration or number of outputs according to that model’s schema. For models requiring input media, put its approved input URL here. Do not put passwords or API keys in model options.</p>
 <label className="block text-sm">Daily generation request limit<input aria-label={name+' daily generation limit'} type="number" min="1" max="1000" value={limit} onChange={e=>setLimit(Number(e.target.value))} className={settingsInput+' mt-2'}/></label>
 <p className="text-xs text-zinc-400">Shared across your enabled companies and projects; resets at midnight UTC. This limits requests, not dollars or individual output files. Review model prices and set spending limits in your provider account. Failed or uncertain submissions still count.</p>
 <button disabled={busy} className={settingsButton+' bg-indigo-600'}>Save media connection</button></form>{data.saved&&<button disabled={busy} className={settingsButton} onClick={()=>act(()=>api.del(base),'Disconnected. New generations are paused. Already submitted jobs may finish and incur provider charges.')}>Disconnect {name}</button>}
 </>:<><p className="text-sm text-zinc-400">{data.model} · {data.daily_limit} requests per day across this account. Enabling access allows Work agents of this {kind}’s editors to submit paid generations using your saved provider key.</p><label className="flex gap-3 items-center text-sm"><input type="checkbox" checked={enabled||data.inherited} disabled={!data.saved||busy||data.inherited} onChange={e=>setEnabled(e.target.checked)}/>Allow {name} generation{data.inherited?' · inherited from company':''}</label><div className="flex flex-wrap gap-3"><button disabled={busy||!data.saved} className={settingsButton} onClick={()=>act(()=>api.put(base,{enabled}),'Media access updated.')}>Save media access</button><button className={settingsButton} onClick={()=>accountSettings(provider)}>Manage account connection</button></div>{data.inherited&&<p className="text-xs text-zinc-400">To remove inherited access, disable this provider in company settings.</p>}
 {kind==='project'&&<><form className="border-t border-zinc-700 pt-4 space-y-3" onSubmit={e=>{e.preventDefault();act(async()=>{if(!requestKey.current)requestKey.current=crypto.randomUUID();await api.post(base+'/generate',{prompt,request_key:requestKey.current});requestKey.current=null;setPrompt('');},'Generation submitted. Refresh its job to check progress.');}}><label className="block text-sm">Generation prompt<textarea aria-label={name+' generation prompt'} required maxLength={8000} rows={3} value={prompt} onChange={e=>{setPrompt(e.target.value);requestKey.current=null;}} className={settingsInput+' mt-2'}/></label><button disabled={busy||!data.saved||!data.allowed} className={settingsButton+' bg-indigo-600'}>Generate with {name} · uses provider credits</button><p className="text-xs text-zinc-400">If submission is interrupted, refresh this page and check existing jobs before submitting another generation.</p></form>
 <section className="space-y-3"><h3 className="font-semibold">Generation jobs</h3>{!data.jobs?.length&&<p className="text-sm text-zinc-400">No generations in this project yet.</p>}{data.jobs?.map(j=><article key={j.id} aria-label={'Generation '+j.id} className="border border-zinc-700 rounded-xl p-4 space-y-2"><p className="font-medium text-sm">{j.status.replaceAll('_',' ')} · {j.model}</p><p className="text-sm text-zinc-400 whitespace-pre-wrap break-words">{j.prompt}</p><p className="text-xs text-zinc-500 break-all">Job {j.id}{j.request_id?' · Provider '+j.request_id:''}</p>{j.status==='uncertain'&&<p className="text-sm text-amber-200">Submission outcome is uncertain. Check the provider dashboard before creating another job; it may already be chargeable.</p>}<div className="flex gap-3 flex-wrap">{j.outputs.map((url,i)=><a key={url} href={url} target="_blank" rel="noreferrer" className={settingsButton}>Open output {i+1}</a>)}</div>{!['completed','failed','nsfw','canceled','uncertain'].includes(j.status)&&<div className="flex gap-3"><button disabled={busy} className={settingsButton} onClick={()=>operate(j,'refresh')}>Refresh job</button><button disabled={busy} className={settingsButton} onClick={()=>operate(j,'cancel')}>Request cancellation</button></div>}</article>)}<p className="text-xs text-zinc-400">Output links are hosted by your provider and can expire. Download files you need to keep and add them to project Files. Boardly stores job records, not copies of the generated media.</p></section></>}
 </>}
 </>}</div>;
}
