import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
const input='rounded-lg bg-zinc-950 border border-zinc-700 px-3 py-2 text-sm';
export default function Members({kind,id,onClose}){
 const [data,setData]=useState(null),[email,setEmail]=useState(''),[role,setRole]=useState('editor'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>api.get(`/api/${kind}/${id}/members`).then(setData);
 useEffect(()=>{load().catch(e=>setError(e.message));},[kind,id]);
 async function act(fn){setBusy(true);setError('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <div className="fixed inset-0 z-50 bg-black/60 p-4 flex items-center justify-center" onClick={onClose}><section role="dialog" aria-modal="true" aria-label="Members" onClick={e=>e.stopPropagation()} className="w-full max-w-2xl max-h-[90vh] overflow-auto rounded-2xl bg-zinc-900 border border-zinc-700 p-6 space-y-5">
  <header className="flex justify-between"><h2 className="text-xl font-semibold">{kind==='companies'?'Company':'Project'} members</h2><button aria-label="Close members" onClick={onClose}>✕</button></header>
  <p className="text-sm text-zinc-400">{kind==='companies'?'Company members can access every project in this company.':'Project members can access this project. Company access is inherited.'} Each person counts once toward the account’s user allowance, including pending users. They do not need a paid account.</p>
  {data&&<p className="text-sm">{data.usage.users} users across this account · {data.user_limit===null?'Unlimited users':`${data.user_limit} user allowance`}</p>}
  {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}{notice&&<p role="status" className="text-emerald-300 text-sm">{notice}</p>}
  <form className="flex flex-wrap gap-2" onSubmit={e=>{e.preventDefault();act(async()=>{await api.post(`/api/${kind}/${id}/members`,{email,role});setEmail('');setNotice('User added. Share the sign-in link below; they can sign in with an email code.');});}}><input aria-label="Member email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="teammate@company.com" className={input+' flex-1 min-w-48'}/><select aria-label="Member role" className={input} value={role} onChange={e=>setRole(e.target.value)}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-sm disabled:opacity-50">Add user</button></form>
  <p className="text-xs text-zinc-400">Editors manage tasks and files and use their own AI billing. Viewers can read and download. Account settings, company email, project secrets and payment cards are managed by the account owner.</p>
  {data&&<div className="space-y-3">{[...data.members,...data.inherited].map(m=><div key={m.grant_id} className="flex flex-wrap items-center gap-3 rounded-lg border border-zinc-800 p-3"><div className="flex-1"><p className="text-sm">{m.email}</p><p className="text-xs text-zinc-500">{m.inherited_from?`From ${m.inherited_from}`:m.status==='active'?'Active':'Awaiting first sign-in'}</p></div>{m.inherited_from?<span className="text-xs text-zinc-400">{m.role}</span>:<><select aria-label={`Role for ${m.email}`} value={m.role} disabled={busy} className={input} onChange={e=>act(()=>api.patch(`/api/memberships/${m.grant_id}`,{role:e.target.value}))}><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button disabled={busy} className="text-sm text-rose-300" onClick={()=>act(()=>api.del(`/api/memberships/${m.grant_id}`))}>Remove</button></>}</div>)}{!data.members.length&&!data.inherited.length&&<p className="text-sm text-zinc-500">Only the account owner has access.</p>}<div className="text-sm border-t border-zinc-800 pt-4"><p className="text-zinc-400 mb-2">Share this sign-in link with the added user:</p><a href={data.sign_in_url} className="text-indigo-300 break-all">{data.sign_in_url}</a><button className="ml-3 text-indigo-300" onClick={()=>navigator.clipboard.writeText(data.sign_in_url).then(()=>setNotice('Sign-in link copied.')).catch(()=>setError('Copy the sign-in link shown here.'))}>Copy link</button></div></div>}
 </section></div>;
}
