import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
export default function ProjectEmployees({board,onClose}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[employee,setEmployee]=useState(''),[task,setTask]=useState(''),[instruction,setInstruction]=useState('');
 const base=`/api/boards/${board.id}/employees`,owner=board.permissions?.owner!==false;
 useEffect(()=>{let active=true,pending=false;const refresh=async()=>{if(pending)return;pending=true;try{const d=await api.get(base);if(active)setData(d);}catch(e){if(active)setError(e.message);}finally{pending=false;}};refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer);};},[base]);
 async function action(fn){setBusy(true);setError('');try{await fn();setData(await api.get(base));}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section aria-label="Project employees" className="p-4 space-y-4 overflow-y-auto min-h-36 flex-1">
  <div className="flex justify-between gap-3"><h3 className="font-semibold">Project employees</h3><button onClick={onClose} className="text-sm underline">Close team</button></div>
  <p className="text-sm text-zinc-400">Named teammates share assignments and handoffs. The coordinator dispatches unclaimed To Do tasks while continuous work is enabled. Real blockers wait for their next action.</p>
  {error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}
  {data&&<>
   <p role="status" className="text-sm text-indigo-200">{data.team.enabled?'Continuous team enabled':'Continuous team paused'}</p>
   {owner&&<button disabled={busy} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm disabled:opacity-40" onClick={()=>action(()=>api.put(base,{enabled:!data.team.enabled,instruction:data.team.instruction||'Complete the authorized To Do tasks, verify deliverables and share handoffs. Keep working until done, stopped or blocked.'}))}>{data.team.enabled?'Pause new assignments':'Enable continuous team'}</button>}
   <form className="space-y-2 border border-zinc-700 rounded-xl p-3" onSubmit={e=>{e.preventDefault();action(async()=>{await api.post(base+'/assign',{employee_id:employee||data.employees[0]?.id,card_id:Number(task),instruction});setTask('');setInstruction('');});}}><h4 className="text-sm font-semibold">Call an employee</h4><label className="text-sm block">Employee<select aria-label="Employee" value={employee||data.employees[0]?.id||''} onChange={e=>setEmployee(e.target.value)} className="block w-full bg-zinc-900 rounded-lg p-2">{data.employees.map(e=><option key={e.id} value={e.id}>{e.name} · {e.role}</option>)}</select></label><label className="text-sm block">Task number<input aria-label="Assignment task number" type="number" min="1" required value={task} onChange={e=>setTask(e.target.value)} className="block w-full bg-zinc-900 rounded-lg p-2"/></label><label className="text-sm block">Instructions<textarea aria-label="Assignment instructions" value={instruction} maxLength={10000} onChange={e=>setInstruction(e.target.value)} className="block w-full bg-zinc-900 rounded-lg p-2"/></label><button disabled={busy||!task} className="rounded-lg bg-indigo-600 px-3 py-2 text-sm disabled:opacity-40">Assign task</button></form>
   <div className="grid gap-3">{data.employees.map(e=>{const latest=data.assignments.find(a=>a.employee_id===e.id);return <article key={e.id} className="border border-zinc-700 rounded-xl p-3"><h4 className="font-medium">{e.name} <span className="text-xs text-indigo-300">{e.role}</span></h4><p className="text-xs text-zinc-400 mt-1">{e.instruction}</p><p className="text-sm mt-2">{latest?`Task #${latest.card_id} · ${latest.status}`:e.role==='Coordinator'&&data.team.enabled?'Watching the task queue':'Available'}</p>{latest&&<><p className="text-xs text-zinc-400">{latest.blocker||latest.progress}</p><a className="text-xs underline text-indigo-300" href={`#/board/${board.id}?chat=${latest.thread_id}`}>Open assignment</a>{['queued','running','recovering'].includes(latest.status)&&<button className="ml-3 text-xs underline" onClick={()=>action(()=>api.post(`/api/chat/jobs/${latest.job_id}/cancel`,{}))}>Stop assignment</button>}</>}</article>;})}</div>
   <h4 className="text-sm font-semibold">Team handoffs</h4><div className="space-y-3 max-h-80 overflow-y-auto">{data.messages.map(m=><article key={m.id} className="text-sm border-l-2 border-indigo-500 pl-3"><p className="text-xs text-zinc-500">{data.employees.find(e=>e.id===m.sender_id)?.name||'Coordinator / owner'}{m.recipient_id?' → '+(data.employees.find(e=>e.id===m.recipient_id)?.name||'Employee'):' → Team'}</p><p className="whitespace-pre-wrap break-words">{m.body}</p></article>)}</div>
   <form onSubmit={e=>{e.preventDefault();action(async()=>{await api.post(base+'/messages',{body:message});setMessage('');});}} className="space-y-2"><label className="text-sm block">Message the team<textarea aria-label="Team message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={8000} className="mt-2 w-full bg-zinc-900 border border-zinc-700 rounded-lg p-2"/></label><button disabled={busy||!message.trim()} className="rounded-lg bg-zinc-800 px-3 py-2 text-sm">Save team message</button></form>
  </>}
 </section>;
}
