import React,{useEffect,useState} from 'react';
import {api} from '../api.js';
const button='rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const field='w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm';
const initial={label:'',host:'',port:22,username:'',auth_type:'key',private_key:'',passphrase:'',password:'',fingerprint:'',allow_agent:false,tailnet_device_id:''};
export default function SshConnections({kind,id}){
 const [data,setData]=useState({connections:[],inherited:[]}),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[network,setNetwork]=useState(null);
 const base=`/api/${kind}/${id}/ssh`;const load=()=>api.get(base).then(setData);
 useEffect(()=>{load().catch(e=>setError(e.message));api.get('/api/account/tailscale').then(setNetwork).catch(()=>{});},[base]);
 async function act(fn){setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="space-y-4"><div className="flex items-center justify-between"><div><h3 className="font-semibold">SSH connections</h3><p className="text-xs text-zinc-400 mt-2">{kind==='companies'?'Share servers with projects in this company.':'Save servers for this project.'} Agent access applies only to Work mode.</p></div><button className={button} onClick={()=>setForm({...initial})}>Add SSH connection</button></div>
  {error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-300">{notice}</p>}
  {form&&<form className="p-4 rounded-xl border border-indigo-500/30 space-y-3" onSubmit={e=>{e.preventDefault();act(async()=>{await api.post(base,form);setForm(null);setNotice('SSH connection saved');});}}>
   <label className="block text-xs text-zinc-400">Network / device<select aria-label="Network / device" className={field+' mt-1'} value={form.tailnet_device_id} onChange={e=>{const d=network?.devices.find(d=>d.id===e.target.value);setForm({...form,tailnet_device_id:e.target.value,host:d?(d.dns_name||d.addresses[0]):''});}}><option value="">Standard SSH hostname or IP</option>{network?.state==='Running'&&network.devices.map(d=><option key={d.id} value={d.id}>Tailscale · {d.name}{d.online?'':' (offline)'}</option>)}</select></label>
   {network?.state!=='Running'&&<p className="text-xs text-zinc-500">Connect Tailscale in Account & AI to select your private devices.</p>}
   <div className="grid sm:grid-cols-2 gap-3">{[['label','Connection name'],['host','Hostname or IP'],['port','Port'],['username','SSH username']].map(([key,label])=><label key={key} className="text-xs text-zinc-400">{label}<input required readOnly={key==='host'&&!!form.tailnet_device_id} className={field+' mt-1'} type={key==='port'?'number':'text'} min={key==='port'?1:undefined} max={key==='port'?65535:undefined} value={form[key]} onChange={e=>setForm({...form,[key]:key==='port'?Number(e.target.value):e.target.value})}/></label>)}</div>
   <label className="block text-xs text-zinc-400">Authentication<select className={field+' mt-1'} value={form.auth_type} onChange={e=>setForm({...form,auth_type:e.target.value})}><option value="key">Private SSH key</option><option value="password">Password</option></select></label>
   {form.auth_type==='key'?<><label className="block text-xs text-zinc-400">Private key<textarea required autoComplete="off" spellCheck={false} className={field+' mt-1 font-mono'} rows={4} value={form.private_key} onChange={e=>setForm({...form,private_key:e.target.value})}/></label><label className="block text-xs text-zinc-400">Key passphrase (if needed)<input autoComplete="new-password" type="password" className={field+' mt-1'} value={form.passphrase} onChange={e=>setForm({...form,passphrase:e.target.value})}/></label></>:<label className="block text-xs text-zinc-400">SSH password<input required autoComplete="new-password" type="password" className={field+' mt-1'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}
   <label className="block text-xs text-zinc-400">Trusted host fingerprint<input required className={field+' mt-1 font-mono'} placeholder="SHA256:…" value={form.fingerprint} onChange={e=>setForm({...form,fingerprint:e.target.value.trim()})}/></label><p className="text-xs text-zinc-500">Copy the SHA256 host-key fingerprint from your server console or a trusted existing SSH connection. Boardly checks it before sending credentials.</p>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={form.allow_agent} onChange={e=>setForm({...form,allow_agent:e.target.checked})}/>Allow Work agents to use this connection</label><div className="flex gap-2"><button disabled={busy} className={button+' bg-indigo-600'}>Save SSH connection</button><button type="button" className={button} onClick={()=>setForm(null)}>Cancel</button></div>
  </form>}
  {data.connections.map(c=><article key={c.id} className="border border-zinc-700 rounded-xl p-4 space-y-3"><div><h4 className="font-medium">{c.label}</h4><p className="text-xs text-zinc-400">{c.tailnet_device_id?'Tailscale · ':''}{c.username}@{c.host}:{c.port} · {c.auth_type==='key'?'Private key stored':'Password stored'}</p><p className="text-xs text-zinc-500 break-all mt-1">{c.fingerprint}</p></div><label className="flex gap-2 text-sm"><input disabled={busy} type="checkbox" checked={!!c.allow_agent} onChange={e=>act(()=>api.patch(base+'/'+c.id,{allow_agent:e.target.checked}))}/>Allow Work agents</label><div className="flex gap-2"><button disabled={busy} className={button} onClick={()=>act(async()=>{await api.post(base+'/'+c.id+'/test',{});setNotice(c.label+': authenticated successfully from Boardly cloud');})}>Test connection</button><button disabled={busy} className={button} onClick={()=>act(()=>api.del(base+'/'+c.id))}>Remove connection</button></div></article>)}
  {!!data.inherited.length&&<div className="rounded-xl border border-zinc-800 p-4"><h4 className="text-sm font-medium">Enabled company connections</h4>{data.inherited.map(c=><p className="text-sm text-zinc-400 mt-2" key={c.id}>{c.label} · {c.username}@{c.host} · managed in Company → SSH</p>)}</div>}
  {!data.connections.length&&!form&&<p className="text-sm text-zinc-500">No SSH connections saved here yet.</p>}
 </section>;
}
