import React,{useEffect,useRef,useState} from 'react';
import {api} from '../api.js';
import ComputerAccess from './ComputerAccess.jsx';
import SshSetup from './SshSetup.jsx';
const button='rounded-lg border border-zinc-700 px-3 py-2 text-sm hover:bg-zinc-800 disabled:opacity-40';
const field='w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2 text-sm';
const initial={label:'',host:'',port:22,username:'',auth_type:'key',private_key:'',passphrase:'',password:'',fingerprint:'',allow_agent:false,tailnet_device_id:'',jump_id:''};
export default function SshConnections({kind,id,focus=false}){
 const [data,setData]=useState({connections:[],inherited:[]}),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[network,setNetwork]=useState(null),[setup,setSetup]=useState(null);
 const heading=useRef(null);
 useEffect(()=>{if(focus){heading.current?.scrollIntoView({block:'start'});heading.current?.focus({preventScroll:true});}},[focus]);
 const base=kind==='owner'?'/api/account/ssh':`/api/${kind}/${id}/ssh`;const generation=useRef(0),writing=useRef(false);const load=async()=>{const n=++generation.current;const next=await api.get(base);if(n===generation.current)setData(next);};
 useEffect(()=>{setForm(null);setSetup(null);let active=true,pending=false;const refresh=async()=>{if(!active||pending||writing.current)return;pending=true;try{await load();if(active)setError('');}catch(e){if(active){setError(e.message);if([403,404].includes(e.status)){setData({connections:[],inherited:[]});setForm(null);}}}finally{pending=false;}};const visible=()=>{if(document.visibilityState==='visible')refresh();};refresh();api.get('/api/account/tailscale').then(setNetwork).catch(()=>{});const timer=setInterval(visible,3000);window.addEventListener('focus',refresh);return()=>{active=false;generation.current++;clearInterval(timer);window.removeEventListener('focus',refresh);};},[base]);
 async function act(fn){writing.current=true;generation.current++;setBusy(true);setError('');setNotice('');try{await fn();await load();return true;}catch(e){await load().catch(()=>{});setError(e.message);return false;}finally{writing.current=false;setBusy(false);}}
 return <section className="space-y-4"><div className="flex flex-wrap gap-3 items-center justify-between"><div><h3 ref={heading} tabIndex={-1} className="font-semibold">{kind==='owner'?'SSH across your companies':'SSH connections'}</h3><p className="text-xs text-zinc-400 mt-2">{kind==='owner'?'Save once and share with all current and future companies and projects in your account. Members need SSH permission for the company or project they access.':kind==='companies'?'Account connections are inherited automatically. Connections saved here are shared with this company’s projects.':'Account and company connections are inherited automatically. Add a connection here only for this project.'} Agent access applies only to Work mode.</p></div><button className={button} onClick={()=>{setForm(null);setSetup({});}}>Add SSH connection</button></div>
  {kind!=='owner'&&data.can_manage_account&&<button className={button+' text-indigo-200'} onClick={()=>window.dispatchEvent(new CustomEvent('boardly-account',{detail:{section:'ssh'}}))}>Manage account SSH connections</button>}
  <p className="text-xs text-zinc-400">Connect your own computers with no per-computer subscription charge or fixed connection-count limit. This is SSH command access, not a hosted graphical desktop. Members still need SSH permission for their company or project.</p>
  {error&&<p role="alert" className="text-sm text-rose-300">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-300">{notice}</p>}
  {data.can_manage_account&&!!data.connections.length&&<details className="space-y-3"><summary className="cursor-pointer font-medium">Computer sharing & assignment</summary><p className="text-xs text-zinc-400">The account owner always retains access. Assign one member for individual use, several to share, or choose all permitted members. Changes apply to new commands and stop active brokered connections when access is revoked; remote processes may continue.</p>{data.connections.map(c=><ComputerAccess key={c.id} connection={c} members={data.members||[]} busy={busy} onSave={value=>act(async()=>{await api.patch(base+'/'+c.id,{access:value});setNotice(c.label+': computer access saved');})}/>)}</details>}
  {setup&&<SshSetup key={base+':'+(setup.connection?.id||'new')} base={base} kind={kind} network={network} saved={setup.connection?setup:null} onDone={message=>{setSetup(null);act(async()=>setNotice(message));}} onCancel={()=>{setSetup(null);load().catch(()=>{});}}/>}
  {!setup&&!form&&<button className={button} onClick={()=>setForm({...initial})}>Use an existing key or password</button>}
  {form&&<form className="p-4 rounded-xl border border-indigo-500/30 space-y-3" onSubmit={e=>{e.preventDefault();act(async()=>{await (form.id?api.patch(base+'/'+form.id,form):api.post(base,form));setForm(null);setNotice('SSH connection saved');});}}>
   <label className="block text-xs text-zinc-400">Network / device<select aria-label="Network / device" className={field+' mt-1'} disabled={!!form.id} value={form.tailnet_device_id||''} onChange={e=>{const d=network?.devices.find(d=>d.id===e.target.value);setForm({...form,tailnet_device_id:e.target.value,jump_id:'',host:d?(d.dns_name||d.addresses[0]):''});}}><option value="">Standard SSH hostname or IP</option>{network?.state==='Running'&&network.devices.map(d=><option key={d.id} value={d.id}>Tailscale · {d.name}{d.online?'':' (offline)'}</option>)}</select></label>
   {network?.state!=='Running'&&<p className="text-xs text-zinc-500">Connect Tailscale in Account & AI to select your private devices.</p>}
   {kind==='owner'&&<label className="block text-xs text-zinc-400">Jump host<select aria-label="Jump host" className={field+' mt-1'} value={form.jump_id||''} disabled={!!form.tailnet_device_id} onChange={e=>setForm({...form,jump_id:e.target.value})}><option value="">Connect directly</option>{data.connections.filter(c=>c.id!==form.id).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></label>}
   <div className="grid sm:grid-cols-2 gap-3">{[['label','Connection name'],['host','Hostname or IP'],['port','Port'],['username','SSH username']].map(([key,label])=><label key={key} className="text-xs text-zinc-400">{label}<input required readOnly={key==='host'&&!!form.tailnet_device_id} className={field+' mt-1'} type={key==='port'?'number':'text'} min={key==='port'?1:undefined} max={key==='port'?65535:undefined} value={form[key]} onChange={e=>setForm({...form,[key]:key==='port'?Number(e.target.value):e.target.value})}/></label>)}</div>
   {form.id&&<p className="text-xs text-zinc-400">Credentials are saved. Leave them blank to keep the current key or password.</p>}
   <label className="block text-xs text-zinc-400">Authentication<select aria-label="Authentication" className={field+' mt-1'} value={form.auth_type} onChange={e=>setForm({...form,auth_type:e.target.value})}><option value="key">Private SSH key</option><option value="password">Password</option></select></label>
   {form.auth_type==='key'?<><label className="block text-xs text-zinc-400">Private key<textarea required={!form.id} autoComplete="off" spellCheck={false} className={field+' mt-1 font-mono'} rows={4} value={form.private_key} onChange={e=>setForm({...form,private_key:e.target.value})}/></label><label className="block text-xs text-zinc-400">Key passphrase (if needed)<input autoComplete="new-password" type="password" className={field+' mt-1'} value={form.passphrase} onChange={e=>setForm({...form,passphrase:e.target.value})}/></label></>:<label className="block text-xs text-zinc-400">SSH password<input required={!form.id} autoComplete="new-password" type="password" className={field+' mt-1'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}
   <label className="block text-xs text-zinc-400">Trusted host fingerprint<input required className={field+' mt-1 font-mono'} placeholder="SHA256:…" value={form.fingerprint} onChange={e=>setForm({...form,fingerprint:e.target.value.trim()})}/></label><p className="text-xs text-zinc-500">Copy the SHA256 host-key fingerprint from your server console or a trusted existing SSH connection. Boardly checks it before sending credentials.</p>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={form.allow_agent} onChange={e=>setForm({...form,allow_agent:e.target.checked})}/>{kind==='owner'?'Allow Work agents in all my companies':'Allow Work agents to use this connection'}</label><div className="flex gap-2"><button disabled={busy} className={button+' bg-indigo-600'}>Save SSH connection</button><button type="button" className={button} onClick={()=>setForm(null)}>Cancel</button></div>
  </form>}
  {data.connections.map(c=><article key={c.id} className="border border-zinc-700 rounded-xl p-4 space-y-3"><div><h4 className="font-medium">{c.label}</h4><p className="text-xs text-zinc-400 break-all">{c.tailnet_device_id?'Tailscale · ':''}{c.username}@{c.host}:{c.port} · {c.auth_type==='key'?'Private key stored':'Password stored'}</p><p className="text-xs text-zinc-500 break-all mt-1">{c.fingerprint||'Add a trusted host fingerprint to enable this connection.'}</p>{c.jump_id&&<p className="text-xs text-zinc-400 mt-1">Via jump host: {data.connections.find(h=>h.id===c.jump_id)?.label||'Owner connection'}</p>}</div><label className="flex gap-2 text-sm"><input disabled={busy||!c.fingerprint} type="checkbox" checked={!!c.allow_agent} onChange={e=>{const enabled=e.target.checked;setData(old=>({...old,connections:old.connections.map(row=>row.id===c.id?{...row,allow_agent:Number(enabled)}:row)}));act(()=>api.patch(base+'/'+c.id,{allow_agent:enabled}));}}/>{kind==='owner'?'Allow Work agents in all my companies':'Allow Work agents'}</label><div className="flex flex-wrap gap-2">{c.generated_key&&<button disabled={busy} className={button} onClick={()=>act(async()=>{setForm(null);setSetup(await api.get(base+'/'+c.id+'/setup'));})}>{c.fingerprint?'Show public key':'Finish key setup'}</button>}<button disabled={busy} className={button} onClick={()=>{setSetup(null);setForm({...initial,...c,allow_agent:!!c.allow_agent,private_key:'',passphrase:'',password:''});}}>Edit connection</button><button disabled={busy} className={button} onClick={()=>act(async()=>{await api.post(base+'/'+c.id+'/test',{});setNotice(c.label+': authenticated successfully from Boardly cloud');})}>Test connection</button><button disabled={busy} className={button} onClick={()=>act(()=>api.del(base+'/'+c.id))}>Remove connection</button></div></article>)}
  {!!data.inherited.length&&<div className="rounded-xl border border-zinc-800 p-4"><h4 className="text-sm font-medium">Shared SSH connections</h4>{data.inherited.map(c=><div key={c.id} className="mt-3 space-y-2"><p className="text-sm text-zinc-400 break-all">{c.label} · {c.username}@{c.host} · {c.company_id===null?'all owner companies · managed in Account & AI':'managed in Company → SSH'}</p><p className="text-xs text-zinc-500">{c.allow_agent?'Available to Work agents in this project':'Agent access paused'}{c.tested_at?' · Last authenticated '+new Date(c.tested_at).toLocaleString():''}</p><button disabled={busy||!c.fingerprint} className={button} aria-label={'Test shared SSH connection '+c.label} onClick={()=>act(async()=>{await api.post(base+'/'+c.id+'/test',{});setNotice(c.label+': authenticated successfully from Boardly cloud');})}>Test connection</button></div>)}</div>}
  {!data.connections.length&&!data.inherited.length&&!form&&!setup&&<p className="text-sm text-zinc-500">No SSH connections saved here yet.</p>}
 </section>;
}
